epicmaxco/vuestic-ui

- src/components/vuestic-components/va-select/VaSelect.vue
> fix: select option

- src/components/vuestic-components/va-file-upload/VaFileUpload.demo.vue
- src/components/vuestic-components/va-file-upload/VaFileUpload.vue
- src/components/vuestic-components/va-file-upload/VaFileUploadGalleryItem.vue
- src/components/vuestic-components/va-file-upload/VaFileUploadList.vue
- src/components/vuestic-components/va-file-upload/VaFileUploadListItem.vue
- src/components/vuestic-components/va-file-upload/va-file-upload-docs.md
- src/components/vuestic-sass/icons/icons.scss
close [600](https://github.com/epicmaxco/vuestic-admin/issues/600)
Note: Material Icons were imported to fix bug with delete icon
> feat: va-file-upload default file list

- src/components/vuestic-components/va-data-table/VaDataTable.demo.vue
- src/components/vuestic-components/va-data-table/VaDataTable.vue
- src/components/vuestic-components/va-data-table/VaDataTableCustomDataManagerExample.vue
Added property to set custom dataManager. Created test example.
Issue [#655](https://github.com/epicmaxco/vuestic-admin/issues/655) in vuestic-admin.
> feat: data manager in va-data-table exposed

- src/components/vuestic-components/va-button/VaButton.vue
> disabled button brightness off

- src/components/vuestic-components/va-data-table/VaDataTable.vue
Add a sort order without creating a data-manager
> Add sort order to data table

- src/components/vuestic-components/va-radio-button/VaRadioButton.vue
- yarn.lock
#58
* Fix style bug
* Fix eslint error in VaRadioButton.vue:66
> fix: disabled radio button has an incorrect style

- src/components/vuestic-components/va-file-upload/VaFileUpload.vue
> button hover fix

- src/components/vuestic-components/va-button/VaButton.vue
- src/components/vuestic-components/va-color-presentation/VaColorPresentation.vue
- src/services/ColorThemePlugin.js
- src/services/color-functions.js
fix #28 
Need checked hover color change solution.
I change filter brightness(115%) to brightness(110%) on hover.
wass:
https://user-images.githubusercontent.com/22664941/64702510-5ca40b80-d4b3-11e9-81a5-fa83428a4a89.png
became:
https://monosnap.com/file/oO7JqyySQb1BLc4Y772HL7gKqLDi3R
> Fix/colors gradient and hover.

- src/components/context-test/ContextTest.demo.vue
- src/components/context-test/ContextTest.vue
- src/components/context-test/context-provide/ContextPlugin.js
- src/components/vuestic-components/va-button/VaButton.vue
- src/services/ColorThemePlugin.js
- yarn.lock
* Make context fully dynamic
* Apply new syntax to button component
> context 2.0

- src/components/vuestic-components/va-chart/VaChart.demo.vue
- src/components/vuestic-components/va-chart/VaChart.vue
Fix #81 
Fix property name of va-chart child component
> fix considers option props of  va-chart component

- src/components/vuestic-components/va-navbar/VaNavbar.vue
- src/components/vuestic-components/va-sidebar/VaSidebar.vue
- src/components/vuestic-components/va-sidebar/VaSidebarLinkGroup.vue
- src/components/vuestic-components/va-topbar/VaTopbar.vue
- src/components/vuestic-components/va-topbar/VaTopbarLink.vue
- src/components/vuestic-components/va-topbar/VaTopbarLinkGroup.vue
- src/components/vuestic-plugin.js
:warning: **Important**: make sure to review/merge the [admin-part of this PR](https://github.com/epicmaxco/vuestic-admin/pull/646) as well.
Also make sure to checkout respective branches on *both* repos during testing/reviewing.
> feat: va-topbar

- package.json
- src/vue-book/book-main.js
- vue.config.js
- yarn.lock
<details>
```vue
// Your code
```
</details>
> added build version to console

- src/components/vuestic-components/va-form/VaForm.demo.vue
- src/components/vuestic-components/va-form/VaForm.vue
- src/components/vuestic-components/va-input/VaInput.vue
> fix(v-form): rework form validation

- src/components/vuestic-components/va-avatar/VaAvatar.vue
- src/mixins/SizeMixin.js
- src/services/ColorThemePlugin.js
fix contest logic for VaAvatar component
<details>
```vue
// Your code
```
</details>
> fix VaAvatar context logic

- src/components/vuestic-components/va-select/VaSelect.vue
Closes
epicmaxco/vuestic-admin/issues/719
epicmaxco/vuestic-admin/issues/717
epicmaxco/vuestic-admin/issues/714
Cherry-pick to develop
<details>
```vue
// Your code
```
</details>
> fix VaSelect label style

- src/components/vuestic-components/va-select/VaSelect.vue
- src/components/vuestic-components/va-timeline/VaTimelineItem.vue
Related to epicmaxco/vuestic-admin/pull/734
<details>
```vue
// Your code
```
</details>
> corporate theme fixes

- package.json
- yarn.lock
> update vue-book version

- src/components/vuestic-components/va-progress-bar/progress-types/VaProgressBar.demo.vue
- src/components/vuestic-components/va-progress-bar/progress-types/VaProgressBar.vue
Implement reverse VaProgressBar https://github.com/epicmaxco/vuestic-ui/issues/143
> implement: reverse VaProgressBar

- src/components/vuestic-components/va-slider/VaSlider.vue
> Fix: VaSlider bugs

- package.json
- src/components/context-test/context-provide/context/va-icons-framework-config.js
- src/components/vuestic-components/va-data-table/VaDataTable.spec.js
- src/components/vuestic-components/va-icon/VaIcon.demo.vue
- src/components/vuestic-components/va-icon/VaIcon.vue
- src/components/vuestic-components/va-inner-loading/VaInnerLoading.vue
- src/components/vuestic-components/va-select/VaSelect.vue
- yarn.lock
closes #188
Remove epic-spinners
> fix: remove epic-spinners

- src/components/vuestic-components/va-color-picker/ColorDot.vue
- src/components/vuestic-components/va-color-picker/VaColorInput.vue
Fixes #76:  incorrect position  of color input dot.
> Fix 76 incorrect color input dot position

- src/components/vuestic-mixins/SelectableList/SelectableListMixin.js
- src/components/vuestic-mixins/SelectableList/SelectableListMixin.spec.js
- src/components/vuestic-mixins/testIsSelectableList.js
- src/services/utils.js
- Add SelectableListMixin
- Add testIsSelectableList helper to ensure component uses the mixin
- Add unit tests
Closes #192
> Selectable List Mixin implemented:

- src/components/vuestic-components/va-slider/VaSlider.vue
Fixes #190 incorrect slider track display
Added proper css, fixed default props.
> Feat 190 added insufficient styles to css

- docs/components/VaDivider.md
- src/components/vuestic-components/va-divider/DividerWithList.vue
- src/components/vuestic-components/va-divider/VaDivider.demo.vue
- src/components/vuestic-components/va-divider/VaDivider.spec.js
- src/components/vuestic-components/va-divider/VaDivider.vue
- src/components/vuestic-components/va-list/VaList.demo.vue
This should close https://github.com/epicmaxco/vuestic-ui/issues/40
<details>
```vue
<VaList>
<VaItem>Item 1</VaItem>
<VaDivider />
<VaItem>Item 2</VaItem>
<VaDivider />
<VaItem>Item 3</VaItem>
</VaList>
```
</details>
> feat(components): create VaDivider component

- docs/components/VaCheckbox.md
- src/components/vuestic-components/va-checkbox/VaCheckbox.demo.vue
- src/components/vuestic-components/va-checkbox/VaCheckbox.vue
- src/components/vuestic-components/va-option-list/VaOptionList.demo.vue
- src/components/vuestic-components/va-option-list/VaOptionList.md
- src/components/vuestic-components/va-option-list/VaOptionList.spec.js
- src/components/vuestic-components/va-option-list/VaOptionList.vue
- src/components/vuestic-mixins/SelectableList/SelectableListMixin.js
- src/components/vuestic-mixins/SelectableList/SelectableListMixin.spec.js
- src/components/vuestic-mixins/testIsFormComponent.js
- src/components/vuestic-mixins/testIsSelectableList.js
- src/services/utils.js
- src/services/utils.spec.js
- Add OptionList component
- Add tests
- Add some changes to SelectableListMixin
- Add left-label prop to VaCheckbox component
Closes #88
> Add OptionList Component

- src/components/vuestic-components/va-checkbox/VaCheckbox.vue
Fixes #218 
Fixes bug with validation on blur from label to input and vice versa.
> fix: fixed mousedown validation

- package.json
- packages/ui/package.json
Should fix the pre-commit hook
To have it working you possibly need to do the following:
- empty your `.git/hooks` folder
- reinstall `node_modules`
> chore: fix pre-commit hook

- packages/vue-cli-plugin/README.md
- packages/vue-cli-plugin/generator/index.js
- packages/vue-cli-plugin/index.js
- packages/vue-cli-plugin/package.json
Create rudimentary vue-cli plugin.
Currently just adds vuestic-ui to deps.
> add rudimentary vue-cli plugin

- packages/docs/.eslintignore
- packages/docs/components/docs-content/DocsContent.vue
- packages/docs/components/docs-content/configs/rating.ts
- packages/docs/components/dynamic-template/DynamicTemplate.vue
- packages/docs/components/header/components/ColorDropdown.vue
- packages/docs/components/header/components/LanguageDropdown.vue
- packages/docs/components/header/components/VersionDropdown.vue
- packages/docs/components/rating-docs-demo/RatingColorDocsDemo.vue
- packages/docs/components/sidebar/NavigationRoutes.ts
- packages/docs/locales/en/en.json
- packages/docs/nuxt.config.js
- packages/docs/pages/components/va-form/vaFormApiOptions.ts
- packages/docs/pages/index.vue
- packages/docs/pages/index/rating.vue
- packages/docs/plugins/context.ts
- packages/docs/plugins/localeRoute.ts
- packages/docs/types/configTypes.ts
- packages/ui/src/components/vuestic-components/va-dropdown/VaDropdown.vue
- packages/ui/src/components/vuestic-components/va-rating/VaRatingItem.vue
> review fixes

- packages/ui/src/components/vuestic-components/va-file-upload/VaFileUpload.demo.vue
- packages/ui/src/components/vuestic-components/va-file-upload/VaFileUpload.vue
> Fix VaFileUpload not working with 'file-types' prop

- packages/docs/components/DocsCode.vue
`.code` class removed from prism container as `.va-content pre.code` styles are conflicting with Prism theme
> Add default prism theme

- packages/docs/components/header/Header.vue
- packages/docs/pages/index.vue
Add styles to prevent breaking on small screen sizes
> update styles for mobile

- packages/docs/components/DocsCode.vue
- packages/docs/components/docs-content/api/va-file-upload/VaFileUploadApi.vue
- packages/docs/components/docs-content/api/va-file-upload/vaFileUploadApiOptions.ts
- packages/docs/components/docs-content/configs/va-file-upload.ts
- packages/docs/components/sidebar/NavigationRoutes.ts
- packages/docs/examples/va-file-upload/Basic.vue
- packages/docs/examples/va-file-upload/DragAndDrop.vue
- packages/docs/examples/va-file-upload/Gallery.vue
- packages/docs/examples/va-file-upload/Validation.vue
- packages/docs/locales/en/en.json
- packages/docs/pages/index.vue
- packages/docs/pages/index/fileUpload.vue
- packages/docs/utilities/markdown-view/MarkdownView.vue
- packages/ui/src/components/vuestic-sass/resources/_variables.scss
- Add docs for FileUpload component
- Fix some styling issues
closes #266
> add FileUpload docs and fix some styling issues

- README.md
- package.json
- scripts/.eslintrc.js
- scripts/generators/component/Component.demo.vue.hbs
- scripts/generators/component/Component.spec.ts.hbs
- scripts/generators/component/Component.vue.hbs
- scripts/generators/component/Example.vue.hbs
- scripts/generators/component/api-options.ts.hbs
- scripts/generators/component/docPage.vue.hbs
- scripts/generators/component/index.js
- scripts/generators/component/page-config.ts.hbs
- scripts/generators/index.js
- yarn.lock
Created the script which allows auto-generating boilerplate code for common parts of vuestic-ui.
> chore: create boilerplate code generator

- packages/docs/components/page-configs/va-button/api-options.ts
- packages/docs/components/page-configs/va-button/page-config.ts
- packages/docs/components/sidebar/navigationScheme.json
- packages/docs/examples/va-button/Default.vue
- packages/docs/examples/va-button/WithColor.vue
- packages/docs/examples/va-button/WithIcon.vue
- packages/docs/examples/va-button/WithSize.vue
- packages/docs/examples/va-button/WithStyle.vue
- packages/docs/locales/en/en.json
- packages/docs/pages/index/button.vue
- packages/ui/src/components/vuestic-components/va-button/VaButton.demo.vue
- packages/ui/src/components/vuestic-components/va-button/VaButton.vue
> Docs for Button component

- packages/docs/components/page-configs/va-avatar/api-options.ts
- packages/docs/components/page-configs/va-avatar/page-config.ts
- packages/docs/components/sidebar/navigationScheme.json
- packages/docs/examples/va-avatar/Color.vue
- packages/docs/examples/va-avatar/Default.vue
- packages/docs/examples/va-avatar/Size.vue
- packages/docs/examples/va-avatar/WithEmail.vue
- packages/docs/examples/va-avatar/WithIcon.vue
- packages/docs/examples/va-avatar/WithImage.vue
- packages/docs/locales/en/en.json
- packages/docs/pages/index/avatar.vue
> feat(310): Add avatar docs

- packages/docs/examples/va-avatar/Size.vue
- packages/docs/locales/en/en.json
- packages/docs/package.json
- packages/ui/package.json
- packages/ui/src/components/vuestic-components/va-avatar/VaAvatar.vue
- packages/ui/src/components/vuestic-components/va-rating/VaRating.vue
- packages/ui/src/mixins/SizeMixin.ts
- packages/ui/src/services/api-docs/ApiDocs.vue
- packages/ui/src/services/api-docs/ManualApiOptions.ts
- packages/ui/src/services/api-docs/api-docs-helpers.ts
- packages/ui/src/services/api-docs/default-api-options.ts
- yarn.lock
- rename prop inside SizeMixin
- Add text explaining font-size prop behavior in avatar component
> Fix issue with avatar font size

- packages/docs/components/page-configs/va-infinite-scroll/api-options.ts
- packages/docs/components/page-configs/va-infinite-scroll/page-config.ts
- packages/docs/components/sidebar/navigationScheme.json
- packages/docs/examples/va-infinite-scroll/CustomTarget.vue
- packages/docs/examples/va-infinite-scroll/Default.vue
- packages/docs/examples/va-infinite-scroll/Disabled.vue
- packages/docs/examples/va-infinite-scroll/Reverse.vue
- packages/docs/locales/en/en.json
- packages/docs/pages/index/infinite-scroll.vue
- packages/docs/plugins/jsdom.ts
- packages/ui/src/components/vuestic-components/va-badge/VaBadge.vue
- packages/ui/src/components/vuestic-components/va-infinite-scroll/tests/VaInfiniteScroll.spec.ts
- packages/ui/src/components/vuestic-plugin.js
> Docs for VaInifiniteScroll component

- packages/docs/components/page-configs/va-infinite-scroll/api-options.ts
- packages/ui/src/services/api-docs/ManualApiOptions.ts
- packages/ui/src/services/api-docs/api-docs-helpers.ts
> feat/ docs manual type

- packages/ui/src/components/vuestic-components/va-slider/VaSlider.vue
> (fix) slider transition

- packages/ui/src/components/vuestic-components/va-infinite-scroll/VaInfiniteScroll.vue
- packages/ui/src/components/vuestic-components/va-progress-bar/progress-types/VaProgressCircle.vue
> (fix) infinite scroll

- packages/docs/components/page-configs/va-radio/api-options.ts
- packages/docs/components/page-configs/va-radio/page-config.ts
- packages/docs/components/sidebar/navigationScheme.json
- packages/docs/examples/va-radio/Color.vue
- packages/docs/examples/va-radio/CustomLabels.vue
- packages/docs/examples/va-radio/Default.vue
- packages/docs/examples/va-radio/Disabled.vue
- packages/docs/locales/en/en.json
- packages/docs/locales/es/es.json
- packages/docs/pages/index/radio.vue
> docs for va-radio

- packages/ui/src/components/vuestic-components/va-option-list/VaOptionList.vue
> fix option-list

- packages/docs/components/page-configs/va-button/api-options.ts
- packages/docs/locales/en/en.json
- packages/ui/src/components/vuestic-components/va-button/VaButton.demo.vue
- packages/ui/src/components/vuestic-components/va-button/VaButton.vue
- packages/ui/src/components/vuestic-components/va-button/tests/VaButton.spec.ts
> Feat/va-button public methods (blur/focus)

- packages/ui/src/components/vuestic-components/va-date-picker/VaDatePicker.vue
- packages/ui/src/components/vuestic-plugin.js
> Fix: vuestic-plugin va-date-picker usage

- packages/docs/locales/en/en.json
> fix: minor docs

- packages/ui/jest.config.js
- packages/ui/package.json
- packages/ui/src/components/vuestic-components/va-tag/VaTag.vue
- packages/ui/src/components/vuestic-components/va-tag/tests/__snapshots__/VaTag.spec.ts.snap
- yarn.lock
> fix: build, jest css imports, VaTag router-link fixes

- packages/docs/components/page-configs/va-select/api-options.ts
- packages/docs/components/page-configs/va-select/page-config.ts
- packages/docs/components/sidebar/navigationScheme.json
- packages/docs/examples/va-select/AllowCreate.vue
- packages/docs/examples/va-select/Decorators.vue
- packages/docs/examples/va-select/Default.vue
- packages/docs/examples/va-select/Searchable.vue
- packages/docs/examples/va-select/Slots.vue
- packages/docs/examples/va-select/State.vue
- packages/docs/examples/va-select/Tags.vue
- packages/docs/examples/va-select/Validation.vue
- packages/docs/examples/va-select/Variations.vue
- packages/docs/locales/en/en.json
- packages/docs/locales/es/es.json
- packages/docs/pages/index/select.vue
- packages/ui/src/components/vuestic-components/va-dropdown/VaDropdown.vue
- packages/ui/src/components/vuestic-components/va-input/VaInput.vue
- packages/ui/src/components/vuestic-components/va-select/VaSelect.demo.vue
- packages/ui/src/components/vuestic-components/va-select/VaSelect.vue
- packages/ui/src/components/vuestic-components/va-select/VaSelectOptionList.vue
- packages/ui/src/components/vuestic-components/va-select/tests/VaSelect.spec.ts
VaSelect docs and some minor fixes
> VaSelect docs

- packages/ui/src/components/vuestic-components/va-rating/tests/VaRating.spec.ts
- packages/ui/src/components/vuestic-components/va-select/VaSelect.vue
- packages/ui/src/components/vuestic-components/va-select/tests/VaSelect.spec.ts
Fix/va-select test, focused state
> Fix/va-select test, focused state

- packages/ui/src/components/vuestic-components/va-avatar/tests/VaAvatar.spec.ts
- packages/ui/src/components/vuestic-components/va-badge/tests/VaBadge.spec.ts
- packages/ui/src/components/vuestic-components/va-breadcrumbs/tests/VaBreadcrumbs.spec.ts
- packages/ui/src/components/vuestic-components/va-button-dropdown/tests/VaButtonDropdown.spec.ts
- packages/ui/src/components/vuestic-components/va-button/tests/VaButton.spec.ts
- packages/ui/src/components/vuestic-components/va-card/tests/VaCard.spec.ts
- packages/ui/src/components/vuestic-components/va-icon/tests/VaIcon.spec.ts
- packages/ui/src/components/vuestic-components/va-input/tests/VaInput.spec.ts
- packages/ui/src/components/vuestic-components/va-pagination/tests/VaPagination.spec.ts
- packages/ui/src/components/vuestic-components/va-progress-bar/progress-types/tests/VaProgressBar.spec.ts
- packages/ui/src/components/vuestic-components/va-progress-bar/progress-types/tests/VaProgressCircle.spec.ts
- packages/ui/src/components/vuestic-components/va-radio/tests/VaRadio.spec.ts
- packages/ui/src/components/vuestic-components/va-rating/tests/VaRating.spec.ts
- packages/ui/src/components/vuestic-components/va-select/tests/VaSelect.spec.ts
- packages/ui/src/components/vuestic-components/va-slider/tests/VaSlider.spec.ts
- packages/ui/src/components/vuestic-components/va-tabs/VaTabs.vue
- packages/ui/src/components/vuestic-components/va-tabs/tests/VaTabs.spec.ts
- packages/ui/src/components/vuestic-components/va-tag/tests/VaTag.spec.ts
- packages/ui/src/components/vuestic-mixins/SelectableMixin/SelectableMixin.spec.ts
- packages/ui/src/services/ColorThemePlugin.spec.ts
- packages/ui/src/services/testHasColorThemeMixin.ts
> fix color mixin

- packages/ui/src/components/vuestic-components/va-dropdown/VaDropdown.vue
> fix dropdown

- packages/ui/src/components/vuestic-components/va-data-table/VaDataTable.vue
- packages/ui/src/components/vuestic-components/va-data-table/VaDataTableCustomDataManagerExample.vue
> fix sort in datatable. fix sort in example

- packages/docs/components/sidebar/Sidebar.vue
- packages/ui/src/components/vuestic-components/va-breadcrumbs/VaBreadcrumbsItem.vue
- packages/ui/src/components/vuestic-components/va-button/VaButton.vue
- packages/ui/src/components/vuestic-components/va-card/VaCard.vue
- packages/ui/src/components/vuestic-components/va-list/VaListItem.vue
- packages/ui/src/components/vuestic-components/va-tabs/VaTab.vue
- packages/ui/src/components/vuestic-components/va-tag/VaTag.vue
- packages/ui/src/components/vuestic-mixins/RouterLinkMixin/RouterLinkMixin.ts
Closes #442. Add functionality to resolve router-link and nuxt-link href prop for SEO optimisation.
> Router link mixin href feature

- packages/docs/components/sidebar/Sidebar.vue
- packages/ui/src/components/vuestic-components/va-breadcrumbs/VaBreadcrumbsItem.vue
- packages/ui/src/components/vuestic-components/va-button/VaButton.vue
- packages/ui/src/components/vuestic-components/va-card/VaCard.vue
- packages/ui/src/components/vuestic-components/va-list/VaListItem.vue
- packages/ui/src/components/vuestic-components/va-tabs/VaTab.vue
- packages/ui/src/components/vuestic-components/va-tag/VaTag.vue
- packages/ui/src/components/vuestic-mixins/RouterLinkMixin/RouterLinkMixin.ts
Reverts epicmaxco/vuestic-ui#443
> Revert "Router link mixin href feature"

- packages/docs/components/header/Header.vue
- packages/docs/components/header/components/HeaderSelector.vue
- packages/docs/components/header/components/VersionDropdown.vue
Fixes responsive layout of docs header
> fix: response layout fix

- packages/docs/components/header/Header.vue
- packages/docs/nuxt.config.js
- packages/docs/pages/index.vue
- packages/ui/src/components/vuestic-sass/resources/_variables.scss
fix #433
fixed mobile view (added body min-width and viewport tag)
added meta tags(title, description etc.), fixed header and main tags
> issues/433 - fixed mobile view

- packages/docs/layouts/default.vue
> fix: correct body width

- packages/docs/assets/fonts.scss
> fix: font size

- packages/ui/src/components/vuestic-components/va-slider/VaSlider.vue
Fix the slider bug #440
</details>
> fix/slider #440

- packages/docs/components/page-configs/styles/va-table/page-config.ts
- packages/docs/components/sidebar/navigationRoutes.ts
- packages/docs/examples/va-table/Clickable.vue
- packages/docs/examples/va-table/Default.vue
- packages/docs/examples/va-table/Hoverable.vue
- packages/docs/examples/va-table/Striped.vue
- packages/docs/locales/en/en.json
- packages/docs/locales/es/es.json
- packages/docs/pages/styles/table.vue
> add table docs

- packages/ui/src/components/vuestic-components/va-slider/VaSlider.vue
> fix keyboard navigation

- packages/ui/src/components/vuestic-components/va-sidebar/VaSidebar.vdemo.vue
- packages/ui/src/components/vuestic-components/va-sidebar/VaSidebar.vue
> Fix sidebar default color and demo

- packages/ui/src/components/vuestic-components/va-tabs/VaTabs.vue
fix tabs paggination (part of #499)
update pagination status and fill free right space in container  when window resize event received
<details>
```vue
// Your code
```
</details>
> fix tabs pagination (#499)

- packages/ui/src/components/vuestic-components/va-icon/va-iconset/VaIconMenuCollapsed.vue
- packages/ui/src/components/vuestic-components/va-navbar/VaNavbar.vdemo.vue
- packages/ui/src/components/vuestic-components/va-navbar/VaNavbar.vue
- packages/ui/src/components/vuestic-components/va-navbar/VaNavbarItem/VaNavbarItem.vue
- packages/ui/src/components/vuestic-components/va-navbar/index.ts
- packages/ui/src/components/vuestic-plugin.ts
closes #523
Added navbar demo. Refactored unusable navbar component.
Does the navbar have the correct behavior? Maybe it needs additional functionality.
> Added navbar demo. Refactored navbar.

- packages/ui/src/components/vuestic-sass/global/_typography.scss
Before:
After:
<details>
```vue
// Your code
```
</details>
> Fix extra margin for nested ul tags in typography.

- packages/ui/src/components/vuestic-components/va-card/VaCard.vdemo.vue
- packages/ui/src/components/vuestic-components/va-card/VaCard.vue
- packages/ui/src/components/vuestic-components/va-card/VaCardContent.vue
- packages/ui/src/components/vuestic-components/va-card/VaCardTitle.vue
Now VaCard has not overflow: hidden and dropdowns can be shown correctly.
<details>
```vue
// Your code
```
</details>
> Remove overflow hidden for a card, because dropdown was not visible.

- packages/ui/src/components/vuestic-components/va-card/VaCard.vue
To
<details>
```vue
// Your code
```
</details>
> Fix / width 100% for va-card-inner.

- packages/ui/src/components/vuestic-components/va-navbar/VaNavbar.vdemo.vue
- packages/ui/src/components/vuestic-components/va-navbar/VaNavbar.vue
> Added color prop to Navbar.

- packages/ui/src/components/vuestic-components/va-toast/VaToast.vue
- packages/ui/src/components/vuestic-sass/resources/_variables.scss
> Removed border for toast.

- packages/ui/src/components/vuestic-components/va-tabs/VaTabs.vue
fix `grow tabs should be like this` subtask
> Fix for #499 / tabs grow

- packages/ui/src/components/vuestic-components/va-select/VaSelect.vdemo.vue
- packages/ui/src/components/vuestic-components/va-select/VaSelect.vue
- packages/ui/src/components/vuestic-components/va-select/getDemoData.ts
Data in demo:
```
[
{
text: 'one',
icon: 'info',
},
{
text: 'two',
icon: 'face',
},
{
text: 'three',
icon: 'warning',
},
]
```
Before:
All items are highlighted when hovering.
Working on only if data items have `id` keys.
After:
-----
Also, I think it needs a deeper refactoring
> Fix broken select

- packages/ui/build/config.js
- packages/ui/build/config.ts
There was an error after webpack build. Named exports was `undefined`. This fix allow webpack to compile named exports that allow ts create declarations properly.
> Fix named export in webpack build.

- packages/vue-cli-plugin/generator/index.js
Part of #232 issue
This PR improves vue-cli add generator to add import and use commands into the main file
> Vue-CLI add feature

- packages/vue-cli-docs/src/components/page-configs/getting-started/installation/page-config.ts
- packages/vue-cli-docs/src/helpers/DocsHelper.ts
- packages/vue-cli-docs/src/locales/en/en.json
WIP #232 
Add docs to the installation part of "getting started" section
> WIP: Installation docs

- packages/ui/package.json
- yarn.lock
<details>
```vue
// Your code
```
</details>
> Fix tests. Added ts-jest as a dependency.

- packages/ui/src/components/vuestic-components/va-config/VaConfig.demo.vue
- packages/ui/src/components/vuestic-components/va-icon/VaIcon.demo.vue
- packages/ui/src/main.ts
- packages/ui/src/services/global-config/global-config-plugin.ts
- packages/ui/src/services/global-config/global-config.ts
> fix#594. Now global config have merge and set methods.

- packages/ui/src/services/color-config/color-config.ts
- packages/ui/src/services/component-config/component-config.ts
> Configs types fixes.

- packages/vue-cli-docs/src/components/DocsCode.vue
- packages/vue-cli-docs/src/components/landing/Admin.vue
- packages/vue-cli-docs/src/components/landing/Customize.vue
- packages/vue-cli-docs/src/components/landing/Footer.vue
<details>
```vue
// Your code
```
</details>
> Minor docs fixes

- packages/ui/src/components/vuestic-components/va-button/VaButton.demo.vue
- packages/ui/src/components/vuestic-components/va-button/VaButton.vue
- packages/ui/src/components/vuestic-components/va-button/_variables.scss
closes #610
<details>
```vue
// Your code
```
</details>
> Rollback icon and rightIcon props. Bug fixes.

- packages/docs/src/components/landing/Admin.vue
- packages/docs/src/components/landing/Header.vue
- packages/docs/src/components/landing/StarsButton.vue
- packages/docs/src/examples/va-option-list/Example.vue
- packages/docs/src/examples/va-option-list/WithComplexData.vue
- packages/docs/src/examples/va-option-list/WithRadio.vue
- packages/docs/src/examples/va-option-list/WithSwitch.vue
- packages/docs/src/examples/va-sidebar/Color.vue
- packages/docs/src/examples/va-sidebar/Default.vue
- packages/docs/src/examples/va-sidebar/Hoverable.vue
- packages/docs/src/examples/va-sidebar/Minimized.vue
- packages/docs/src/examples/va-sidebar/MinimizedWidth.vue
- packages/docs/src/examples/va-sidebar/Position.vue
- packages/docs/src/examples/va-sidebar/VModel.vue
- packages/docs/src/examples/va-sidebar/Width.vue
- packages/ui/src/components/vuestic-components/va-file-upload/VaFileUpload.vue
- packages/ui/src/components/vuestic-components/va-image/VaImage.vue
> Minor fixes

- packages/docs/src/components/DocsAlert.vue
- packages/docs/src/components/DocsContent.vue
- packages/docs/src/components/DocsSubtitle.vue
- packages/docs/src/components/page-configs/getting-started/installation/page-config.ts
- packages/docs/src/helpers/DocsHelper.ts
- packages/docs/src/types/configTypes.ts
> feat(docs): add alert component for docs

- packages/docs/src/components/page-configs/ui-elements/va-sidebar-item/api-options.ts
- packages/docs/src/components/page-configs/ui-elements/va-sidebar-item/examples/active.ts
- packages/docs/src/components/page-configs/ui-elements/va-sidebar-item/examples/components.ts
- packages/docs/src/components/page-configs/ui-elements/va-sidebar-item/examples/icons.ts
- packages/docs/src/components/page-configs/ui-elements/va-sidebar-item/examples/index.ts
- packages/docs/src/components/page-configs/ui-elements/va-sidebar-item/examples/simple.ts
- packages/docs/src/components/page-configs/ui-elements/va-sidebar-item/page-config.ts
- packages/docs/src/components/sidebar/navigationRoutes.ts
- packages/docs/src/examples/va-sidebar-item/Active.vue
- packages/docs/src/examples/va-sidebar-item/Components.vue
- packages/docs/src/examples/va-sidebar-item/Icons.vue
- packages/docs/src/examples/va-sidebar-item/Simple.vue
- packages/docs/src/locales/en/en.json
- packages/docs/src/locales/es/es.json
- packages/docs/src/pages/ui-elements/sidebar-item.vue
- packages/ui/src/components/vuestic-components/va-sidebar/VaSidebarItem/VaSidebarItem.vue
closes #656 
http://localhost:8080/en/ui-elements/sidebar-item
> Fix #656. Added VaSidebarItem docs.

- packages/docs/src/components/page-configs/ui-elements/va-navbar/api-options.ts
- packages/docs/src/components/page-configs/ui-elements/va-navbar/page-config.ts
- packages/docs/src/components/sidebar/navigationRoutes.ts
- packages/docs/src/examples/va-navbar/Colors.vue
- packages/docs/src/examples/va-navbar/Default.vue
- packages/docs/src/examples/va-navbar/Shape.vue
- packages/docs/src/locales/en/en.json
- packages/docs/src/locales/es/es.json
- packages/docs/src/pages/ui-elements/navbar.vue
- packages/ui/src/components/vuestic-components/va-navbar/VaNavbar.vue
- packages/ui/src/components/vuestic-components/va-navbar/tests/VaNavbar.spec.ts
- packages/ui/src/services/color-config/color-config.ts
I have to add textColor prop for navbar, which by default is undefined. If textColor is undefined then we use `getTextColor` from our `color-functions`.
I removed unexpected shift for background color, so for now user can be sure that if he passes `#ffde00` color as a prop, then exactly this color will be used.
Also, I added documentation for VaNavbar.
> Added Navbar docs. Added shape and text color props to VaNavbar. 

- packages/docs/src/components/page-configs/ui-elements/va-sidebar-item/page-config.ts
- packages/docs/src/components/page-configs/ui-elements/va-sidebar/page-config.ts
- packages/docs/src/examples/va-sidebar-item/Colors.vue
- packages/docs/src/examples/va-sidebar/Color.vue
- packages/docs/src/examples/va-sidebar/Gradient.vue
- packages/docs/src/examples/va-sidebar/Position.vue
- packages/docs/src/locales/en/en.json
- packages/ui/src/components/vuestic-components/va-sidebar/VaSidebar.demo.vue
- packages/ui/src/components/vuestic-components/va-sidebar/VaSidebar.vue
- packages/ui/src/components/vuestic-components/va-sidebar/VaSidebarItem/VaSidebarItem.vue
<details>
```vue
// Your code
```
</details>
> Fix Sidebar colors.

- packages/ui/src/components/vuestic-components/va-button-dropdown/VaButtonDropdown.vue
> Fix button dropdown.

- packages/ui/src/components/vuestic-components/va-card/_variables.scss
> Remove overflow hidden from card.

- packages/docs/src/components/header/Header.vue
- packages/docs/src/layouts/default.vue
There was an issue with the margin around content and the language dropdown
<details>
I fixed margin and language dropdown
```vue
// Your code
```
</details>
> Fixed margin and language dropdown

- packages/docs/src/components/page-configs/ui-elements/va-select/page-config.ts
- packages/docs/src/examples/va-select/ObjectOptions.vue
- packages/docs/src/examples/va-select/TrackBy.vue
- packages/docs/src/locales/en/en.json
- packages/ui/src/components/vuestic-components/va-select/VaSelect.demo.vue
- packages/ui/src/components/vuestic-components/va-select/VaSelect.vue
- packages/ui/src/components/vuestic-components/va-select/VaSelectOptionList/VaSelectOptionList.vue
- packages/ui/src/components/vuestic-mixins/SelectableList/SelectableListMixin.ts
- packages/ui/src/services/utils.ts
For now, valueBy returns value in `v-model`, but still shows text from textBy.
> Fix #827. Fixed bug with trackby prop as functions.

- packages/vue-cli-plugin/.eslintrc.js
- packages/vue-cli-plugin/README.md
- packages/vue-cli-plugin/generator/index.js
- packages/vue-cli-plugin/generator/template/public/index.html
closes #832
Tested with 
```bash
vue create test-app
cd test-app
yarn add -D /path/to/vuestic-ui/packages/vue-cli-plugin
vue invoke vuestic-ui
```
Add fonts to index.html
Use vuestic-plugin in chained create app
Install specific vuestic-ui version.
> Add fonts to vue-cli-plugin

- packages/ui/src/components/vuestic-components/va-input/VaInput.vue
> Clicking on any point of input triggering focus.

- packages/docs/src/locales/en/en.json
close #866 
Added link to Material Icons list to docs on Icon config and Va-icon pages.
> #866 Added link to Material Icons list to docs

- packages/ui/src/services/color-config/color-config.ts
- packages/ui/src/services/color-config/color-functions.ts
- packages/ui/src/services/color-config/tests/color-functions.spec.ts
closes #841
Added setHSLAColor function and unit-test for it, as requested.
> Added setHSLAColor in addition of shiftHSLAColor.

- packages/docs/src/components/sidebar/Sidebar.vue
- packages/docs/src/components/sidebar/algolia-search/AlgoliaSearch.vue
- packages/docs/src/config/theme-config.ts
- packages/docs/src/examples/grid/Breakpoints.vue
- packages/docs/src/examples/grid/Default.vue
- packages/docs/src/examples/grid/Gutters.vue
- packages/docs/src/examples/grid/Offsets.vue
- packages/docs/src/examples/va-sidebar/Color.vue
- packages/docs/src/examples/va-sidebar/Gradient.vue
- packages/docs/src/examples/va-sidebar/Minimized.vue
- packages/docs/src/examples/va-sidebar/MinimizedWidth.vue
- packages/docs/src/examples/va-sidebar/VModel.vue
- packages/docs/src/examples/va-sidebar/Width.vue
- packages/ui/src/components/vuestic-components/va-sidebar/VaSidebar.vue
closes #711 
1. Fixed placeholder color as intended.
2. Added new colors to DOC's themes and adjusted names.
3. Fixed cases when used old color names with new theme.
> Fixed DOC's color palette and names.

- packages/docs/src/components/page-configs/ui-elements/va-avatar/page-config.ts
- packages/docs/src/examples/va-avatar/WithEmail.vue
- packages/docs/src/locales/en/en.json
- packages/ui/package.json
- packages/ui/src/components/vuestic-components/va-avatar/VaAvatar.demo.vue
- packages/ui/src/components/vuestic-components/va-avatar/VaAvatar.vue
> Moved gravatar in peer dependencies.

- packages/docs/src/components/sidebar/navigationRoutes.ts
Moved badge doc to view category. Close #892
> Moved badge doc to view category

- packages/ui/src/components/vuestic-components/va-dropdown/VaDropdown.vue
> Dropdown outside-click event fixed.

- packages/docs/package.json
- packages/docs/src/scripts/sync/prompt/translations.ts
- packages/docs/src/scripts/sync/translations.ts
Translations sync script. Partially cover #916
> Added sync script

- README.md
<details>
```vue
// Your code
```
</details>
> Typo fix: you're -> you've

- packages/docs/src/components/DocsAnchor.vue
- packages/docs/src/components/DocsContent.vue
- packages/docs/src/components/DocsHeadline.vue
- packages/docs/src/layouts/default.vue
close #932 
Added the anchor in the docs headline.
> add the anchor in the docs headline

- packages/docs/src/components/DocsApi/ApiDocs.vue
- packages/docs/src/components/DocsApi/ManualApiOptions.ts
- packages/docs/src/components/DocsApi/api-docs-helpers.ts
- packages/docs/src/components/DocsApi/component-options-compiler.ts
> Merge events from Component Options

- packages/docs/src/components/DocsNavigation.vue
Closes #919
Fixed clipboard button, using Clipboard API. Previously, v-clipboard plugin for nuxt was used for copy functional, but we rejected nuxt after moving from vue2 -> vue3.
> Fixed clipboard button.

- packages/docs/src/locales/en/en.json
mostly improved grammar, fixed a couple of typos, etc.
<details>
```vue
// Your code
```
</details>
> docs: small fixes for the "treeshaking" section

- packages/docs/src/locales/en/en.json
No huge additions/deletions. Just a reconsideration of what's already written: phrasing, grammar, typos, etc.
Should be reviewed by serving the docs locally ('cause it's pretty hard to understand the changes looking at the diffs).
> Docs/translations - reconsideration of english docs

- packages/docs/src/components/landing/Seamless/SeamlessAnotherButton.vue
- packages/docs/src/components/landing/Seamless/SeamlessAnotherCheckbox.vue
- packages/docs/src/components/landing/Seamless/SeamlessAnotherRangeSlider.vue
- packages/docs/src/components/landing/Seamless/SeamlessAnotherSelect.vue
smallfixes to @alygee 's PR for a better vuestic-styleguide conformance
> feat: better ripple effect + refact: SCSS style-cascading

- packages/ui/build/rollup/configs/cjs.js
- packages/ui/build/rollup/configs/esm.js
- packages/ui/build/rollup/configs/iife.js
- packages/ui/build/rollup/configs/index.js
- packages/ui/build/rollup/configs/styles.js
- packages/ui/build/rollup/plugins/rollup-delete-junk.js
- packages/ui/build/rollup/plugins/rollup-teaser-preset.js
- packages/ui/package.json
- packages/ui/rollup.config.js
- packages/ui/src/styles/global/global.scss
- packages/ui/src/styles/grid/_grid-spacing.scss
- packages/ui/src/styles/grid/grid-resources.scss
- packages/ui/src/styles/resources/resources.scss
- packages/ui/src/styles/vuestic-styles.scss
- yarn.lock
> Added styles separately to dist

- packages/docs/src/components/sidebar/Sidebar.vue
> fix: sidebar links should respect changes to the primary color

- packages/ui/build/rollup/configs/cjs.js
- packages/ui/build/rollup/configs/iife.js
- packages/ui/build/rollup/plugins/rollup-teaser-preset.js
- packages/ui/package.json
- packages/ui/src/components/va-option-list/VaOptionList.vue
- packages/ui/src/services/utils.spec.ts
- packages/ui/src/services/utils.ts
- yarn.lock
Close: https://github.com/epicmaxco/vuestic-ui/issues/1021
Changes:
- feat add UUID generator
- feat add test for UUID generator
- feat remove nodeBuiltinsPlugin
<details>
```vue
// Your code
```
</details>
New UUID looks like it:
esm node_modules before:
after:
> Add uuid generator

- packages/bundlers-tests/.gitignore
- packages/bundlers-tests/Readme.md
- packages/bundlers-tests/build-vuestic-ui.sh
- packages/bundlers-tests/index.html
- packages/bundlers-tests/jest.config.ts
- packages/bundlers-tests/package.json
- packages/bundlers-tests/src/App.vue
- packages/bundlers-tests/src/main.ts
- packages/bundlers-tests/src/shims-vue.d.ts
- packages/bundlers-tests/src/vite-env.d.ts
- packages/bundlers-tests/test/tree-shaking.spec.js
- packages/bundlers-tests/tsconfig.json
- packages/bundlers-tests/vite.config.ts
- packages/bundlers-tests/vue.config.js
- yarn.lock
Yarn workspace package that tests how vuestic-ui runs using vue-cli (webpack) and vite (rollup).
Please, check how it works for you during the review.
I'm not sure if you need to run
```lerna add vuestic-ui``` - should work fine without it. 
If you can not see components after build using `yarn serve:vite` or `yarn serve:webpack`, check out this PR which fixes that issue https://github.com/epicmaxco/vuestic-ui/pull/1029
> Bundlers test package

- packages/docs/src/locales/en/en.json
- packages/docs/src/locales/ru/ru.json
- packages/docs/src/scripts/generators/component/Component.vue.hbs
- packages/docs/src/scripts/generators/component/index.ts
close #1039
`yarn generate:component` script now works correctly.
Some of the docs links are fixed as well.
Imports inside generated files and paths are valid now, new files are created the way we want it.
</details>
> Fix #1039 generate component script

- packages/docs/jest.config.js
- packages/docs/package.json
- packages/docs/src/components/DocsApi/__tests__/api-docs-heper.spec.ts
- packages/docs/src/components/DocsApi/api-docs-helpers.ts
- packages/docs/src/components/page-configs/ui-elements/va-avatar/page-config.ts
- packages/docs/src/components/page-configs/ui-elements/va-date-picker/api-options.ts
- packages/docs/src/components/page-configs/ui-elements/va-date-picker/page-config.ts
- packages/docs/src/examples/va-sidebar-item/Active.vue
- packages/docs/src/examples/va-sidebar-item/Components.vue
- packages/docs/src/locales/en/en.json
- packages/docs/src/locales/ru/ru.json
- packages/docs/src/plugins/i18n.ts
- packages/docs/tsconfig.json
- packages/ui/jest.config.js
- packages/ui/src/components/va-date-picker/hooks/use-picker.ts
close #989
Rebased and resolved conflicts of [PR#1023](https://github.com/epicmaxco/vuestic-ui/pull/1023)
> Fix #989 Add event docks and fix hover event for DatePicker, Improve API table events handling

- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-select/VaSelectOptionList/VaSelectOptionList.vue
- packages/ui/src/composables/useSelectableList.ts
close #1057 
- **Search works with numbers inside Select component now.**
</details>
> Fix #1057: Search for numbers & minor refactor

- packages/docs/src/components/DocsNavigation.vue
- packages/docs/src/locales/en/en.json
- packages/docs/src/locales/ru/ru.json
> Add translation for docs nav buttons

- packages/ui/README.md
- packages/ui/package.json
> Update npmjs package description

- packages/ui/package.json
fix #1076
This PR should fix some minor npm issues.
> Move @types/wepback to dev dependecies.

- packages/docs/src/components/DocsExample.vue
- packages/docs/src/locales/en/en.json
- packages/docs/src/locales/ru/ru.json
> Add conditional label for showCode btn

- packages/docs/src/components/header/components/VersionDropdown.vue
> Show correct vuestic ui version on docs page

- packages/docs/src/components/page-configs/getting-started/configuration-guide/code-examples/icons.ts
- packages/docs/src/components/page-configs/services/colors-config/code-examples/icons-config.ts
- packages/docs/src/components/page-configs/services/global-config/code-examples/reactive-set.ts
- packages/docs/src/components/page-configs/services/global-config/code-examples/reactive-update.ts
- packages/docs/src/components/page-configs/services/global-config/code-examples/setup.ts
- packages/docs/src/components/page-configs/services/icons-config/code-examples/alias-example.ts
- packages/docs/src/components/page-configs/styles/css-variables/code-examples/general.ts
> Fix #1113 Fix docs pages (services, styles)

- packages/ui/src/components/va-collapse/VaCollapse.vue
> Fix default collapse mode-value. Fix collapse unordered animation.

- packages/ui/src/components/va-button/VaButton.vue
> Fixed height in rounded button.

- packages/ui/src/components/va-input/VaInput.vue
> Use cursor default in readonly input.

- packages/ui/src/main.ts
- packages/ui/src/vuestic-plugin/vuestic-plugin-without-components.ts
Simply forget about export `VuesticPluginsWithoutComponents`.
> Fix vuestic plugin without components.

- packages/ui/src/components/va-file-upload/VaFileUpload.vue
- packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue
- packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/_variables.scss
- packages/ui/src/components/va-file-upload/VaFileUploadList/VaFileUploadList.vue
- packages/ui/src/components/va-file-upload/VaFileUploadListItem/VaFileUploadListItem.vue
- packages/ui/src/components/va-file-upload/VaFileUploadListItem/_variables.scss
- packages/ui/src/components/va-file-upload/VaFileUploadUndo/VaFileUploadUndo.vue
- packages/ui/src/components/va-file-upload/VaFileUploadUndo/_variables.scss
At first, I thought we have a problem with VaFileUpload because of vue-class-component, so I rewrite VaFileUpload to composition API. But, later I realized that there is no problem at all. So in this PR I fixed broken keyboard navigation and some small bugs.
close #975
> Fix keyboard navigation for file upload.

- packages/docs/src/components/DocsApi/ApiDocs.vue
- packages/docs/src/components/page-configs/ui-elements/va-date-input/code/global-config.ts
- packages/docs/src/components/page-configs/ui-elements/va-date-input/page-config.ts
- packages/docs/src/components/page-configs/ui-elements/va-date-picker/page-config.ts
- packages/docs/src/examples/va-date-input/advancedFormatting.vue
- packages/docs/src/examples/va-date-input/input.vue
- packages/docs/src/examples/va-date-input/inputProps.vue
- packages/docs/src/examples/va-date-picker/Disabled.vue
- packages/docs/src/examples/va-date-picker/Readonly.vue
- packages/docs/src/locales/en/en.json
- packages/ui/src/components/va-date-input/VaDateInput.vue
- packages/ui/src/components/va-date-input/hooks/date-text-parser.ts
- packages/ui/src/components/va-date-picker/VaDatePicker.vue
- packages/ui/src/components/va-date-picker/components/VaDatePickerCell.vue
- packages/ui/src/components/va-date-picker/components/VaDayPicker/VaDayPicker.vue
- packages/ui/src/components/va-date-picker/components/VaMonthPicker/VaMonthPicker.vue
- packages/ui/src/components/va-date-picker/components/VaYearPicker/VaYearPicker.vue
- packages/ui/src/components/va-input/VaInput.vue
> Added date input parse docs.

- packages/ui/src/components/va-tabs/VaTab/VaTab.vue
- packages/ui/src/components/va-tabs/VaTabs.vue
> Remove console log for tabs

- packages/docs/src/assets/colors.scss
- packages/docs/src/components/landing/OpenSource.vue
- packages/docs/src/components/landing/Preview.vue
> Common primary color for landing page

- packages/docs/src/components/DocsNavigation.vue
> Fix docs-navigation links color on hover

- packages/docs/src/components/DocsNavigation.vue
> Fix icons for codesandbox

- packages/docs/src/components/landing/Header.vue
closes #747
also fixes star button alignment
Bug:
> Fix: landing page mobile menu

- packages/ui/src/components/va-button/VaButton.vue
> Pressed style for buttons on focus

- packages/ui/build/rollup/configs/cjs.js
- packages/ui/build/rollup/configs/esm.js
- packages/ui/build/rollup/configs/iife.js
- packages/ui/build/rollup/configs/styles.js
- packages/ui/build/rollup/plugins/rollup-transform-scss.js
- packages/ui/build/rollup/postcss-plugins/postcss-import.js
- packages/ui/package.json
- yarn.lock
closes #1185
closes #1184
Removed ~normalize.css from dist import, inject it's code instead.
> Resolve css from node_modules using postcss.

- packages/ui/src/components/va-checkbox/VaCheckbox.vue
close: #1217
Added stop propagation to the checkbox for click events
> Fix #1217: Can't select checkbox with space button

- packages/ui/src/components/va-pagination/VaPagination.vue
Directly changed the opacity for buttons with disabled state.
close: #1205
> Fix#1205 Directly changed the opacity for buttons with disabled state

- packages/docs/src/page-configs/ui-elements/backtop/examples/Default.vue
> Fix#1249: Fix target selector in VaBacktop doc example

- packages/docs/src/helpers/ReadHelper.ts
> Add path hack for windows to make it works #1279

- packages/docs/src/components/DocsExample.vue
- packages/docs/src/components/DocsNavigation.vue
> Fix path to git example

- packages/docs/src/components/DocsNavigation.vue
- packages/docs/src/helpers/DocsHelper.ts
- packages/docs/src/helpers/ReadHelper.ts
> Fix path to examples

- packages/docs/src/page-configs/ui-elements/input/examples/Textarea.vue
- packages/docs/src/page-configs/ui-elements/input/examples/Validate.vue
> Remove commented example

- packages/docs/src/page-configs/ui-elements/form/examples/Default.vue
- packages/docs/src/page-configs/ui-elements/form/examples/WithInputs.vue
- packages/docs/src/page-configs/ui-elements/input/examples/Default.vue
- packages/docs/src/page-configs/ui-elements/input/examples/Hint.vue
- packages/docs/src/page-configs/ui-elements/input/examples/Mask.vue
- packages/docs/src/page-configs/ui-elements/input/examples/Slots.vue
- packages/docs/src/page-configs/ui-elements/input/examples/Styles.vue
- packages/docs/src/page-configs/ui-elements/input/examples/Textarea.vue
- packages/docs/src/page-configs/ui-elements/input/examples/Validate.vue
- packages/docs/src/page-configs/ui-elements/select/page-config.ts
- packages/ui/src/components/va-form/VaForm.demo.vue
- packages/ui/src/components/va-input/VaInput.vue
- packages/ui/src/components/va-input/components/VaInputField.vue
- packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue
- packages/ui/src/components/va-select/VaSelect.demo.vue
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-time-input/VaTimeInput.vue
- packages/ui/src/composables/useFormComponent.ts
- packages/ui/src/composables/useValidation.ts
close: #1281
close: #1302
close: #1285
close: #1291
Changes:
> Fix#1281 #1302 #1291 Fix VaSelect validation

- packages/docs/src/page-configs/ui-elements/modal/examples/ModalSizing.vue
- packages/ui/src/components/va-modal/VaModal.vue
close: #1215
close: #1306
Changes:
> Fix#1215 #1306 Fix VaModal mobile fullscreen

- packages/docs/src/page-configs/ui-elements/form/examples/WithInputs.vue
- packages/docs/src/page-configs/ui-elements/sidebar-item/examples/Active.vue
- packages/docs/src/page-configs/ui-elements/sidebar-item/examples/Components.vue
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/composables/useValidation.ts
> Fix useValidation hook

- packages/docs/src/page-configs/ui-elements/select/examples/Decorators.vue
- packages/docs/src/page-configs/ui-elements/select/examples/Slots.vue
- packages/ui/src/components/va-dropdown/VaDropdown.vue
- packages/ui/src/components/va-input/VaInput.demo.vue
- packages/ui/src/components/va-input/components/VaInputField.vue
- packages/ui/src/components/va-select/VaSelect.demo.vue
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-time-input/VaTimeInput.vue
> Fix #1324 VaSelect dropdown position

- packages/docs/src/page-configs/ui-elements/button/examples/WithIcon.vue
- packages/ui/src/components/va-button/VaButton.demo.vue
- packages/ui/src/components/va-button/VaButton.vue
> Fix#1340 Fix VaButton icon color

- package.json
- packages/ui/README.md
package.json has an incorrect version
close #1189
> Fix #1189: Wrong version badge on npmjs

- packages/docs/src/components/page-configs/contribution/tree-shaking-requirements/page-config.ts
- packages/docs/src/components/sidebar/navigationRoutes.ts
- packages/docs/src/locales/en/en.json
- packages/docs/src/locales/es/es.json
- packages/docs/src/locales/ru/ru.json
- packages/docs/src/pages/contribution/tree-shaking-requirements.vue
- packages/ui/build/rollup/plugins/rollup-delete-junk.js
> Tree-shaking contribution docs

- packages/ui/src/components/va-list/VaListLabel.vue
closes #1335
Added the new property with the default value for the color. For now, I set the primary color as default.
> VaListLabel default color

- packages/ui/src/components/va-select/VaSelectOptionList/VaSelectOptionList.vue
> Fix #1395: VaSelect scroll performance

- packages/ui/src/components/va-input/components/VaInputField.vue
- packages/ui/src/styles/resources/_mixins.scss
#1229
Increased scroll width to prevent expand mark from shrinking.
Before:
After:
> Increase input scroll width

- packages/ui/src/components/va-option-list/VaOptionList.vue
- packages/ui/src/composables/useFormComponent.ts
- packages/ui/src/composables/useValidation.ts
> Rewrite VaOptionList.vue in composition api

- packages/ui/src/components/va-input/hooks/useCleave.ts
> Fix#1384 Fix VaInput editing behavior

- packages/ui/src/components/va-form/VaForm.vue
- packages/ui/src/components/va-form/consts.ts
> refactor: rewrite VaForm.vue with context api

- packages/docs/src/components/DocsApi/ApiDocs.vue
- packages/docs/src/components/DocsApi/ApiTableData.ts
- packages/docs/src/components/DocsContent.vue
- packages/docs/src/helpers/SortHelper.ts
- packages/docs/src/helpers/TranslationsHelper.ts
> Docs fix apply translations fn

- packages/ui/src/components/va-checkbox/VaCheckbox.vue
close #1435 
Fix issue when VACheckbox component not given id or name it will give id or name undefined
> FIx #1435 VaCheckbox Id is Undefined

- packages/ui/src/components/va-affix/VaAffix.vue
> refactor:  packages\ui\src\components\va-affix\VaAffix.vue

- packages/docs/tsconfig.json
- packages/ui/src/components/va-alert/VaAlert.vue
- packages/ui/src/components/va-alert/_variables.scss
- packages/ui/src/components/va-alert/useAlertStyles.ts
- packages/ui/src/composables/useColor.ts
- packages/ui/src/mixins/StatefulMixin/cStatefulMixin.ts
> refactor: rewrite VaAlert in composition api

- packages/ui/src/components/va-app-bar/VaAppBar.vue
- packages/ui/src/mixins/ScrollMixin/ScrollMixin.ts
> refactor: rewrite VaAppBar in composition api

- packages/ui/src/components/va-button-toggle/VaButtonToggle.vue
> refactor: buttonToggle to composition api

- packages/ui/src/components/va-button-group/VaButtonGroup.vue
> refactor: buttonGroup to composition api

- packages/ui/src/components/va-breadcrumbs/VaBreadcrumbs.vue
- packages/ui/src/composables/useColor.ts
> refactor: rewrite breadcrump to composition api

- packages/ui/src/components/va-badge/VaBadge.vue
- packages/ui/src/composables/useColor.ts
> refactor: rewrite badge in composition api

- packages/ui/src/components/va-backtop/VaBacktop.vue
> refactor: rewrite backtop to composition api

- packages/ui/src/components/va-card/VaCard.vue
- packages/ui/src/components/va-card/VaCardContent.vue
- packages/ui/src/components/va-card/VaCardTitle.vue
- packages/ui/src/composables/useAlign.ts
- packages/ui/src/composables/useColor.ts
- packages/ui/src/composables/useRouterLink.ts
> refactor: card and card items, improve router link typing

- packages/ui/src/components/va-checkbox/VaCheckbox.vue
Removed leaked useColorComputed.
> fix: remove computedColor

- packages/ui/src/components/va-affix/VaAffix.vue
> FIX#1521 VaAffix Element is null

- packages/ui/src/components/va-checkbox/useSelectable.ts
> Hotfix/falsy array value (#1555)

- packages/docs/src/page-configs/contribution/guide/code-examples/folder-structure.ts
How about to make component file structure more detailed?
http://localhost:8080/en/contribution/guide
> Added folders to component folder structure.

- packages/docs/src/locales/en/en.json
- packages/docs/src/page-configs/contribution/guide/code-examples/folder-structure.ts
- packages/docs/src/page-configs/contribution/guide/code-examples/npm-scripts.ts
- packages/docs/src/page-configs/services/icons-config/code-examples/alias-example.ts
- packages/docs/src/page-configs/services/icons-config/code-examples/font-example.ts
Add translations for code blocks in code-examples and examples.
fixes #1370
> Add translations for code blocks and examples.

- packages/ui/src/components/va-sidebar/VaSidebarItem/VaSidebarItem.vue
> Add `useHover` hook in `VaSidebarItem`

- packages/ui/src/components/va-date-input/VaDateInput.vue
> Fix: minor VaDateInput modelValue type error

- packages/ui/src/components/va-backtop/VaBacktop.demo.vue
- packages/ui/src/components/va-file-upload/VaFileUpload.demo.vue
- packages/ui/src/components/va-file-upload/VaFileUpload.vue
- packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue
- packages/ui/src/components/va-modal/VaModal.vue
> Fix warnings in demo examples

- packages/docs/src/page-configs/ui-elements/checkbox/examples/Coloring.vue
- packages/docs/src/page-configs/ui-elements/icon/examples/Color.vue
- packages/docs/src/page-configs/ui-elements/list/examples/Disabled.vue
- packages/ui/src/components/va-avatar/VaAvatar.vue
- packages/ui/src/components/va-backtop/VaBacktop.demo.vue
- packages/ui/src/components/va-backtop/VaBacktop.vue
- packages/ui/src/components/va-badge/VaBadge.vue
- packages/ui/src/components/va-button-toggle/VaButtonToggle.vue
- packages/ui/src/components/va-button/VaButton.vue
- packages/ui/src/components/va-card/VaCard.vue
- packages/ui/src/components/va-color-indicator/VaColorIndicator.vue
- packages/ui/src/components/va-config/VaConfig.demo.vue
- packages/ui/src/components/va-file-upload/VaFileUpload.demo.vue
- packages/ui/src/components/va-file-upload/VaFileUpload.vue
- packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue
- packages/ui/src/components/va-input/components/VaInputWrapper.vue
- packages/ui/src/components/va-modal/VaModal.vue
- packages/ui/src/components/va-sidebar/VaSidebarItem/VaSidebarItem.vue
- packages/ui/src/components/va-switch/VaSwitch.vue
- packages/ui/src/services/color-config/color-config.ts
- packages/ui/src/services/color-config/color-functions.ts
- packages/ui/src/services/color-config/color-theme-presets.ts
Merging develop -> nuxt-rework
> Merging develop -> nuxt-rework

- packages/ui/src/components/va-chip/VaChip.vue
VaChip moved to composition api.
> [#1641] VaChip moved on composition api

- packages/ui/src/components/va-slider/VaSlider.vue
- packages/ui/src/components/va-slider/_variables.scss
close: #1669 
Fixed pins position style. The initial problem is caused by some props combinations that  weren't processed.
> [#1669] fixed pins position style

- packages/ui/src/components/va-input/components/VaInputWrapper.vue
Same as https://github.com/epicmaxco/vuestic-ui/pull/1670
Already approved.
> vite css autoprefixer warn fix for merging in develop

- packages/ui/src/styles/global/_utility-global.scss
- packages/ui/src/styles/global/typography.scss
> [#1334] Remove junk css

- packages/ui/package.json
- packages/ui/src/components/va-scrollbar/VaScrollbar.vue
Deleted unnecessary dependencies, used in the only one outdated component, which is already seems to be non-working. But just in case - functionality was partially compensated.
P.S. Instead of `erd` i wanted to use `useResizeObserver` - in this case component should be partially moved to composition api, but was told not to waste time on this.
> Unnecessary dependencies removing

- packages/ui/src/components/va-date-picker/VaDatePicker.demo.vue
- packages/ui/src/components/va-date-picker/VaDatePicker.vue
- packages/ui/src/components/va-date-picker/_variables.scss
- packages/ui/src/components/va-date-picker/components/VaDatePickerCell.vue
- packages/ui/src/components/va-date-picker/components/VaDatePickerHeader/VaDatePickerHeader.vue
- packages/ui/src/components/va-date-picker/components/VaDayPicker/VaDayPicker.vue
- packages/ui/src/components/va-date-picker/components/VaMonthPicker/VaMonthPicker.vue
- packages/ui/src/components/va-date-picker/components/VaYearPicker/VaYearPicker.vue
These changes are a partial solution to issue #1342.
I do not close this issue, as the requirements for it will expand (new features will be added).
> Partial update of `VaDatePicker` visual style

- package.json
- packages/ui/package.json
Add exports to package.json so that user can use better imports.
Add exports so that user of vuestic-ui can make better imports.
fix #1503
Example of using under here.
<details>
```vue
import 'vuestic-ui'  // import ./packages/ui/dist/esm/main.js
require('vuestic-ui') // import ./packages/ui/dist/cjs/main.js
import 'vuestic-ui/ssr' // import ./packages/ui/dist/esm-ssr/main.js
import 'vuestic-ui/iife' // import ./packages/ui/dist/iife/vuestic-ui.js
import 'vuestic-ui/styles/...' // import ./packages/ui/dist/styles/...
import 'vuesttic-ui/types/..' // import ./packages/ui/dist/types/...
```
</details>
> Add exports to main package.json

- packages/ui/src/components/va-navbar/VaNavbar.vue
- packages/ui/src/components/va-navbar/VaNavbarItem/VaNavbarItem.vue
- packages/ui/src/components/va-navbar/_variables.scss
> [#1703] Fix `VaNavbar` text colors

- packages/docs/src/page-configs/services/colors-config/examples/change-colors.vue
- packages/docs/src/page-configs/services/colors-config/examples/css-variable.vue
> Fixed color config docs example.

- packages/docs/src/page-configs/ui-elements/slider/examples/Slots.vue
- packages/docs/src/page-configs/ui-elements/slider/examples/Vertical.vue
- packages/ui/src/components/va-slider/VaSlider.demo.vue
- packages/ui/src/components/va-slider/VaSlider.vue
- packages/ui/src/components/va-slider/_variables.scss
close #1691 
changes:
https://user-images.githubusercontent.com/55198465/165296425-33469a7e-fd82-40bd-8039-7fe52c95f876.mov
> [#1691] Fix `VaSlider` mobile behavior

- packages/docs/src/components/sidebar/navigationRoutes.ts
- packages/docs/src/locales/en/en.json
- packages/docs/src/locales/ru/ru.json
- packages/docs/src/page-configs/getting-started/nuxt/code-examples/index.ts
- packages/docs/src/page-configs/getting-started/nuxt/page-config.ts
- packages/docs/src/pages/getting-started/nuxt.vue
> Added nuxt integration page.

- packages/docs/src/helpers/DocsHelper.ts
- packages/docs/src/locales/en/en.json
- packages/docs/src/page-configs/contribution/documentation-page/page-config.ts
- packages/docs/src/page-configs/contribution/translation/page-config.ts
Updated some docs (basically one alert)
> feat: update translation docs approach

- packages/docs/package.json
- packages/docs/public/manifest.json
- packages/docs/src/main.ts
- packages/docs/src/registerServiceWorker.ts
- yarn.lock
close: #735 
PWA support added and tested.
> [#735] pwa support added

- packages/docs/src/locales/en/en.json
- packages/docs/src/locales/ru/ru.json
- packages/docs/src/page-configs/getting-started/nuxt/code-examples/index.ts
- packages/docs/src/page-configs/getting-started/nuxt/page-config.ts
Related to: https://github.com/epicmaxco/vuestic-ui/pull/1716
Nuxt 3 Vuestic UI integration docs update.
> nuxt 3 installation docs update

- packages/ui/build/rollup/config.js
- packages/ui/build/rollup/configs/esm.js
- packages/ui/build/rollup/configs/styles.js
Partially related to https://github.com/epicmaxco/vuestic-ui/issues/1646
> styles extraction from components, removed styles injection

- packages/ui/src/components/va-tabs/VaTab/VaTab.vue
- packages/ui/src/components/va-tabs/VaTabs.vue
- packages/ui/src/components/va-tabs/types/index.ts
- packages/ui/src/composables/useResizeObserver.ts
- yarn.lock
IDK why, but I have ts errors if `Ref<HTMLElement | null>`. Can't build anything.
> Fix ts errors in VaTabs.

- packages/ui/src/components/va-data-table/hooks/useAnimationName.ts
- packages/ui/src/components/va-date-picker/hooks/use-picker.ts
> fix argument name

- packages/ui/src/components/va-color-indicator/VaColorIndicator.vdemo.vue
- packages/ui/src/components/va-color-indicator/VaColorIndicator.vue
- packages/ui/src/components/va-color-input/VaColorInput.vue
- packages/ui/src/styles/global/_utility-global.scss
close: #1681 
Added HTML5 native color picker for color indicator. Updates to related components. Refactoring.
> [#1681] color picker added, refactoring

- packages/ui/src/components/va-modal/VaModal.demo.vue
- packages/ui/src/components/va-modal/VaModal.vue
close #1651
Feedback appreciated. This works but I wish I could figure out how to fix this in less costyl fashion.
> fix: dismiss only last modal on esc

- packages/ui/src/components/va-dropdown/VaDropdown.vue
- packages/ui/src/components/va-popover/VaPopover.vue
- packages/ui/src/composables/usePopover.ts
> [#1756] Fix `usePopover` `offset` prop

- packages/docs/src/locales/en/en.json
- packages/docs/src/page-configs/ui-elements/file-upload/api-options.ts
- packages/ui/src/components/va-file-upload/VaFileUpload.demo.vue
- packages/ui/src/components/va-file-upload/VaFileUpload.vue
Add `file-removed` event to VaFileUpload.
Fixes #1732
> Add `file-removed` event to VaFileUpload

- packages/ui/src/components/va-accordion/VaAccordion.vue
- packages/ui/src/components/va-accordion/hooks/useAccordion.ts
- packages/ui/src/components/va-collapse/VaCollapse.vue
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-select/VaSelectOptionList/VaSelectOptionList.vue
https://github.com/epicmaxco/vuestic-ui/pull/1778
https://github.com/epicmaxco/vuestic-ui/pull/1757
> PRs #1778 and #1757

- packages/nuxt/package.json
- packages/nuxt/src/module.ts
- packages/ui/package.json
- packages/ui/src/vue-book/book-main.ts
> Bump versions. Minor, removed unused imports.

- packages/ui/vue.config.js
> Update webpack config for vue-book dev server.

- packages/ui/src/components/va-sidebar/VaSidebarItem/VaSidebarItem.vue
> removed important

- packages/ui/src/components/va-carousel/VaCarousel.vue
close https://github.com/epicmaxco/vuestic-ui/issues/1822
Just added missing component. Must-have for `essential` build
> Register VaHover component in VaCarousel.

- packages/ui/src/components/va-alert/useAlertStyles.ts
- packages/ui/src/components/va-avatar/VaAvatar.vue
- packages/ui/src/components/va-badge/VaBadge.vue
- packages/ui/src/components/va-button-group/VaButtonGroup.vue
- packages/ui/src/components/va-button-toggle/VaButtonToggle.vue
- packages/ui/src/components/va-button/VaButton.vue
- packages/ui/src/components/va-card/VaCard.vue
- packages/ui/src/components/va-checkbox/VaCheckbox.vue
- packages/ui/src/components/va-chip/VaChip.vue
- packages/ui/src/components/va-collapse/VaCollapse.vue
- packages/ui/src/components/va-dropdown/components/VaDropdownContent/VaDropdownContent.vue
- packages/ui/src/components/va-modal/VaModal.vue
- packages/ui/src/components/va-navbar/VaNavbar.vue
- packages/ui/src/components/va-pagination/VaPagination.vue
- packages/ui/src/components/va-popover/VaPopover.vue
- packages/ui/src/components/va-sidebar/VaSidebar.vue
- packages/ui/src/components/va-toast/VaToast.vue
- packages/ui/src/composables/useTextColor.ts
closes #1814
Before:
After:
Here  is also some issue with sidebar, but I think we will fix it with https://github.com/epicmaxco/vuestic-ui/pull/1736 in different task.
> Fix#1814/outline button text color

- packages/vue-cli-plugin/README.md
- packages/vue-cli-plugin/generator/configs/default.js
- packages/vue-cli-plugin/generator/configs/treeshaking.js
- packages/vue-cli-plugin/generator/index.js
- packages/vue-cli-plugin/generator/utils/getPackageJSON.js
- packages/vue-cli-plugin/generator/utils/insertPlugin.js
- packages/vue-cli-plugin/generator/utils/resolveDependency.js
- packages/vue-cli-plugin/prompts.js
- Updated imports
- Removed CSS code split for now..
closes https://github.com/epicmaxco/vuestic-ui/issues/1797
> Update vue-cli-plugin to use vuestic-ui 1.4.0.

- packages/ui/src/components/va-sidebar/VaSidebarItem/VaSidebarItem.vue
- packages/ui/src/composables/useHover.ts
- packages/ui/src/composables/useRouterLink.ts
close #915
close https://github.com/epicmaxco/vuestic-ui/issues/1231
useRouterLink hook.
I also fixed useHover, it didn't want to work with useRouterLink 🤔
> Fix#915/use router link in sidebar item

- packages/ui/src/components/va-button-toggle/VaButtonToggle.vue
- packages/ui/src/components/va-button/VaButton.vue
- packages/ui/src/components/va-collapse/VaCollapse.vue
Related to:
#1374 
#1810 
`VaButtonToggle`, `VaButton`, `VaCollapse` accessibility & dom optimization checks.
> `VaButton`, `VaButtonToggle` & `VaCollapse` accessibility & dom optimization checks

- packages/ui/src/components/va-tabs/VaTabs.vue
> [#1885] Fix `VaTabs` `grow`

- packages/ui/src/components/va-app-bar/VaAppBar.vue
- packages/ui/src/components/va-app-bar/_variables.scss
Closes: #1883 
Minor bugfix of `VaAppBar` position.
> [#1883] `VaAppBar` position fix

- packages/nuxt/src/module.ts
> Nuxt module hotfix

- packages/ui/src/components/va-breadcrumbs/VaBreadcrumbsItem/VaBreadcrumbsItem.vue
- packages/ui/src/components/va-card/VaCard.vue
- packages/ui/src/composables/useRouterLink.ts
closes: #1760 
closes: #1871
`useRouterLink` refactoring, that solves problems with it is some cases.
P.S. `unknown` -> `any` related to #1878
> [#1760] [#1871] `useRouterLink` refactoring

- packages/docs/src/components/DocsContent.vue
> [#1837] Revert font size increasing

- packages/ui/src/components/va-slider/VaSlider.vue
- packages/ui/src/composables/useArrayRefs.ts
close #1912 
changes:
https://user-images.githubusercontent.com/55198465/172170998-fbdb9109-86e2-47f0-bbfc-370470eaca6e.mov
> [#1912] Fix `VaSlider` type `range`

- packages/ui/package.json
- packages/ui/src/vue-book/assets/icons/icons.scss
- yarn.lock
Closes https://github.com/epicmaxco/vuestic-ui/issues/1892.
> Fixed #1892.

- README.md
- packages/docs/src/helpers/CodeSandboxExample.ts
- packages/docs/src/helpers/CodeSandboxIconsHelper.ts
- packages/docs/src/locales/en/en.json
- packages/docs/src/locales/ru/ru.json
- packages/docs/src/page-configs/getting-started/configuration-guide/code-examples/colors.ts
- packages/docs/src/page-configs/getting-started/configuration-guide/code-examples/components.ts
- packages/docs/src/page-configs/getting-started/configuration-guide/code-examples/icons.ts
- packages/docs/src/page-configs/services/global-config/code-examples/setup.ts
- packages/docs/src/page-configs/styles/colors/code-examples/scheme.ts
- packages/docs/src/page-configs/ui-elements/date-input/code/global-config.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/1934
> Change all vuesticPlugin to createVuestic.

- README.md
> Minor. Fix Readme url.

- package.json
- packages/ui/build/bump-version.ts
- packages/ui/build/utils.ts
- packages/ui/package.json
- yarn.lock
So, you can't really test this script unless it goes to `develop` sadly, so ping me if you don't like something in the code.
Documentation for this comand I plan to do separately.
<details>
```vue
// Your code
```
</details>
> feat: automate version bump for generators and github templates

- packages/ui/src/components/va-dropdown/VaDropdown.vue
- packages/ui/src/components/va-time-input/VaTimeInput.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/1859
closes https://github.com/epicmaxco/vuestic-ui/issues/1972
> fix#1859 Show dropdown on manul input prop.

- packages/ui/src/components/va-input/components/VaInputWrapper.vue
> Fix import components in `va-input-wrapper`

- packages/ui/src/components/va-switch/VaSwitch.demo.vue
- packages/ui/src/components/va-switch/VaSwitch.vue
- packages/ui/src/styles/resources/_mixins.scss
Close: #1962 
Fixed line height, added new visual keyboard focus state, refactoring.
> [#1962] `VaSwitch` line height fix, keyboard focus state, minor refactoring

- package.json
- packages/ui/build/utils.ts
- packages/ui/scripts/release-script.md
- packages/ui/scripts/release-script.ts
- tsconfig.json
Improved release script in accordance to https://github.com/epicmaxco/vuestic-ui/pull/1986 
<details>
```vue
// Your code
```
</details>
> fix: small release script fixes

- packages/ui/src/components/va-dropdown/VaDropdown.vue
- packages/ui/src/components/va-select/VaSelect.vue
> Accessibility fixes

- packages/docs/src/components/header/Header.vue
- packages/docs/src/components/header/components/algolia-search/AlgoliaSearch.vue
- packages/docs/src/components/header/components/algolia-search/algolia-color-plugin.ts
- packages/docs/src/components/sidebar/Sidebar.vue
- packages/docs/src/main.ts
closes #1939
close https://github.com/epicmaxco/vuestic-ui/issues/726
Move Algolia search to the navbar, change header styles
Results:
> Move algolia search to the navbar

- packages/docs/src/page-configs/extensions/ag-grid/examples/Styles.vue
- packages/docs/src/page-configs/styles/typography/examples/textCode.vue
- packages/docs/src/page-configs/ui-elements/affix/examples/Bottom.vue
- packages/docs/src/page-configs/ui-elements/affix/examples/Top.vue
- packages/docs/src/page-configs/ui-elements/alert/examples/Border.vue
- packages/docs/src/page-configs/ui-elements/alert/examples/Center.vue
- packages/docs/src/page-configs/ui-elements/alert/examples/Closeable.vue
- packages/docs/src/page-configs/ui-elements/alert/examples/Color.vue
- packages/docs/src/page-configs/ui-elements/alert/examples/Default.vue
- packages/docs/src/page-configs/ui-elements/alert/examples/Dense.vue
- packages/docs/src/page-configs/ui-elements/alert/examples/Icon.vue
- packages/docs/src/page-configs/ui-elements/alert/examples/Styles.vue
- packages/docs/src/page-configs/ui-elements/alert/examples/Title.vue
- packages/docs/src/page-configs/ui-elements/backtop/examples/Default.vue
- packages/docs/src/page-configs/ui-elements/infinite-scroll/examples/Disabled.vue
- packages/ui/src/components/va-slider/VaSlider.vue
It is not necessary anymore to have root element in vue3, so we are removing those root div from examples.
Closes  #2080
</details>
> remove root div from examples

- packages/ui/src/components/va-sidebar/VaSidebarItem/VaSidebarItem.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/2078
> Fix sidebar text color.

- packages/ui/src/components/va-checkbox/VaCheckbox.demo.vue
- packages/ui/src/components/va-checkbox/VaCheckbox.vue
- packages/ui/src/components/va-checkbox/_variables.scss
- packages/ui/src/components/va-input/_variables.scss
- packages/ui/src/components/va-input/components/VaMessageList/VaMessageList.vue
- packages/ui/src/components/va-input/components/VaMessageListWrapper.vue
- packages/ui/src/composables/useSelectable.ts
Related: #715
Minor `VaCheckbox` visual updates.
> [#715] `VaCheckbox` visual updates

- packages/docs/src/page-configs/getting-started/ssr-guide/code-examples/css-variables.ts
- packages/docs/src/page-configs/getting-started/ssr-guide/code-examples/vite-ssr-plugin.ts
- packages/docs/src/page-configs/getting-started/ssr-guide/code-examples/vitesse.ts
- packages/nuxt/src/runtime/plugin.ts
- packages/ui/src/services/color-config/plugin/create-color-config-plugin.ts
Closes #2135 
<details>
```vue
// Your code
```
</details>
> [#2135] Docs: typo `renderCSSVarialbes` fixed

- packages/ui/src/components/AccessibilityGuide.md
Close: #2122 
Accessibility guide in .md, base checklist & reference in notion (https://www.notion.so/epicmax/Vuestic-ui-10e698cacd5846688647e1d8482277c9#f10c56baffde4b62826cb90aad02fe5a).
> [#2122] Accessibility guide

- packages/ui/src/components/va-slider/VaSlider.vue
> fix:types build hotfix

- packages/ui/src/components/va-pagination/VaPagination.vue
Check before closing is needed: https://github.com/epicmaxco/vuestic-ui/issues/2152
Mb fixes problem with codesandbox. 
- no problems were found with `cjs` build,
- strange places in `iife` minimized build with `Pf` were removed (looked like a reassigment of the undefined var).
> [#2152] `iife` build codesandbox fix

- packages/ui/src/components/va-collapse/VaCollapse.demo.vue
- packages/ui/src/components/va-collapse/VaCollapse.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/2158
> fix(collapse): collapse content must change height if it content is height is changed

- packages/docs/src/components/DocsApi/ApiDocs.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/2094
> docs: removed version and required column.

- packages/ui/src/components/va-input/VaInput.vue
- packages/ui/src/components/va-select/VaSelect.vue
> Fix `VaInput` and `VaSelect` wrapper class

- packages/ui/src/components/va-list/VaListItemLabel.vue
- packages/ui/src/components/va-list/_variables.scss
> Fix `VaListItemLabel` `line-height`

- packages/docs/src/page-configs/introduction/roadmap/components/roadmap.vue
Close #2183 
Added two media query in the roadmap.vue file to fix the roadmap in mobile view
> fixed roadmap responsiveness on mobile

- packages/ui/src/composables/useFixedBar.ts
> fix: build type hotfix

- packages/ui/package.json
> fix: styles  named export in package.json

- packages/ui/src/composables/useRouterLink.ts
Same as https://github.com/epicmaxco/vuestic-ui/pull/2264 but for `develop` branch.
> `VaButton` prop `to` in Nuxt 3 hotfix

- packages/ui/src/components/va-split/VaSplit.vue
Close: #2203 
unhovered opacity 0.7 -> hovered opacity 1
> [2203] `VaSplit` default dragger hover visual state

- packages/ui/src/components/va-select/VaSelect.vue
Close: #2286
Change value getter methods for the modelValue.
> Change value getter methods for the modelValue getter

- packages/docs/src/locales/en/en.json
- packages/docs/src/page-configs/getting-started/nuxt/page-config.ts
- packages/nuxt/src/composables/use-css.ts
- packages/nuxt/src/module.ts
- packages/nuxt/src/types.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/2314
> Fix#2314/fonts nuxt module option

- packages/ui/src/styles/typography/_mixins.scss
Minor refix for https://github.com/epicmaxco/vuestic-ui/issues/2282 (for develop branch, already solved for 1.5.0 in https://github.com/epicmaxco/vuestic-ui/pull/2332)
> [#2282] docs github link refix

- packages/ui/src/services/component-config/component-config.ts
- packages/ui/src/services/config-transport/createProxyComponent.ts
> (1.5.0) Fix: stack overflow issue in Nuxt 3

- packages/nuxt/src/module.ts
In https://github.com/nuxt/framework/pull/7116 we made a breaking change allowing modules to use RC constraints. This PR fixes this.
> fix: update nuxt version constraint

- packages/docs/src/layouts/default.vue
- packages/docs/src/pages/index.vue
- packages/ui/src/styles/typography/_mixins.scss
Typography, docs & landing page links keyboard-only focus style.
> Typography links focus style update

- packages/docs/src/locales/en/en.json
- packages/docs/src/page-configs/ui-elements/rating/examples/ItemSlot.vue
- packages/docs/src/page-configs/ui-elements/rating/page-config.ts
- packages/ui/src/components/va-rating/VaRating.vue
- packages/ui/src/components/va-rating/components/VaRatingItem/VaRatingItem.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/2350
> feat: rating item slot

- packages/ui/src/components/va-radio/VaRadio.vue
Closes: #716 
`VaRadioButton` visual focus state update.
> [#716] `VaRadioButton` visual focus state update

- packages/ui/src/composables/tests/useStateful.spec.ts
Minor update I'd hope @aluarius to take a look and maybe discuss a bit.
> feat: minor stateful test update

- packages/ui/src/composables/useSelectable.ts
There is no type for the array-value property in the checkbox component
> Add missing types for array-value prop

- packages/docs/src/components/header/Header.vue
- packages/docs/src/page-configs/ui-elements/button-toggle/examples/ToggleColor.vue
- packages/ui/src/components/va-button-toggle/VaButtonToggle.vue
- packages/ui/src/components/va-button/VaButton.demo.vue
- packages/ui/src/components/va-button/VaButton.vue
- packages/ui/src/composables/useHoverStyle.ts
- packages/ui/src/composables/usePressedStyle.ts
- packages/ui/src/services/color-config/color-functions.ts
> `VaButton` fixes

- packages/ui/src/composables/useSelectable.ts
> fix isSelectable after change null to undefined

- packages/ui/src/components/va-time-picker/components/VaTimePickerColumn/VaTimePickerColumn.vue
A little fix for the time picker.
> fix: support mac trackpad scroll event listener

- packages/docs/src/components/landing/LandingCustomize.vue
- packages/docs/src/components/sidebar/SidebarLink.vue
- packages/docs/src/config/theme-config.ts
- packages/ui/src/components/va-sidebar/VaSidebarItem/VaSidebarItem.vue
- packages/ui/src/composables/useColors.ts
- packages/ui/src/composables/useElementBackground/useElementBackground.ts
- packages/ui/src/services/color-config/color-functions.ts
- packages/ui/src/services/color-config/color-theme-presets.ts
- packages/ui/src/services/color-config/tests/color-config.spec.ts
- packages/ui/src/styles/global/color-themes.demo.vue
- packages/ui/src/utils/tests/test-utils.spec.ts
Fixed tests, did a little refactoring.
> Fix tests and refactor colors case notation

- packages/docs/src/page-configs/ui-elements/data-table/examples/Filtering.vue
> [#2316] Update `VaDataTable` filtering example in docs with debounced input

- packages/ui/build/build.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/2433
> fix: make build script to wait until css is built

- packages/ui/src/components/va-date-picker/components/VaDatePickerCell.vue
Removed the @include focus-outline; line to remove outline when the element is focused
> [#2420] Removed outline on datepicker

- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/composables/useSelectableList.ts
- packages/ui/src/services/utils.ts
Closes: #2395 
Closes: #2362 
Closes: #2136
Separate bugfixes related to the `VaSelect` component.
> [#2395] [#2362] [#2136] `VaSelect` bugfix, minor refactoring

- packages/ui/src/components/va-modal/VaModal.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/2371
> fix: modal overflow on mobile

- packages/ui/src/components/va-alert/VaAlert.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/2478
> chore: rollback missing css

- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/composables/tests/useMaxSelections.spec.ts
- packages/ui/src/composables/useMaxSelections.ts
Now ValueComputed returns SelectOption and emits valueBy correctly.
> fix: multiple select options value-by

- packages/docs/src/page-configs/ui-elements/split/examples/CustomGrabber.vue
- packages/docs/src/page-configs/ui-elements/split/examples/CustomLimits.vue
- packages/docs/src/page-configs/ui-elements/split/examples/Default.vue
- packages/docs/src/page-configs/ui-elements/split/examples/Disabled.vue
- packages/docs/src/page-configs/ui-elements/split/examples/Maximization.vue
- packages/docs/src/page-configs/ui-elements/split/examples/Nested.vue
- packages/docs/src/page-configs/ui-elements/split/examples/Snapping.vue
- packages/docs/src/page-configs/ui-elements/split/examples/Vertical.vue
- packages/ui/src/components/va-split/VaSplit.vue
- packages/ui/src/components/va-split/_variables.scss
closes https://github.com/epicmaxco/vuestic-ui/issues/2475
> Fix#2475/split scrollbars

- packages/docs/src/page-configs/ui-elements/app-bar/examples/Color.vue
- packages/docs/src/page-configs/ui-elements/hover/examples/Disabled.vue
- packages/ui/src/components/va-button-dropdown/VaButtonDropdown.vue
- packages/ui/src/components/va-dropdown/VaDropdown.vue
- packages/ui/src/components/va-hover/VaHover.vue
- packages/ui/src/composables/useStateful.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/2494
closes https://github.com/epicmaxco/vuestic-ui/issues/2489
> fix: dropdown and hover stateful prop

- packages/docs/src/page-configs/styles/typography/examples/text-helpers/alignment.vue
- packages/docs/src/page-configs/styles/typography/examples/text-helpers/transform.vue
- packages/docs/src/page-configs/styles/typography/examples/text-helpers/truncate.vue
- packages/docs/src/page-configs/styles/typography/examples/text/secondary.vue
- packages/docs/src/page-configs/styles/typography/examples/textCode.vue
- packages/ui/src/styles/typography/_mixins.scss
- packages/ui/src/styles/typography/_module.scss
- packages/ui/src/styles/typography/typography.scss
closes https://github.com/epicmaxco/vuestic-ui/issues/2480
> fix: typography double dash

- packages/docs/src/page-configs/ui-elements/chip/examples/Closeable.vue
- packages/docs/src/page-configs/ui-elements/chip/examples/Link.vue
- packages/docs/src/page-configs/ui-elements/chip/examples/Shadow.vue
> Fixed chip demo.

- packages/ui/src/components/va-color-input/VaColorInput.vue
> Changed position of color circle in VaColorInput.

- packages/docs/src/page-configs/ui-elements/checkbox/examples/Array.vue
- packages/docs/src/page-configs/ui-elements/checkbox/examples/Coloring.vue
- packages/docs/src/page-configs/ui-elements/checkbox/examples/Label.vue
- packages/docs/src/page-configs/ui-elements/list/examples/Clickable.vue
- packages/docs/src/page-configs/ui-elements/list/examples/Default.vue
- packages/docs/src/page-configs/ui-elements/list/examples/Disabled.vue
- packages/docs/src/page-configs/ui-elements/list/examples/Fit.vue
- packages/docs/src/page-configs/ui-elements/list/examples/Lines.vue
- packages/docs/src/page-configs/ui-elements/select/examples/AllowCreate.vue
- packages/docs/src/page-configs/ui-elements/select/examples/Decorators.vue
- packages/docs/src/page-configs/ui-elements/select/examples/ObjectOptions.vue
- packages/docs/src/page-configs/ui-elements/select/examples/Searchable.vue
- packages/docs/src/page-configs/ui-elements/select/examples/Slots.vue
- packages/docs/src/page-configs/ui-elements/select/examples/State.vue
- packages/docs/src/page-configs/ui-elements/select/examples/Styles.vue
- packages/docs/src/page-configs/ui-elements/select/examples/TrackBy.vue
- packages/docs/src/page-configs/ui-elements/select/examples/Variations.vue
- packages/ui/src/components/va-list/VaList.vue
- packages/ui/src/components/va-list/VaListItem.vue
- packages/ui/src/components/va-list/_variables.scss
> Fixed demos spacing.

- packages/ui/src/components/va-pagination/VaPagination.vue
- packages/ui/src/components/va-pagination/_variables.scss
> make VaPagination bg color transparent as in VaInput

- packages/docs/src/components/DocsExample.vue
- packages/ui/src/components/va-card/_variables.scss
closes https://github.com/epicmaxco/vuestic-ui/issues/2570
> fix(#2570): card styles miss match with docs

- packages/docs/src/locales/en/en.json
- packages/docs/src/page-configs/ui-elements/modal/examples/BeforeClose.vue
- packages/docs/src/page-configs/ui-elements/modal/page-config.ts
- packages/ui/src/components/va-modal/VaModal.demo.vue
- packages/ui/src/components/va-modal/VaModal.vue
> feat(Modal): add beforeClose prop

- packages/ui/src/components/va-tabs/VaTabs.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/2586
> fix: empty tabsList error

- packages/ui/src/components/va-input/hooks/useCleave.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/2568
> fix(#2568): input mask wrong formatted value

- packages/docs/src/locales/en/en.json
- packages/ui/src/components/va-tabs/VaTabs.vue
- [x ] New feature (non-breaking change which adds functionality)
> [va-tabs]: add hide-pagination prop

- packages/docs/src/components/DocsContent.vue
- packages/docs/src/helpers/DocsHelper.ts
- packages/docs/src/locales/en/en.json
- packages/docs/src/locales/ru/ru.json
- packages/docs/src/page-configs/getting-started/installation/page-config.ts
- packages/docs/src/page-configs/ui-elements/dropdown/page-config.ts
- packages/ui/src/components/va-collapse/VaCollapse.vue
- packages/ui/src/components/va-collapse/_variables.scss
- packages/ui/src/components/va-input/components/VaInputWrapper/VaInputWrapper.vue
Close #2579
Not finished, needs russian, but you can take a look at current things:
> feat: migration guide

- packages/ui/src/components/va-dropdown/VaDropdown.demo.vue
- packages/ui/src/components/va-dropdown/VaDropdown.vue
- packages/ui/src/composables/useDropdown.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/2604
> fix(#2604): now auto-placement prop count cross line

- package.json
- packages/nuxt/nuxt.shim.d.ts
- packages/nuxt/playground/nuxt.config.ts
- packages/nuxt/src/composables/use-composables.ts
- packages/nuxt/src/composables/use-plugin.ts
- packages/nuxt/src/config/components.ts
- packages/nuxt/src/config/composables.ts
- packages/nuxt/src/runtime/composables.ts
- packages/nuxt/src/runtime/plugin.ts
- packages/nuxt/src/types.ts
- packages/nuxt/src/utils/resolve.ts
- yarn.lock
- Fix dev:prepare build
- Added missing components
- Added missing composables
> Fix/nuxt 1.5.0

- packages/ui/src/vuestic-plugin/global-components.ts
instad -> instead
<details>
```vue
// Your code
```
</details>
> Fix typo in global-components.ts

- packages/docs/src/components/ThemeSwitch.vue
- packages/docs/src/components/header/Header.vue
- packages/docs/src/components/header/components/ColorDropdown.vue
- packages/docs/src/components/header/components/LanguageDropdown.vue
- packages/docs/src/components/landing/LandingHeader.vue
- packages/docs/src/layouts/landing.vue
- packages/ui/src/components/va-button-dropdown/VaButtonDropdown.vue
- packages/ui/src/vuestic-plugin/types/index.ts
- packages/ui/src/vuestic-plugin/utils/use-plugin.ts
> docs color dropdown

- packages/docs/src/components/ThemeSwitch.vue
- packages/docs/src/components/header/Header.vue
- packages/docs/src/components/header/components/ColorDropdown.vue
- packages/docs/src/components/header/components/LanguageDropdown.vue
- packages/docs/src/components/landing/LandingHeader.vue
- packages/docs/src/layouts/landing.vue
- packages/ui/src/components/va-button-dropdown/VaButtonDropdown.vue
- packages/ui/src/components/va-color-indicator/VaColorIndicator.vue
- packages/ui/src/components/va-switch/VaSwitch.vue
- packages/ui/src/vuestic-plugin/types/index.ts
- packages/ui/src/vuestic-plugin/utils/use-plugin.ts
> Refactor color dropdown

- packages/ui/src/components/va-counter/VaCounter.vue
Close #2607
Close #2569
- Fixed min value behavior when it set to `0`.
- Refactoring.
> Counter fixes

- packages/ui/src/components/va-date-picker/components/VaDatePickerCell.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/2664
> fix: date picker selected cell color

- packages/ui/src/components/va-data-table/hooks/useSortable.ts
Close #2497
- Refactored and fixed with it sorting issue on nuxt when `ssr` is truthy.
> Fix sorting in the VaDataTable

- packages/nuxt/src/runtime/plugin.ts
- Fixed breakpoint service usage in nuxt apps.
> feat: sync plugins

- packages/nuxt/src/composables/use-plugin.ts
- packages/nuxt/src/runtime/plugin.ts
- packages/ui/src/services/color/plugin/create-color-config-plugin.ts
Solves https://discord.com/channels/457593300799717377/1044901048315289690/1045356747554037840
> Fix: Nuxt 3 colors issue fix

- packages/docs/src/page-configs/getting-started/configuration-guide/code-examples/colors.ts
Closes: #2751 
Minor docs example fix.
> Minor configuration example fix

- packages/ui/src/composables/useColors.ts
Closes: #2753 
Colors config now understands kebab-case variables names.
> feat: now color config understands color names in kebab case

- packages/docs/src/locales/index.ts
- packages/docs/src/locales/zh-CN/zh-CN.json
<details>
```vue
// Your code
```
</details>
> docs(translate): add zh-CN part

- packages/docs/src/components/DocsNavigation.vue
> [#2564] docs codesandbox icon fix

- packages/docs/src/page-configs/ui-elements/dropdown/examples/PlacementAndOffset.vue
- packages/ui/src/components/va-button-dropdown/VaButtonDropdown.vue
- packages/ui/src/components/va-dropdown/VaDropdown.vue
- packages/ui/src/components/va-navbar/VaNavbar.vue
- packages/ui/src/composables/useDeprecated.ts
- packages/ui/src/composables/useDropdown.ts
- packages/ui/src/composables/usePlacementAliases.ts
> `usePlacementAliases` refactor and `useDeprecated` bugfix

- packages/ui/src/services/vue-plugin/components.ts
Close #2676
- Add component export.
> fix: add va-toast export

- packages/ui/src/composables/useElementBackground/utils.ts
Close #2805
- Replaced selector error with warning message.
> fix: replace error with warning

- packages/ui/src/components/va-sidebar/VaSidebar.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/2637
> fix(#2637): register va-config in va-sidebar

- packages/ui/src/components/va-button/hooks/useButtonTextColor.ts
- packages/ui/src/services/color/utils.ts
- Fix button colors on safari <16 versions.
> fix: button state colors for safari browsers

- packages/sandbox/configs/vite/common-config.ts
> fix: develop docs build hotfix

- packages/docs/src/locales/en/en.json
- packages/docs/src/page-configs/services/colors-config/page-config.ts
Adding document for `colors` of `useColors`.
> docs: adding document for `colors` of `useColors`

- packages/nuxt/src/runtime/plugin.ts
- packages/ui/src/services/color/config/default.ts
closes #2821
close https://github.com/epicmaxco/vuestic-ui/issues/2824
Need to double-check if issue is gone with this PR.
> Fix#2821/nuxt color presets fix

- packages/ui/src/components/va-slider/VaSlider.vue
> Types build hotfix

- packages/docs/package.json
- packages/sandbox/.gitignore
- packages/sandbox/analysis/bundle-sizes.js
- packages/sandbox/scripts/bundle-analysis.ts
> Docs ci mb fix

- packages/ui/src/components/va-input/components/VaInputWrapper/VaInputWrapper.vue
Close #2901 
Reordered background color variable assignment.
> fix: input wrapper background color

- packages/ui/src/components/va-virtual-scroller/VaVirtualScroller.demo.vue
- packages/ui/src/components/va-virtual-scroller/VaVirtualScroller.vue
- packages/ui/src/components/va-virtual-scroller/useVirtualScrollerSizes.ts
> Low elements amount bugfix and auto wrapper size mode for `VaVirtualScroller`

- packages/ui/src/composables/useValidation.ts
- packages/ui/src/main.ts
This PR aims to expose the ValidationRule\<T> type to the consumer of the library to be able to use it in advanced scenarios.
> feature: expose ValidationRule<T> type to consumer

- packages/docs/src/components/landing/LandingAdmin.vue
- packages/docs/src/components/landing/LandingCustomize.vue
- packages/docs/src/components/landing/LandingFooter.vue
- packages/docs/src/components/landing/LandingPreview.vue
- packages/docs/src/components/landing/LandingStarsButton.vue
Close #2937
Close #2938 
Close #2939 
Landing page fixes
<details>
<summary>Screenshots</summary>
</details>
> fix: button presets and indents

- packages/ui/src/components/va-rating/components/VaRatingItem/VaRatingItem.vue
> fix: click on rating item emitted two events

- packages/ui/src/components/va-modal/VaModal.vue
- packages/ui/src/components/va-modal/_variables.scss
Hotfix vuestic-nuxt-tailwind bug (https://github.com/epicmaxco/vuestic-ui/issues/2960).
> [#2960] hotfix nuxt-vuestic-tailwind bug

- packages/docs/src/locales/zh-cn/zh-cn.json
- packages/ui/src/components/va-badge/hooks/useFloatingPositionStyles.ts
- packages/ui/src/composables/useDropdown.ts
- packages/ui/src/composables/usePlacementAliases.ts
> [#2896] `va-badge` placement reactivity fix

- packages/docs/locales/en.json
- packages/docs/locales/ru.json
- packages/docs/page-config/getting-started/tree-shaking/code/css-code-split.ts
- packages/docs/page-config/styles/grid/examples/AlignContent.vue
- packages/docs/page-config/styles/grid/examples/AlignDefault.vue
- packages/docs/page-config/styles/grid/examples/AlignJustify.vue
- packages/docs/page-config/styles/grid/examples/AlignSelf.vue
- packages/docs/page-config/styles/grid/examples/Breakpoints.vue
- packages/docs/page-config/styles/grid/examples/Default.vue
- packages/docs/page-config/styles/grid/examples/Gutters.vue
- packages/docs/page-config/styles/grid/examples/Offsets.vue
- packages/docs/page-config/styles/grid/index.ts
- packages/docs/page-config/styles/reset/index.ts
- packages/docs/page-config/styles/smart-helpers/examples/Gutters.vue
- packages/docs/page-config/styles/smart-helpers/examples/Spacing.vue
- packages/docs/pages/index.vue
- packages/ui/src/components/va-select/components/VaSelectContent/VaSelectContent.vue
- packages/ui/src/styles/grid/_grid-global-styles.scss
- packages/ui/src/styles/grid/_grid-spacing.scss
- packages/ui/src/styles/smart-helpers/smart-helpers.scss
Closes: #2991 
Closes: #2988
</details>
> [#2991] [#2988] docs and grid updates

- packages/ui/src/components/va-breadcrumbs/VaBreadcrumbs.vue
- packages/ui/src/utils/resolveSlot.ts
> [#2977] `VaBreadcrumbs` mb error fix & resolve slot helper

- packages/docs/components/HeaderBanner.client.vue
- packages/docs/components/landing/Header.vue
- packages/docs/components/layout/Header.vue
Adaptation of https://github.com/epicmaxco/vuestic-ui/pull/2921
> feat(docs): banner

- packages/docs/config/vuestic-config.ts
- packages/docs/locales/en.json
- packages/docs/page-config/getting-started/nuxt/code/vuestic-config.ts
- packages/docs/page-config/getting-started/nuxt/index.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/2955
closes https://github.com/epicmaxco/vuestic-ui/issues/2822
closes https://github.com/epicmaxco/vuestic-ui/issues/2881
> docs: nuxt vuestic.config.ts

- packages/ui/src/components/va-input/VaInput.demo.vue
- packages/ui/src/components/va-input/VaInput.vue
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/composables/useFocus.ts
- packages/ui/src/composables/useFocusDeep.ts
- packages/ui/src/utils/focus.ts
- packages/ui/src/utils/unwrapEl.ts
> fix(#2894): dispatch focus event when focus

- .circleci/config.yml
> minor: commit of nothing

- packages/docs/.gitignore
- packages/docs/package.json
- packages/docs/page-config/getting-started/tree-shaking/index.ts
- packages/docs/page-config/getting-started/tree-shaking/tree-shaking.md
- packages/sandbox/scripts/bundle-analysis.ts
> fix: docs tree shaking statistics restored

- packages/docs/components/landing/Footer.vue
> fix: landing social icons

- packages/docs/components/landing/Header.vue
- packages/docs/public/landing/cross.svg
- packages/docs/public/landing/hamburger.svg
> fix: landing mobile menu

- packages/ui/src/services/vue-plugin/types/components.ts
> fix(#3067): rollback component type declaration

- packages/create-vuestic/package.json
- packages/create-vuestic/src/index.ts
- packages/create-vuestic/src/steps/2.1.addAgGrid.ts
- packages/create-vuestic/src/versions.ts
- packages/nuxt/package.json
Update create-vuestic to 0.0.4
- Fix for Vuestic Admin template
> Fix#3026/create-vuestic-fix-deps-install

- packages/ui/src/components/va-image/VaImage.demo.vue
- packages/ui/src/components/va-image/VaImage.vue
- packages/ui/src/components/va-image/_variables.scss
- packages/ui/src/components/va-viewer/VaViewer.vue
Have found a few problems while checking Vuestic Admin.
- CSS variables renamed, added missing `:root`.
- Content width minor fix.
> fix: minor va-image fix

- packages/deploy/release-script/release-script.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/3062
> chore: added todo list after release

- packages/docs/locales/en.json
- packages/docs/locales/ru.json
- packages/docs/page-config/ui-elements/avatar/examples/Fallback.vue
- packages/docs/page-config/ui-elements/avatar/examples/GravatarIntegration.vue
- packages/docs/page-config/ui-elements/avatar/index.ts
Close #2663 
- Gravatar usage examples.
- Default fallback with global config.
> feat: add gravatar usage example

- packages/docs/page-config/ui-elements/dropdown/examples/PlacementAndOffset.vue
- packages/docs/page-config/ui-elements/dropdown/examples/PreventOverflow.vue
- packages/ui/src/components/va-dropdown/VaDropdown.demo.vue
- packages/ui/src/components/va-dropdown/VaDropdown.vue
- packages/ui/src/components/va-dropdown/VaDropdownRender.demo.vue
- packages/ui/src/components/va-dropdown/hooks/useAnchorSelector.ts
- packages/ui/src/composables/useDomRect.ts
- packages/ui/src/composables/useDropdown.ts
- packages/ui/src/utils/headless.ts
Closes: #3049 #3047 
[x] `va-dropdown` reimplementation to render function.
> [#3049] [#3047] va-dropdown rewritten to render reimplementation

- packages/ui/src/components/va-stepper/VaStepper.vue
- packages/ui/src/components/va-stepper/VaStepperStepButton.vue
- packages/ui/src/services/i18n/config/default.ts
closes #3028
Inspired by https://www.w3.org/WAI/ARIA/apg/patterns/tabs/
> feat: stepper accessebility

- packages/docs/components/AlgoliaSearch.vue
<details>
```vue
// Your code
```
</details>
> feat: update algolia api key

- packages/docs/components/AlgoliaSearch.vue
<details>
```vue
// Your code
```
</details>
> refactor: restore previous api key

- packages/ui/src/components/va-option-list/VaOptionList.vue
- packages/ui/src/components/va-pagination/VaPagination.vue
- packages/ui/src/composables/useBem.ts
- packages/ui/src/composables/useColors.ts
- packages/ui/src/composables/useDeprecated.ts
- packages/ui/src/composables/useElementBackground/utils.ts
- packages/ui/src/utils/console.ts
- packages/ui/src/utils/env.ts
Close #3151
- Renamed dev environment variable.
> refactor: rename dev env variable

- packages/ui/src/components/va-data-table/VaDataTable.demo.vue
- packages/ui/src/components/va-data-table/VaDataTable.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/3163
> fix(#3163): added header and footer slots to data-table

- packages/ui/src/components/va-time-picker/components/VaTimePickerColumn/VaTimePickerColumn.vue
> fix(#3086): time picker nan value in chrome

- packages/docs/page-config/introduction/browser-support/components/browsers-table.vue
> Restore not supported browsers icons

- packages/ui/src/components/va-switch/VaSwitch.demo.vue
- packages/ui/src/components/va-switch/VaSwitch.vue
- packages/ui/src/components/va-switch/_variables.scss
closes #3087
List of fixes:
- correct outline for keyboard focus
- fixed loader position
- fixed border and label color styles for failed rules
- fixed collision of checkmark (see comments section)
> fix: switch component issues

- packages/ui/src/components/va-inner-loading/VaInnerLoading.vue
> feat: va-inner-loading accessibility improvements

- packages/ui/src/components/va-divider/VaDivider.vue
> fix: add aria-hidden attr for VaDivider

- packages/ag-grid-theme/src/styles/_variables.scss
- packages/ui/src/components/va-checkbox/_variables.scss
- packages/ui/src/styles/global/css-variables.scss
> fix: checkbox styles

- packages/docs/components/layout/header/ThemeSwitch.vue
it's not a new feature anymore
> fix: remove new badge from theme switch component

- packages/ui/src/composables/useRouterLink.ts
> fix: hide router props for not link tags

- packages/docs/locales/en.json
- packages/docs/locales/ru.json
- packages/docs/page-config/ui-elements/divider/index.ts
- packages/docs/page-config/ui-elements/slider/index.ts
- packages/docs/page-config/ui-elements/stepper/index.ts
closes #3111
closes #3227
closes #3228
closes #3229
Covered components:
> feat: docs accessibility guide for VaSlider, VaDivider, VaStepper

- packages/docs/locales/en.json
- packages/docs/locales/ru.json
- packages/docs/page-config/ui-elements/inner-loading/index.ts
> feat: add docs a11y page for `VaInnerLoading`

- packages/docs/locales/en.json
- packages/docs/locales/ru.json
- packages/docs/page-config/ui-elements/icon/index.ts
> feat: add a11y docs section for VaIcon

- packages/docs/locales/en.json
- packages/docs/locales/ru.json
- packages/docs/page-config/ui-elements/spacer/index.ts
> feat: add a11y docs section for VaSpacer

- packages/ui/src/components/va-slider/VaSlider.demo.vue
- packages/ui/src/components/va-slider/VaSlider.vue
> [#2907] `VaSlider` `stateful` prop

- packages/ui/src/components/va-date-input/VaDateInput.vue
closes #3233
Click on input wrapper will show dropdown
> fix: dropdown appearing on VaDateInput click

- packages/ui/src/components/va-input/VaInput.vue
- packages/ui/src/components/va-radio/VaRadio.vue
- packages/ui/src/components/va-rating/components/VaRatingItem/VaRatingItem.vue
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-select/components/VaSelectContent/VaSelectContent.vue
- packages/ui/src/components/va-select/components/VaSelectOptionList/VaSelectOptionList.vue
> fix: add string type for tabindex prop

- packages/docs/page-config/ui-elements/switch/examples/Color.vue
- packages/docs/page-config/ui-elements/switch/examples/Error.vue
- packages/docs/page-config/ui-elements/switch/examples/Indeterminate.vue
- packages/docs/page-config/ui-elements/switch/examples/InnerLabel.vue
- packages/docs/page-config/ui-elements/switch/examples/Label.vue
- packages/docs/page-config/ui-elements/switch/examples/Size.vue
- packages/docs/page-config/ui-elements/switch/examples/State.vue
- packages/ui/src/components/va-switch/VaSwitch.vue
close #2864
<details>
<summary>screenshot</summary>
</details>
> [#2864] `VaSwitch` height

- packages/ui/src/components/va-select/components/VaSelectOptionList/VaSelectOptionList.vue
Close #3315
- Allow to select options with custom markup.
> fix: allow to select options with custom markup

- packages/ui/src/components/va-modal/plugin/index.ts
- Add confirm function to vaModalPlugin
- Add confirm function to vaModalPlugin, closes #3299
> Fix(modal plugin): Add confirm to vaModalPlugin

- packages/docs/components/layout/Header.vue
close #3350 
<details>
<summary>screenshots</summary>
</details>
> [#3350] Add `pointer-events-none` for header search-input

- packages/docs/components/HeaderBanner.client.vue
<details>
<summary>screenshot</summary>
</details>
> Remove Vue.js partner from header banner

- packages/docs/components/landing/Partners.vue
> Remove Vue.js partner logo

- README.md
> Remove partner logo from README

- packages/docs/pages/index.vue
> Remove landing banner

- packages/docs/modules/markdown/runtime/plugins/external-links.ts
closes [#3419](https://github.com/epicmaxco/vuestic-ui/issues/3419)
> fix(docs): markdown external link break lists

- packages/docs/page-config/ui-elements/select/examples/IconOptions.vue
- packages/docs/page-config/ui-elements/select/index.ts
- packages/docs/translations/en.json
Description
I added documentation for the ability to specify an icon per option in the vst-select component.
<details>
```vue
<template>
<div style="max-width: 300px;">
<va-select
v-model="value"
:options="options"
:option-component="iconOption"
/>
</div>
</template>
<script>
import VaSelect from 'vuestic-ui/src/components/va-select/VaSelect.vue'
export default {
components: {
VaSelect
},
data() {
return {
value: "",
options: [
{ code: 'sv', name: 'Svenska', icon: 'flag-se' },
{ code: 'en', name: 'English', icon: 'flag-gb' },
{ code: 'fr', name: 'Français', icon: 'flag-fr' },
{ code: 'de', name: 'Deutsch', icon: 'flag-de' }
],
};
},
computed: {
iconOption() {
return {
props: ['option'],
template: `<div><i class="icon-${this.option.icon}"></i> {{option.name}}</div>`
}
}
}
};
</script> …
```
> Add documentation for option icons feature in select component close #3408

- packages/docs/page-config/ui-elements/button-group/examples/Colors.vue
- packages/docs/page-config/ui-elements/button-group/examples/Gradient.vue
- packages/docs/page-config/ui-elements/button-group/examples/Icons.vue
- packages/docs/page-config/ui-elements/button-group/examples/Sizes.vue
- packages/docs/page-config/ui-elements/button-group/examples/Styles.vue
- packages/ui/src/components/va-button-group/VaButtonGroup.vue
close #3209
<details>
</details>
> [#3209] `VaButtonGroup` gradient

- packages/ui/src/components/va-counter/VaCounter.vue
<details>
```vue
// Your code
```
</details>
> [#3397] Added the margin to the counter

- packages/ui/src/composables/useBreakpoint.ts
- packages/ui/src/services/breakpoint/types.ts
> [#3443] Breakpoint service hydration errors

- packages/docs/page-config/ui-elements/accordion/index.ts
- packages/docs/page-config/ui-elements/collapse/index.ts
- packages/ui/src/components/va-collapse/VaCollapse.vue
Improve and document the accessibility of `VaAccordion` and `VaCollapse`
Fixes #3288 and #3282.
> Accessibility improvements on `VaAccordion` and `VaCollapse`

- packages/docs/components/AlgoliaSearch.vue
Fix docs algolia container z-index
> fix: update algolia search container z-index

- packages/docs/modules/page-config/blocks/api/component-parser/index.ts
- packages/docs/modules/page-config/blocks/api/index.vue
- packages/docs/modules/page-config/blocks/api/types.ts
> fix(docs): manual types merging

- packages/docs/middleware/redirects.global.ts
Add redirects from language pages
Remove language code from the url
> feat(docs): add redirect from language pages

- packages/docs/components/ComponentPlayground.vue
- packages/docs/components/layout/header/ColorDropdown.vue
- packages/docs/page-config/ui-elements/app-bar/examples/Color.vue
- packages/docs/page-config/ui-elements/dropdown/examples/PreventOverflow.vue
- packages/ui/src/components/va-dropdown/VaDropdown.vue
- packages/ui/src/components/va-dropdown/hooks/useDropdown.ts
- packages/ui/src/components/va-select/tests/VaSelect.spec.ts
Remove VaDropdown  prevent-overflow property
> feat(ui): dropdown remove prevent overflow property

- packages/docs/page-config/introduction/roadmap/images/1.8/index.ts
- packages/docs/page-config/introduction/roadmap/images/1.8/menu.vue
- packages/docs/page-config/introduction/roadmap/images/1.8/pageLayout.vue
- packages/docs/page-config/introduction/roadmap/images/index.ts
- packages/docs/page-config/introduction/roadmap/index.ts
- packages/docs/page-config/introduction/roadmap/types.ts
There are PRs for Layout, ColorPicker and Menu component in progress, so I include them in roadmap.
> docs: update 1.8 roadmap

- packages/ui/src/components/va-counter/VaCounter.vue
> Fix#3564/counter buttons

- packages/ui/src/components/va-toast/VaToast.demo.vue
- packages/ui/src/components/va-toast/hooks/useToast.ts
- packages/ui/src/composables/useAppContext.ts
- packages/ui/src/services/current-app.ts
- packages/ui/src/utils/console.ts
- packages/ui/src/vue-book/book-main.ts
closes [#3494](https://github.com/epicmaxco/vuestic-ui/issues/3494)
closes https://github.com/epicmaxco/vuestic-ui/issues/3571
> fix(toast): introduce single app mode

- packages/ui/src/components/va-stepper/VaStepper.demo.vue
- packages/ui/src/components/va-stepper/VaStepper.vue
- packages/ui/src/components/va-stepper/VaStepperControls.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/3568
closes https://github.com/epicmaxco/vuestic-ui/issues/3560
> Fix#3568/provide more things to stepper slot

- packages/ui/src/composables/useFocus.ts
> fix(#3580): set isFocused to false if element haven't rendered yet

- packages/ui/src/components/va-dropdown/hooks/useAnchorSelector.ts
- packages/ui/src/components/va-select/components/VaSelectOptionList/VaSelectOptionList.vue
- packages/ui/src/composables/useClickOutside.ts
- packages/ui/src/composables/useElementRef.ts
- packages/ui/src/composables/useFocusOutside.ts
- packages/ui/src/composables/useHTMLElement.ts
- packages/ui/src/composables/useHTMLElementSelector.ts
- packages/ui/src/composables/useIntersectionObserver.ts
- packages/ui/src/utils/unwrapEl.ts
> fix(#3587): correctly unwrap element from template refs

- packages/ui/src/components/va-radio/VaRadio.demo.vue
- packages/ui/src/components/va-radio/VaRadio.vue
- packages/ui/src/composables/useSelectable.ts
fix https://github.com/epicmaxco/vuestic-ui/issues/3582#issuecomment-1627693752
> fix(#3582): move back label prop

- packages/docs/modules/page-config/blocks/api/component-parser/index.ts
> docs: fix prop types

- packages/docs/page-config/services/icons-config/code/setup-example.ts
> fix#3409/outdated syntax

- packages/docs/components/landing/SocialsLinks.vue
> fix#3655/twitter link

- packages/docs/page-config/ui-elements/sidebar/examples/Position.vue
closes #3652 
Moved both components into a div container and applied mt-2 space-x-2 to it
> fix#3652/docs design 

- packages/docs/page-config/ui-elements/backtop/index.ts
- packages/ui/src/components/va-backtop/VaBacktop.vue
Improve accessibility for va-backtop component.
Fixes #3267.
> Improve accessibility for va-backtop

- packages/ui/src/components/va-dropdown/hooks/useDropdown.ts
- packages/ui/src/utils/focus.ts
> fix(dropdown): jump to top of page on focus

- packages/ui/src/components/va-accordion/VaAccordion.stories.ts
> fixed accordion stories

- packages/docs/pages/index.vue
> remove vue-forge banner

- packages/ui/src/components/va-accordion/VaAccordion.stories.ts
- packages/ui/src/components/va-accordion/VaAccordion.vue
- packages/ui/src/components/va-accordion/hooks/useAccordion.ts
- packages/ui/src/components/va-collapse/VaCollapse.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/3687
> Fix#3687/stateful-accordion

- packages/ui/src/components/va-data-table/VaDataTable.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/3680
> fix(#3680): data table hover in safari

- packages/docs/page-config/ui-elements/dropdown/api-description.ts
- packages/docs/page-config/ui-elements/dropdown/api-options.ts
- packages/ui/src/components/va-dropdown/VaDropdown.demo.vue
- packages/ui/src/components/va-dropdown/VaDropdown.vue
- packages/ui/src/components/va-dropdown/hooks/useDropdown.ts
> va-dropdown fixes

- packages/ui/src/components/va-alert/VaAlert.vue
- packages/ui/src/components/va-input/VaInput.demo.vue
- packages/ui/src/components/va-input/VaInput.vue
- packages/ui/src/utils/combine-functions.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/3726
> fix(va-input): proxy input event

- packages/docs/page-config/styles/colors/components/Components.vue
- packages/docs/page-config/styles/colors/components/ThemeDesigner.vue
- packages/docs/page-config/styles/colors/components/theme-designer/ColorInput.vue
- packages/docs/page-config/styles/colors/index.ts
- packages/ui/src/components/va-color-input/VaColorInput.vue
- packages/ui/src/composables/useColors.ts
- packages/ui/src/services/current-app.ts
Fix va-config colors prop
Fix ColorInput perfomance
Add simple theme designer
> feat(theme-designer): init color preview

- packages/ui/package.json
fix(dependency): added @faker-js/faker to devDependency.
fix: #3752
> fix: devDependency

- packages/docs/page-config/ui-elements/modal/api-description.ts
- packages/ui/src/components/va-modal/VaModal.demo.vue
- packages/ui/src/components/va-modal/VaModal.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/3690
> feat(modal): before-ok and before-cancel methods

- packages/docs/page-config/ui-elements/icon/index.ts
- packages/docs/page-config/ui-elements/input/index.ts
> docs Icon: fixed link to icon-config; docs Input: add hint to examle 'mask'

- packages/ui/src/components/va-checkbox/VaCheckbox.vue
- packages/ui/src/components/va-checkbox/_variables.scss
Have Added pointer cursor to the Checkbox label
> Feat: Added pointer cursor to label in Checkbox #3785

- packages/ui/src/components/va-carousel/VaCarousel.vue
- packages/ui/src/components/va-carousel/hooks/useCarousel.ts
- packages/ui/src/components/va-form/VaForm.stories.ts
- packages/ui/src/components/va-input-wrapper/VaInputWrapper.demo.vue
- packages/ui/src/composables/useForm/useFormParent.ts
fix #3794
fix #3790 (we don't care about `today` if date is not in the same month 🫣)
* fixed carousel bugs
* fixed form bugs (except for autofocus, too complex, moved to #3799)
> fix chromatic tests

- packages/docs/components/layout/Sidebar.vue
- packages/docs/page-config/ui-elements/collapse/examples/Color.vue
- packages/docs/page-config/ui-elements/collapse/examples/Default.vue
- packages/docs/page-config/ui-elements/collapse/examples/Icon.vue
- packages/docs/page-config/ui-elements/collapse/examples/Slots.vue
- packages/docs/page-config/ui-elements/sidebar-item/examples/Components.vue
- packages/docs/page-config/ui-elements/sidebar/examples/Default.vue
- packages/docs/page-config/ui-elements/sidebar/examples/Programmatically.vue
- packages/ui/src/components/va-accordion/VaAccordion.vue
- packages/ui/src/components/va-checkbox/VaCheckbox.vue
- packages/ui/src/components/va-collapse/VaCollapse.demo.vue
- packages/ui/src/components/va-collapse/VaCollapse.vue
- packages/ui/src/composables/useBem.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/3822
closes https://github.com/epicmaxco/vuestic-ui/issues/3807
<details>
```vue
// Your code
```
</details>
> fix(collapse): add border to collapse

- packages/ui/src/components/va-data-table/VaDataTable.stories.ts
- packages/ui/src/components/va-data-table/VaDataTable.vue
- packages/ui/src/components/va-data-table/fabrics.ts
- packages/ui/src/components/va-data-table/hooks/useFilterable.ts
- packages/ui/src/components/va-data-table/index.ts
- packages/ui/src/components/va-data-table/types.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/3838
closes https://github.com/epicmaxco/vuestic-ui/issues/3837
> fix(#3837): emit filter event immidiate if needed

- packages/docs/page-config/ui-elements/app-bar/examples/Shadow.vue
- packages/docs/page-config/ui-elements/list/examples/Clickable.vue
- packages/docs/page-config/ui-elements/list/examples/Default.vue
- packages/docs/page-config/ui-elements/list/examples/Disabled.vue
- packages/docs/page-config/ui-elements/list/examples/Fit.vue
- packages/docs/page-config/ui-elements/list/examples/Lines.vue
- packages/docs/page-config/ui-elements/scroll-container/examples/Default.vue
- packages/docs/page-config/ui-elements/tabs/examples/Content.vue
fixes use of non existent color `background-tertiary` https://github.com/epicmaxco/vuestic-ui/issues/3845
> fix: remove background-tertiary from docs

- packages/docs/page-config/ui-elements/slider/examples/Pins.vue
> fix(#3818): Decrease pins in VaSlider docs example

- packages/ui/src/components/va-input-wrapper/VaInputWrapper.vue
- packages/ui/src/components/va-select/VaSelect.vue
Closes #3867
There was also another issue: auto-complete opened and closed at the same time.
> fix(#3867): select click event

- packages/ui/src/components/va-badge/VaBadge.vue
- packages/ui/src/components/va-card/VaCard.vue
- packages/ui/src/components/va-checkbox/VaCheckbox.vue
- packages/ui/src/components/va-collapse/VaCollapse.vue
- packages/ui/src/components/va-navbar/VaNavbar.vue
- packages/ui/src/components/va-popover/VaPopover.vue
- packages/ui/src/components/va-progress-bar/VaProgressBar.vue
- packages/ui/src/components/va-sidebar/VaSidebar.vue
- packages/ui/src/components/va-toast/VaToast.stories.ts
- packages/ui/src/components/va-toast/VaToast.vue
- packages/ui/src/components/va-toast/_variables.scss
> fix(#3866): toast text color

- packages/ui/src/components/va-tree-view/hooks/useTreeView.ts
> fix getFilteredNodes method

- packages/docs/page-config/contribution/guide/index.ts
Minor updated docs for contributors
> chore(docs): update contribution guide

- packages/ui/src/components/va-button/VaButton.stories.ts
- packages/ui/src/components/va-button/VaButton.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/2704
> fix(#2704): icon shift

- packages/ui/src/components/va-data-table/VaDataTable.stories.ts
- packages/ui/src/components/va-data-table/VaDataTable.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/3831
> fix(#3831): data table jump on pagination

- packages/ui/src/components/va-input/VaInput.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/3840
> fix(#3840): emit focus event once in va-input-wrapper

- packages/ui/src/components/va-switch/VaSwitch.stories.ts
- packages/ui/src/components/va-switch/VaSwitch.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/2074
> fix(#2074): VaSwitch made input clickable and fire change event

- packages/ui/src/components/va-modal/VaModal.vue
Keeping size constant for short message.
Fixing #3961
> Make VaModal size prop work

- packages/docs/page-config/services/global-config/code/setup.ts
Fix wrong indention in setup code snippet.
> fix: wrong indention in setup code snippet

- packages/docs/page-config/ui-elements/slider/examples/Slots.vue
Set limit on the VaInput in order to limit sliding circle inside slider.
Fixes #3977
> Fix VaInput range in slots example of slider docs

- packages/ui/build/plugins/append-component-css.ts
> fix(build): append css to non-script components

- packages/docs/components/landing/Features.vue
- packages/docs/page-config/introduction/roadmap/images/1.6/autoComplete.vue
- packages/docs/page-config/ui-elements/list/examples/Clickable.vue
- packages/docs/page-config/ui-elements/list/examples/Default.vue
- packages/docs/page-config/ui-elements/list/examples/Disabled.vue
- packages/docs/page-config/ui-elements/list/examples/Fit.vue
- packages/docs/page-config/ui-elements/list/examples/Lines.vue
- packages/ui/src/components/va-content/VaContent.demo.vue
- packages/ui/src/components/va-list/VaList.demo.vue
> add alts to images

- packages/ui/src/components/va-file-upload/VaFileUpload.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/3993
> fix(#3993): do not update filelist on mount

- packages/docs/modules/page-config/blocks/change-log/index.vue
Add copyable change log anchor.
Fix #3918.
> add change log anchor

- packages/ui/src/components/va-checkbox/VaCheckbox.stories.ts
- packages/ui/src/components/va-checkbox/VaCheckbox.vue
Added the missing margins between checkboxes in array-value story.
Added an array-value-vertical story, with the margins.
closes https://github.com/epicmaxco/vuestic-ui/issues/4001
> fix(#4001): checkbox margins in array-value mode

- packages/ui/src/components/va-checkbox/VaCheckbox.vue
- packages/ui/src/components/va-checkbox/_variables.scss
Moved css padding values from js to custom css variables.
Added a switch case for better readability
closes #4011  
<details>
```vue
// Your code
```
</details>
> fix(#4011): checkbox Moved padding values from js to custom css variables

- packages/ui/src/components/va-time-input/VaTimeInput.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/4034
> fix(#4034): focus stuck on time input component

- packages/ui/src/components/va-button/VaButton.vue
> fix: button icon size

- packages/ui/package.json
- packages/ui/src/components/va-button/tests/VaButton.spec.ts
- packages/ui/src/components/va-select/tests/VaSelect.spec.ts
- packages/ui/src/composables/tests/useEmitProxy.spec.ts
- packages/ui/src/composables/tests/useStateful.spec.ts
- packages/ui/tsconfig.json
- yarn.lock
Setup proper type checking for tests and eliminated preexisting TS errors in similar way to https://github.com/epicmaxco/vuestic-ui/pull/4043
- Removed exclusion of *.spec.ts files in tsconfig.json (but kept them excluded in build config tsconfig.build.json)
- Updated @vue/test-utils package version as previously installed version produced TS error in `mount` function
> Tests typechecking fix

- packages/ui/src/components/va-alert/VaAlert.vue
- packages/ui/src/components/va-button/VaButton.vue
- packages/ui/src/components/va-card/components/va-card-block/VaCardBlock.vue
- packages/ui/src/components/va-carousel/VaCarousel.vue
- packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue
- packages/ui/src/components/va-file-upload/VaFileUploadSingleItem/VaFileUploadSingleItem.vue
- packages/ui/src/components/va-form/VaForm.vue
- packages/ui/src/components/va-input-wrapper/VaInputWrapper.vue
- packages/ui/src/components/va-list/VaList.vue
- packages/ui/src/components/va-list/VaListItem.vue
- packages/ui/src/components/va-list/VaListItemLabel.vue
- packages/ui/src/components/va-list/VaListItemSection.vue
- packages/ui/src/components/va-list/VaListSeparator.vue
- packages/ui/src/components/va-menu-list/components/VaMenuItem.vue
- packages/ui/src/components/va-modal/VaModal.vue
- packages/ui/src/components/va-rating/VaRating.vue
- packages/ui/src/components/va-rating/components/VaRatingItemNumberButton.vue
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-select/components/VaSelectOptionList/VaSelectOptionList.vue
Make setup function return { [variableName] }
I need this for script to convert everything into setup script.
> fix: normalize return in setup function

- packages/docs/page-config/ui-elements/input/examples/StrictVModel.vue
- packages/docs/page-config/ui-elements/input/index.ts
- packages/ui/src/components/va-input/VaInput.stories.ts
- packages/ui/src/components/va-input/VaInput.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/3996
> fix(input): restore cursor on input value update

- packages/ui/src/components/va-input-wrapper/VaInputWrapper.vue
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-select/components/VaSelectOptionList/VaSelectOptionList.vue
> Fix#4102/autocomplete-allow-space

- packages/ui/src/components/va-dropdown/VaDropdown.stories.ts
- packages/ui/src/components/va-dropdown/VaDropdown.vue
- packages/ui/src/components/va-input-wrapper/VaInputWrapper.vue
- packages/ui/src/components/va-modal/VaModal.vue
- packages/ui/src/components/va-modal/_variables.scss
- packages/ui/src/composables/useZIndex.ts
- packages/ui/src/services/cache/plugin/index.ts
- packages/ui/src/utils/uuid.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/3994
> feat: init zIndex composable

- packages/ui/src/components/va-alert/VaAlert.stories.ts
- packages/ui/src/components/va-dropdown/VaDropdown.stories.ts
- packages/ui/src/components/va-menu-list/VaMenuList.vue
- packages/ui/src/components/va-menu-list/components/VaMenuGroup.vue
Mostly bug fixes and story test correction
> chore: fix chromatic failed tests

- packages/ui/src/components/va-inner-loading/VaInnerLoading.vue
> fix: InnerLoading(#4100) spinner spin

- packages/tailwind/helpers/helpers.ts
While syncing tailwind config to vuestic config some property names may contain dashes. These must be quoted as well, for instance the color 'background-primary'.
<details>
```vue
// Your code
```
</details>
> fix: also quote props containing dashes

- packages/docs/page-config/ui-elements/badge/examples/Placement.vue
- packages/docs/page-config/ui-elements/badge/examples/WithOtherComponents.vue
- packages/docs/page-config/ui-elements/button/examples/Tag.vue
- packages/docs/page-config/ui-elements/button/examples/WithIcon.vue
- packages/docs/page-config/ui-elements/carousel/examples/Ratio.vue
- packages/docs/page-config/ui-elements/carousel/examples/Slots.vue
Copy of https://github.com/epicmaxco/vuestic-ui/pull/3863 with conflicts resolved and without Grid removal
> docs: minor miscellaneous improvements 

- packages/ui/src/components/va-accordion/VaAccordion.stories.ts
- packages/ui/src/components/va-accordion/VaAccordion.vue
- packages/ui/src/components/va-accordion/hooks/useAccordion.ts
- packages/ui/src/components/va-collapse/VaCollapse.vue
- packages/ui/src/composables/useStateful.ts
Accordion bug fix + useStateful improved DX
> fix(#4114): allow to set collapse v-model in accordion

- packages/ui/src/components/va-counter/VaCounter.vue
- packages/ui/src/services/icon/presets/vuestic-aliases.ts
close https://github.com/epicmaxco/vuestic-ui/issues/4058
> add aliases for add/remove icons

- packages/ui/src/components/va-date-input/VaDateInput.vue
- packages/ui/src/components/va-dropdown/CHANGELOG.md
- packages/ui/src/components/va-dropdown/VaDropdown.stories.ts
- packages/ui/src/components/va-dropdown/VaDropdown.vue
- packages/ui/src/components/va-dropdown/hooks/useCursorAnchor.ts
- packages/ui/src/components/va-dropdown/hooks/useDropdownNavigation.ts
- packages/ui/src/components/va-popover/VaPopover.vue
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-time-input/VaTimeInput.vue
- packages/ui/src/components/va-time-picker/components/VaTimePickerColumn/VaTimePickerColumn.vue
- packages/ui/src/utils/unwrapEl.ts
> fix(#4119): improve dropdown keyboard navigation

- packages/ui/src/components/va-switch/VaSwitch.vue
> fix(VaSwitch): fix click nesting issues(#4187)

- packages/docs/page-config/services/icons-config/components/playground.vue
> docs: fix padding in icons config playground(#3846)

- packages/docs/page-config/ui-elements/select/examples/ObjectOptions.vue
- packages/docs/page-config/ui-elements/select/index.ts
closed #4067 
Recommend using track-by to prevent object reference issues when using objects as options.
> docs(VaSelect): improvement objects as options description(#4067)

- packages/ui/src/components/va-data-table/VaDataTable.vue
- packages/ui/src/components/va-data-table/_variables.scss
> fix(VaDataTable): fix double border from head(#4147)

- packages/docs/page-config/ui-elements/stepper/examples/WithForm.vue
- packages/docs/page-config/ui-elements/stepper/index.ts
- packages/ui/src/components/va-form/VaForm.vue
- packages/ui/src/components/va-stepper/VaStepper.stories.ts
- packages/ui/src/components/va-stepper/VaStepper.vue
- packages/ui/src/components/va-stepper/VaStepperControls.vue
- packages/ui/src/components/va-stepper/VaStepperStepButton.vue
- packages/ui/src/components/va-stepper/types.ts
- packages/ui/src/composables/useForm/formContext.ts
- packages/ui/src/composables/useForm/types.ts
- packages/ui/src/composables/useForm/useForm.ts
- packages/ui/src/composables/useForm/useFormParent.ts
- packages/ui/src/composables/useHTMLElementSelector.ts
- packages/ui/src/composables/useTemplateRef.ts
- packages/ui/src/composables/useValidation.ts
- packages/ui/src/services/config-transport/createProxyComponent.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/4235
> feat: handle async rules in stepper

- packages/ui/.storybook/types.ts
- packages/ui/src/components/va-checkbox/VaCheckbox.stories.ts
- packages/ui/src/components/va-checkbox/VaCheckbox.vue
- packages/ui/src/components/va-counter/VaCounter.stories.ts
- packages/ui/src/components/va-counter/VaCounter.vue
- packages/ui/src/components/va-date-input/VaDateInput.stories.ts
- packages/ui/src/components/va-date-input/VaDateInput.vue
- packages/ui/src/components/va-input/VaInput.stories.ts
- packages/ui/src/components/va-select/VaSelect.stories.ts
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-switch/VaSwitch.stories.ts
- packages/ui/src/components/va-switch/VaSwitch.vue
- packages/ui/src/components/va-textarea/VaTextarea.stories.ts
- packages/ui/src/components/va-textarea/VaTextarea.vue
- packages/ui/src/components/va-time-input/VaTimeInput.stories.ts
- packages/ui/src/components/va-time-input/VaTimeInput.vue
- packages/ui/src/composables/useSelectable.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/4221
> fix: touched and dirty states for all components

- packages/ui/src/components/va-breadcrumbs/VaBreadcrumbsItem/VaBreadcrumbsItem.vue
##Issue
https://github.com/epicmaxco/vuestic-ui/issues/3910
<details>
```vue
<style lang="scss">
@import "variables";
.va-breadcrumb-item {
display: var(--va-breadcrumb-item-display);
color: var(--va-breadcrumb-item-color);
&--link {
color: inherit;
cursor: pointer;
&:hover {
opacity: var(--va-breadcrumb-item-hover-opacity);
}
&:focus {
text-decoration: var(--va-breadcrumb-item-focus-text-decoration);
}
}
}
</style>
```
</details>
> bug: added cursor pointer for breadcrumb links

- packages/ui/src/components/va-input-wrapper/VaInputWrapper.vue
closed #3950 
We should reduce the input height when using the inner label mode
> fix(VaInputWrapper): fix inner label height(#3950)

- packages/docs/page-config/ui-elements/avatar/examples/Accessibility.vue
- packages/docs/page-config/ui-elements/avatar/examples/Color.vue
- packages/docs/page-config/ui-elements/avatar/index.ts
https://github.com/epicmaxco/vuestic-ui/issues/3812
<details>
```vue
// Your code
```
</details>
> feat: fixed spacing between avatars in the docs

- packages/docs/page-config/getting-started/installation/code/tailwind-css-import.ts
- packages/docs/page-config/getting-started/installation/index.ts
- packages/docs/page-config/styles/tailwind/index.ts
> Update tailwind docs (#4238)

- packages/ui/src/services/component-config/types.ts
> Allow style and class properties (#4247)

- packages/ui/src/components/va-data-table/VaDataTable.vue
> Wrap expanded row in tr (#4241)

- packages/docs/components/landing/forms/RequestAuditForm.vue
- packages/docs/components/landing/modals/RequestAuditModal.vue
> Code audit edits

- packages/docs/components/HeaderBanner.vue
- packages/docs/components/Recaptcha.vue
- packages/docs/components/landing/forms/RequestAuditForm.vue
- packages/docs/composables/useRecaptcha.ts
> Fixed code audit modal on mobile

- packages/ui/src/components/va-slider/VaSlider.vue
Closes #4291 
Fixes out of range values handling by visually moving thumbs and filling slider to the limits
> fix(slider): out of range values handling

- packages/ui/src/components/va-date-picker/VaDatePicker.demo.vue
- packages/ui/src/components/va-date-picker/VaDatePicker.vue
- packages/ui/src/components/va-date-picker/components/VaDatePickerCell.vue
> fix(VaDatePicker): Fixed today outline in readonly

- packages/docs/components/landing/forms/RequestAuditForm.vue
> Pass name to code audit popup

- packages/ui/src/composables/useInputMask/cursor.spec.ts
- packages/ui/src/composables/useInputMask/cursor.ts
- packages/ui/src/composables/useInputMask/mask.ts
- packages/ui/src/composables/useInputMask/masks/date.ts
- packages/ui/src/composables/useInputMask/masks/numeral.ts
- packages/ui/src/composables/useInputMask/masks/parser.ts
- packages/ui/src/composables/useInputMask/masks/regex.ts
- packages/ui/src/composables/useInputMask/useInputMask.stories.ts
- packages/ui/src/composables/useInputMask/useInputMask.ts
Tests for cursor, better date mask format
> fix(masks): correctly handle months (feb)

- packages/ui/src/components/va-color-input/VaColorInput.vdemo.vue
- packages/ui/src/components/va-color-input/VaColorInput.vue
Fixes: #4341
<details>
```vue
// Your code
&__input {
margin-bottom: 0;
min-width: 5.6rem;
width: 100%;
&__pointer {
cursor: pointer;
}
}
```
</details>
> fix(VaColorInput): added full length color input

- packages/docs/modules/repl/index.ts
- packages/docs/modules/vuestic.ts
- packages/nuxt/src/module.ts
With Nuxt 4 on the horizon, this updates the module compatibility definition to allow it to be installed on Nuxt v4. (Otherwise Nuxt will indicate the module might not be compatible.)
When Nuxt v4 comes out then you might decide or need to make breaking changes in this module and release a new major, but hopefully the migration should be smoother. 🙏 
👉 You can follow this and other changes in https://github.com/nuxt/nuxt/issues/27613 - please feel free to provide feedback as well!
<details>
```vue
// Your code
```
</details>
> chore: indicate compatibility with new v4 major

- packages/docs/components/landing/Footer.vue
- packages/docs/components/landing/Header.vue
- packages/docs/page-config/navigationRoutes.ts
- packages/docs/page-config/support/consulting/index.ts
Updates the "Support & Consulting" page links
> Update the "Support & Consulting" page links

- README.md
- packages/docs/components/landing/Header.vue
1/ Update readme with "Support & Consulting" page info
2/ Adds "Support & Consulting" link to the header mobile menu
> Update readme with "Support & Consulting" page info

- README.md
1/ Adds Netlify link to README.md
2/ Updates wrong "meet the team" link
> chore: add Netlify link to README.md

- packages/docs/netlify.toml
- packages/ui/netlify.toml
Adds Netlify config to the repo for better DX
> chore: set up Netlify config for the monorepo

- packages/create-vuestic/src/steps/1.scaffoldProject.ts
- packages/create-vuestic/src/steps/3.initGit.ts
- packages/create-vuestic/src/steps/4.installDeps.ts
Use `resolvePath(...parts)` in _`create-vuestic/src/utils/resolve-path.ts`_ to join the path parts as it was already done in _`create-vuestic/src/steps/0.cleanDir.ts`_
https://github.com/epicmaxco/vuestic-ui/blob/4f001516baaa3077322fdafbd3ef936039e712c7/packages/create-vuestic/src/steps/0.cleanDir.ts#L9
> fix: create-vuestic crossplatform paths

- README.md
Hello Vuestic UI team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Vuestic UI Guru](https://gurubase.io/g/vuestic-ui) to Gurubase. Vuestic UI Guru uses the data from this repo and data from the [docs](https://ui.vuestic.dev/introduction/overview/) to answer questions by leveraging the LLM.
In this PR, I showcased the "Vuestic UI Guru" badge, which highlights that Vuestic UI now has an AI assistant available to help users with their questions. Please let me know your …
> Introducing Vuestic UI Guru on Gurubase.io

- packages/ui/src/components/va-tree-view/VaTreeView.stories.ts
- packages/ui/src/components/va-tree-view/VaTreeView.vue
- packages/ui/src/components/va-tree-view/components/VaTreeNode/VaTreeNode.vue
- packages/ui/src/components/va-tree-view/hooks/useTreeHelpers.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/3485
> feat: add expandable prop to tree-view

- packages/ui/src/components/va-data-table/VaDataTable.stories.ts
- packages/ui/src/components/va-data-table/VaDataTable.vue
- packages/ui/src/components/va-virtual-scroller/VaVirtualScroller.vue
> fix(data-table#4421): correct key on expandable table

- packages/ui/src/components/va-file-upload/VaFileUpload.vue
> fix(#4418): use correct file type prop

- packages/ui/src/components/va-icon/VaIcon.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/4417
> fix(icon#4417): add translate no to icon

- packages/ui/src/components/va-slider/CHANGELOG.md
- packages/ui/src/components/va-slider/VaSlider.vue
- packages/ui/src/components/va-slider/_variables.scss
- packages/ui/src/composables/std/event/useEvent.ts
- packages/ui/src/services/i18n/config/default.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/4392
> fix(slider#4392): range slide accessibility

- packages/ui/src/components/va-select/components/VaSelectOptionList/VaSelectOptionList.vue
> fix(select#4437): use correct ref

- packages/ui/src/components/va-layout/components/VaLayoutArea.vue
- packages/ui/src/components/va-layout/components/VaLayoutFixedWrapper.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/4448
> fix(layout#4448): fixed wrapper pointer overflow

- packages/ui/src/components/va-file-upload/VaFileUpload.vue
Fixes #4458 - the Upload Files button sits over the top of open select or date picker menus.
> Fixes Upload File button display issue

- packages/ui/src/components/va-input/VaInput.stories.ts
- packages/ui/src/composables/useValidation.ts
closes #3871 
closes https://github.com/epicmaxco/vuestic-ui/issues/4473
> fix(#3871): validate cleared value if immediate-validation is true

- packages/ui/src/composables/useColors.ts
> fix#4322: correctly resolve on- colors from getColor

- packages/ui/src/components/va-modal/VaModal.vue
- packages/ui/src/components/va-modal/hooks/stories/ModalComponentContent.vue
- packages/ui/src/components/va-modal/hooks/useModal.stories.ts
- packages/ui/src/components/va-modal/hooks/useModal.ts
- packages/ui/src/components/va-modal/modal.ts
- packages/ui/src/components/va-modal/plugin/index.ts
- packages/ui/src/components/va-modal/types.ts
- packages/ui/src/composables/std/internal/useMount.stories.ts
- packages/ui/src/composables/std/internal/useMount.ts
- packages/ui/src/utils/types/unwrap-type.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/3829
closes https://github.com/epicmaxco/vuestic-ui/issues/4267
> feat(useModal): add component argument to init and confirm methods

- packages/ui/src/components/va-slider/VaSlider.vue
Should close https://github.com/epicmaxco/vuestic-ui/issues/4446
> fix(slider#4446): update the dot handler position

- packages/docs/page-config/services/icons-config/code/redefine-icons.ts
- packages/docs/page-config/services/icons-config/index.ts
On `Icon Config` information page added "How to redefine default icons" block with example
<details>
```vue
// Your code
```
</details>
> feat(docs):  added "How to redefine default icons" block

- packages/ui/src/components/va-slider/VaSlider.vue
Fix position `dot--value` in `Vertical` slider: refunded `div` element in component layout
> fix: vertical slider position dot--value

- packages/create-vuestic/package.json
- packages/create-vuestic/src/generators/create-nuxt.ts
- packages/create-vuestic/src/steps/1.scaffoldProject.ts
- yarn.lock
closes https://github.com/epicmaxco/vuestic-ui/issues/4338
closes https://github.com/epicmaxco/vuestic-ui/issues/4490
closes https://github.com/epicmaxco/vuestic-ui/issues/4489
> fix(create-vuestic): infinite loading with new nuxt cli

- packages/docs/page-config/ui-elements/data-table/examples/NoDataSlots.vue
- packages/docs/page-config/ui-elements/data-table/index.ts
Add documentation  for no-data slot of data table.
Closed #4494
> docs: add no-data slot documentation

- packages/ui/src/components/va-date-picker/VaDatePicker.stories.ts
- packages/ui/src/components/va-date-picker/components/VaDatePickerHeader/VaDatePickerHeader.vue
- packages/ui/src/components/va-input-wrapper/VaInputWrapper.stories.ts
- packages/ui/src/components/va-input-wrapper/VaInputWrapper.vue
- packages/ui/src/components/va-input-wrapper/components/index.ts
- packages/ui/src/components/va-input/VaInput.stories.ts
- packages/ui/src/components/va-input/VaInput.vue
<details>
```vue
// Your code
```
</details>
> fix(#4544): :child:name for input and DatePicker
