epicmaxco/vuestic-ui

- package.json
- src/components/vuestic-components/va-sidebar/TransitionExpand.vue
- src/components/vuestic-components/va-sidebar/VaSidebarLinkGroup.vue
- yarn.lock
Remove `vue-bulma-expanding` from the project and substitute it with our own solution
*Ready to be merged*
**Here's the first part, make sure to merge both: [here](https://github.com/epicmaxco/vuestic-admin/pull/643)**
> feat: remove vue-bulma-expanding from the project

- src/components/vuestic-components/va-card/VaCard.vue
Fix for the issue (#656)[https://github.com/epicmaxco/vuestic-admin/issues/656].
Removed z-index property for the card stripe.
> fix: remove unnecessary z-index from va-card

- src/components/vuestic-components/va-sidebar/VaSidebar.vue
- src/components/vuestic-sass/resources/_variables.scss
forgot to override sidebar height when the media query changed navbar to top: $sidebar-mobile-top
> fix: sidebar mobile height

- package.json
Added theme restore mechanism for ColorThemePlugin.
Updated vue-epic-bus version to prevent issues with transpileDependencies. 
Connected with this [PR](https://github.com/epicmaxco/vuestic-admin/pull/665)
> fix: restore mechanism for themes

- src/components/vuestic-components/va-button-dropdown/VaButtonDropdown.vue
- src/components/vuestic-components/va-button/VaButton.demo.vue
- src/components/vuestic-components/va-button/VaButton.vue
- src/components/vuestic-components/va-toggle/VaToggle.vue
- src/components/vuestic-sass/resources/_variables.scss
Fixing https://github.com/epicmaxco/vuestic-ui/issues/151 by adding min-width to button and removing y-axis padding as sizing factor, adding fixed height instead. This method is used by multiple frameworks, like Vuetify.
> fix: empty button appearance

- docs/components/VaProgressBar.md
- src/components/vuestic-components/va-progress-bar/progress-types/VaProgressCircle.demo.vue
- src/components/vuestic-components/va-progress-bar/progress-types/VaProgressCircle.vue
closes #144
Cap ProgressCircle `thickness` prop between 0 and 30 values.
> fix: cap ProgressCircle thickness between 0 and 50

- packages/ui/src/components/context-test/context-provide/ContextPlugin.ts
This should fix typescript errors with dynamic properties provided by ContextableMixin
> Add dynamic property for contextable mixin to get rid of typescript error

- packages/ui/src/mixins/SizeMixin.spec.ts
- packages/ui/src/mixins/SizeMixin.ts
-fontSizeComputed now always in rem (px are auto converted to rems)
Closes #261
> Fix SizeMixin not working correctly

- packages/docs/components/header/components/LanguageDropdown.vue
closes #338
We passed 'gb' value instead of 'en' to the vue router and router didn't recognise this value in locales folder. Fix replaces 'gb' with 'en'
> (fix) language selector

- packages/ui/src/components/vuestic-components/va-slider/VaSlider.vue
Fix for #441
CSS calc method worked unstable on the safari, was replaced by the transform property
> replace calc by css transition method

- packages/docs/app/router.scrollBehavior.js
- packages/docs/layouts/default.vue
Fixes: #476
Add this feature inside `router.scrollBehavior.js` it changes only scroll for the components layout, window scroll is still `{x: 0, y: 0}`
> Scroll layout to top

- packages/ui/src/components/vuestic-components/va-form/VaForm.vue
- packages/ui/src/components/vuestic-components/va-form/consts.ts
- packages/ui/src/components/vuestic-mixins/FormComponent/FormComponentMixin.ts
closes #513
<details>
Changes:
- Removed useless `// @ts-ignore`  
- Moved `FormProvider, FormServiceKey` from component exports to separated file `consts.ts` for better ts typing.
- Changed internalErrorMessages from null to []
```ts
internalErrorMessages: any[] = []
```
</details>
> Fix #513 VaSelect error messages is null

- packages/ui/src/components/vuestic-components/va-button/VaButton.vue
- packages/ui/src/components/vuestic-components/va-card/VaCard.vue
- packages/ui/src/components/vuestic-components/va-chip/VaChip.vue
- packages/ui/src/components/vuestic-components/va-list/VaListItem.vue
- packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue
closes #515 
`v-on="inputListeners"` was bind to route-link (`<component  tag="router-link" />`).
Route-link does not support `v-on`, therefore we need to use `.native` modifier (for vue2)  or move all listeners to a div wrapper.
> fix #515 move v-on listeners from router-link to child div

- packages/ui/src/components/vuestic-components/va-breadcrumbs/VaBreadcrumbs.vdemo.vue
- packages/ui/src/components/vuestic-components/va-breadcrumbs/VaBreadcrumbs.vue
closes #517 
the type of `v-for` items is `Symbol(Fragment)`, we need to check this
<details>
```vue
// Your code
```
</details>
> fix: render va-breadcrumbs-items using v-for directive (#517)

- packages/ui/src/components/vuestic-components/va-tabs/VaTab/VaTab.vue
- packages/ui/src/components/vuestic-components/va-tabs/VaTabs.vdemo.vue
- packages/ui/src/components/vuestic-components/va-tabs/VaTabs.vue
closes #502 
Also removed unnecessary function. Becouse we have same functionality in setup function.
```js
// TODO: check if this even works
parseItems () {
const content = (this as any).$slots.default || 0
```
> fix #502 now the first tab does not become active by default

- packages/ui/src/components/vuestic-components/va-card/VaCard.vdemo.vue
- packages/ui/src/components/vuestic-components/va-card/VaCard.vue
- packages/ui/src/components/vuestic-components/va-card/VaCardContent.vue
- packages/ui/src/components/vuestic-components/va-card/VaCardTitle.vue
closes #503
Added one more demo "Dark (Colored)"
> fix #503 use default white text color for dark card title and content

- packages/ui/src/components/vuestic-components/va-slider/VaSlider.vue
closes #501
Concrete vue ref was expected as an array. This caused an error because the `focus` method cannot be called for `undefiend`.
> fix #501 changed dot0 and dot1 ref types from array to HTMLElement.

- packages/ui/src/components/vuestic-components/va-chip/VaChip.vue
- packages/ui/src/components/vuestic-components/va-modal/VaModal.vue
- packages/ui/src/components/vuestic-mixins/StatefulMixin/README.md
- packages/ui/src/components/vuestic-mixins/StatefulMixin/StatefulMixin.ts
closes #508 
Replaced undefiend to prop modelValue value:
```ts
export class StatefulMixin extends mixins(PropsMixin) {
valueState: ValueState = {
modelValue: this.$props.modelValue,
}
// ...
}
```
From Readme
> `:value` allows to set default value for stateful component, and `@input` just informs parent of the change.
Also Readme was updated for vue3
>  `:modelValue` allows to set default value for stateful component, and `@update:modelValue` just informs parent of the change.
This changes allow us to set default value for `:modelValue` for stateful components using following code:
```ts
modelValue = prop<boolean>({ type: Boolean, default: true }) 
// Then
this.valueComputed === true // true
// Or
modelValue = prop<boolean>({ type: Boolean, default: false}) 
// Then
this.valueComputed …
```
> Fix#508/strange stateful mixin logic

- packages/ui/src/components/vuestic-components/va-input/VaInput.vue
- packages/ui/src/components/vuestic-components/va-select/VaSelect.vue
Remove annoying margin from VaSelect and VaInput if `prepend` and `append` slots not passed. in 2847dad
Also fixes by eslint in ba65861
> Fix / VaSelect additional margins

- packages/ui/src/components/vuestic-components/va-input/VaInput.vdemo.vue
- packages/ui/src/components/vuestic-components/va-input/VaInput.vue
closes #533 
I propose to use two attributes for `va-input` and `input` classes, 
Example:
```
<va-input
class="mb-4"
inputClass="p-2 text-red"
...
/>
```
This way `mb-4` class will not affect `input` element inside `va-input` and will prevent this class from being used twice.
> Fix#533/input double class

- packages/ui/src/components/vuestic-sass/global/reset.scss
- packages/ui/src/components/vuestic-sass/resources/_mixins.scss
closes #520
Added default padding for buttons and redefine default browser styles. Also now buttons horizontal padding equal to vuestic admin button padding size (`1.25rem` = `20px`).
> Fix#520. Added default padding for buttons.

- packages/docs/src/components/sidebar/Sidebar.vue
- packages/ui/src/components/vuestic-components/va-sidebar/VaSidebarItem/VaSidebarItem.vue
- packages/ui/src/services/color-config/color-functions.ts
From 
To
Looks less pretty, but now if the user select the `primary` color as active color it will be the `primary` color, not `primary` with 20% alpha.
Users still can use this pretty sidebar item as we have in docs.
Also, I have fixed the hover color in our docs.
> Now active sidebar item uses exacly activeColor without alpha by default

- packages/ui/src/components/vuestic-components/va-button/VaButton.vue
Fix #822.
The `v-on="inputListeners"` used to be attached to the contents block (which is basically the button's text (usually)) and not to the button element itself. Changed the behavior and it seems working as intended to.
Was it some kind of a mistake/typo or am I missing something?
> fix: va-button clickable area

- packages/docs/src/components/DocsExample.vue
Added a wrapper-element with `overflow: auto` to wrap addressable components in docs' examples. This allows to horizontally scroll content (e.g. tables) if it doesn't fit a small screen. See #787 for details.
```vue
// Your code
```
</details>
> fix: #787 (fix horiz. scroll for tables in docs)

- packages/docs/src/components/header/components/LanguageDropdown.vue
- packages/docs/src/components/page-configs/ui-elements/va-button-dropdown/api-options.ts
- packages/docs/src/components/page-configs/ui-elements/va-button-dropdown/page-config.ts
- packages/docs/src/examples/va-button-dropdown/ClickInside.vue
- packages/docs/src/locales/en/en.json
- packages/ui/src/components/vuestic-components/va-button-dropdown/VaButtonDropdown.demo.vue
- packages/ui/src/components/vuestic-components/va-button-dropdown/VaButtonDropdown.vue
- packages/ui/src/components/vuestic-components/va-dropdown/VaDropdown.demo.vue
- packages/ui/src/components/vuestic-components/va-dropdown/VaDropdown.vue
- packages/ui/src/components/vuestic-components/va-popover/VaPopover.demo.vue
- packages/ui/src/components/vuestic-components/va-popover/VaPopover.vue
- packages/ui/src/components/vuestic-components/va-select/VaSelect.demo.vue
- packages/ui/src/components/vuestic-components/va-select/VaSelect.vue
- packages/ui/src/components/vuestic-components/va-select/VaSelectOptionList/VaSelectOptionList.vue
Fix #789: Refactor Dropdown, closeOnContentClick prop, StatefulMixin are added
Now you could use closeOnContentClick as a flag to mark dropdown that should close its content on click.
Default behavior is set to close content on click.
VaButtonDropdown now uses model as described in our docs instead of not doing anything.
Also StatefulMixin is added to VaDropdown & VaButtonDropdown.
VaDropdown refactored - logic improved and simplified.
<details>
```vue
<va-button-dropdown
color="primary"
flat
:label="currentLanguageName"
:offset="[0, 25]"
:isContentClosable="true"
>
```
</details>
> Fix #789: Dropdown refactor, closeOnContentClick prop, StatefulMixin are added

- packages/docs/src/components/sidebar/Sidebar.vue
- packages/ui/src/components/vuestic-components/va-collapse/VaCollapse.vue
closes #844 
This also fixes the keyboard-tab'ing issue.
> fix: #844 don't use <a> for collapse custom headers in docs' sidebar

- packages/ui/src/components/vuestic-components/va-input/VaInput.vue
- packages/ui/src/components/vuestic-components/va-select/VaSelect.vue
close #847
Selecting an item from VaSelect options list will not scroll up to the top anymore,
It will be a lot easier to keep selecting other items when "multiple" prop is set to true.
</details>
> Fix #847: VaSelect searchBar focus won't scroll up

- packages/docs/package.json
- packages/docs/src/components/header/components/LanguageDropdown.vue
- packages/docs/src/components/languages.ts
- packages/docs/src/helpers/I18nHelper.ts
- packages/docs/src/layouts/default.vue
- packages/docs/src/locales/index.ts
- packages/docs/src/main.ts
- packages/docs/src/router/index.ts
- yarn.lock
closes #645
This PR removes the `vue-lang-router` dependency. 
It seems like this dependency is a great solution for vue2, but not for vue3. Because this dependency works with aliases, it uses hacks and works incorrectly anyway. In `vue-router` you can not simply change the route to its alias for some reason. So I decided to simply copy routes, without aliases. Also, `vue-lang-router` has poor support and don't have updates for a 3 month.
Also, in this PR dropdown with English and Español languages become shown. Because this PR fixes localizations I returned this dropdown back. 
We can temporarily remove Español language by just commenting it here packages/docs/src/components/languages.ts
> Fix docs locale

- packages/ui/src/components/vuestic-components/va-dropdown/VaDropdown.demo.vue
- packages/ui/src/components/vuestic-components/va-dropdown/VaDropdown.vue
close #900 
The bug occurred when the default v-model was true and the keep-anchor-width prop was set.
It was:
Now:
> fixed VaDropdown when v-model true by default

- packages/ui/src/components/vuestic-components/va-slider/VaSlider.demo.vue
- packages/ui/src/components/vuestic-components/va-slider/VaSlider.vue
close #927 
Changed order of icons in vertical slider.
Fixed append and prepend slots  in vertical slider.
Fixed the color of a slot label.
Hid tags of label section when invert-label is true and label is not present.
Changed Slider Demos.
> fix some bugs in va-slider

- packages/docs/src/utilities/markdown-view/MarkdownView.vue
- packages/ui/src/components/vuestic-components/va-badge/VaBadge.demo.vue
- packages/ui/src/components/vuestic-components/va-badge/VaBadge.vue
- packages/ui/src/components/vuestic-components/va-badge/_variables.scss
- packages/ui/src/components/vuestic-components/va-button/VaButton.demo.vue
- packages/ui/src/components/vuestic-components/va-button/VaButton.vue
close #862 
close #791 
va-button should display multiline text without errors now.
Also I removed the variable --va-badge-text-wrapper-font-size, it is not needed because --va-badge-font-size does the same
Added indentation for code elements in a paragraph
> #862 fixed multiline button and remove unnecessary sccs variable

- packages/docs/src/components/header/components/LanguageDropdown.vue
- packages/docs/src/locales/index.ts
Closes #903
Now, DOC's homepage takes local storage/navigator language value as default.
> Added language auto-detection.

- packages/docs/package.json
- packages/docs/src/components/DocsLink.vue
- packages/docs/src/components/page-configs/contribution/documentation-page/page-config.ts
- packages/docs/src/components/page-configs/contribution/documentation-page/table-options.ts
- packages/docs/src/components/page-configs/styles/typography/page-config.ts
- packages/docs/src/locales/en/en.json
- packages/docs/src/locales/ru/ru.json
- packages/docs/src/main.ts
- packages/docs/src/markdown-it-attrs.d.ts
- packages/docs/src/utilities/markdown-view/MarkdownIt.ts
- packages/docs/src/utilities/markdown-view/MarkdownView.vue
- packages/docs/src/utilities/markdown-view/set-class-attribute-to-external-links.ts
- packages/docs/src/utilities/markdown-view/set-origin-location-to-relative-links.ts
- yarn.lock
close #962
Some of the changes:
- add external package and connect plugin "markdown-it-attrs", allowed to include attributes (with special delimiters) to markdown tokens (in our case, to links: `[[target="_blank"]]`)
- add `setClassAttributeToExternalLinks` plugin
- add `setOriginLocationToRelativeLinks` plugin (set `window.location.origin` and locale (from `useI18n` hook))
- split `MarkdownIt` into a separate instance
- rewrite `MarkdownView` in Composition API style
- replace `<a>` tags with markdown syntax in locale strings, add `[[target="_blank"]]` to all external links
- minor updates locales, page-config files
> Fix #962 Add markdown-it plugins for processing links in MarkdownView

- packages/ui/package.json
- yarn.lock
Moved the `tslib` from `devDependencies` to `dependencies` to remove the warning when installing the project.
Close https://github.com/epicmaxco/vuestic-ui/issues/998
Installed minimum version 2.2.0, same as in child library which requires this dependency ([asvae-executors](https://github.com/asvae/executors)).
> VA-998 move tslib to dependencies

- packages/ui/build/rollup/configs/esm.js
- packages/ui/build/rollup/generate-rollup-inputs.js
For some reason, Vite can not build bundled lib using `preserve modules` option. So I decided to split esm bundle into chunks providing multiple inputs, that were generated using readdir of `/src/components` folder.
I checked this PR with `vite preview` command nad `vite dev`.
It also works with webpack (vue-cli).
I think this PR should be merged after tree-shaking tests is ready to prevent unexpected issues.
closes #1024
> Fix vite build

- .github/CONTRIBUTING.md
Fix CONTRIBUTING.md guide link pointing to localhost instead of docs. Updated to use same link as in /README.md
<details>
```
Check contribution docs [here](https://vuestic.dev/en/contribution/guide).
```
</details>
(First time trying to help out OSS. Feel free to flame accordingly.)
> fix: CONTRIBUTING.md link pointing to localhost

- package.json
- packages/ui/package.json
- packages/ui/src/components/va-icon/VaIcon.vue
- packages/ui/src/mixins/SizeMixin.ts
close #1054
close #1087
**Global config sizes** are applied by the sizeMixin now correctly.
This is a temporary solution because I found out that we have slightly bigger issue overall with global configs not being applied in the build version.
I've checked everything related to configs logic and it works as expected except for withConfigTransport - most likely it will be the part of a global solution.
However this issue is resolved and I will just make a new one to take care of the rest.
</details>
> Fix #1054: GlobalConfig sizes, temporary solution

- packages/ui/src/styles/global/reset.scss
closes #1085 
Overrides the normalize.css rule for firefox. Also, we should pay attention to the `:focus-visible` pseudo-selector. It can be useful when it will be supported by all required browsers.
> fix: disable mozilla focusring

- packages/docs/src/locales/en/en.json
- packages/ui/src/components/va-button-group/VaButtonGroup.vue
- packages/ui/src/components/va-button-toggle/VaButtonToggle.vue
- packages/ui/src/components/va-button/_variables.scss
First of all, there was an issue with background passed as style in VaButtonToggle, because of that this style was ignored after switching the active button in VaButtonToggle. Also, It required to remove transition for the border (it does not work anyway). So I made the transition only for background what looks good. 
Next, I fixed the issue with different outlined, flat and default buttons.
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
<tr/>
</table>
closes #1070
closes #1083
> Fix #1083. Move toggle active button styles to props.

- packages/ui/src/services/config-transport/withConfigTransport.ts
Global and local configs were not working completely after the build.
It was caused by `vue-class-component` logic wrapping our code.
The only reason it worked in `dev` is because constructor name was the same as component name here unlike the bundled version.
</details>
> Fix #1042: Global & local configs

- packages/docs/src/examples/va-modal/NestedModals.vue
- packages/ui/src/components/va-data-table/_variables.scss
- packages/ui/src/components/va-dropdown/_variables.scss
- packages/ui/src/components/va-modal/_variables.scss
- packages/ui/src/components/va-toast/VaToast.vue
- packages/ui/src/components/va-toast/_variables.scss
- packages/ui/src/components/va-toast/index.ts
- packages/ui/src/styles/global/css-variables.scss
> Fix#1192 Fix VaModal, VaDropdown and VaToast z-index

- packages/ui/src/components/va-time-picker/VaTimePicker.vue
- packages/ui/src/components/va-time-picker/components/VaTimePickerColumn.vue
> Fix#1243: Set tabindex for disabled VaTimePicker columns

- packages/docs/src/page-configs/ui-elements/checkbox/examples/Coloring.vue
- packages/ui/src/components/va-checkbox/VaCheckbox.vue
> Fix#1201 Fix VaCheckbox selectstart

- packages/docs/src/page-configs/ui-elements/chip/examples/Icon.vue
- packages/ui/src/components/va-chip/VaChip.vue
- packages/ui/src/components/va-chip/_variables.scss
> Fix#1247 Change VaChip vertical-align

- packages/docs/src/components/sidebar/algolia-search/AlgoliaSearch.vue
- packages/ui/src/components/va-input/VaInput.vue
> Fix#1260 Fix VaInput id attr and algolia-search input selector

- packages/docs/src/page-configs/ui-elements/button-dropdown/examples/Default.vue
- packages/ui/src/components/va-button-dropdown/VaButtonDropdown.demo.vue
- packages/ui/src/components/va-button-dropdown/VaButtonDropdown.vue
> Fix #1261 Add round style to va-button-dropdown without label prop

- packages/docs/src/locales/en/en.json
- packages/docs/src/locales/ru/ru.json
- packages/docs/src/page-configs/ui-elements/data-table/api-options.ts
- packages/docs/src/page-configs/ui-elements/data-table/examples/Filtering.vue
- packages/docs/src/page-configs/ui-elements/data-table/examples/Other.vue
- packages/docs/src/page-configs/ui-elements/data-table/examples/Pagination.vue
- packages/docs/src/page-configs/ui-elements/data-table/examples/Sorting.vue
- packages/ui/src/components/va-data-table/VaDataTable.new.demo.vue
- packages/ui/src/components/va-data-table/VaDataTable.vue
- packages/ui/src/components/va-data-table/hooks/useFilterable.ts
- packages/ui/src/components/va-data-table/hooks/useSelectable.ts
- packages/ui/src/components/va-data-table/hooks/useSortable.ts
- packages/ui/src/components/va-data-table/hooks/useStyleable.ts
> Fix#1204 Add VaDataTable events

- packages/docs/src/page-configs/ui-elements/input/examples/Hint.vue
- packages/docs/src/page-configs/ui-elements/select/examples/Decorators.vue
- packages/docs/src/page-configs/ui-elements/select/examples/Slots.vue
- packages/docs/src/page-configs/ui-elements/select/examples/Variations.vue
- packages/ui/src/components/va-input/VaInput.vue
- packages/ui/src/components/va-input/components/VaInputField.vue
- packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-select/VaSelectOptionList/VaSelectOptionList.vue
- packages/ui/src/composables/useMaxSelections.ts
close: #1258 
close: #1286 
Changes:
> Fix#1258 Fix VaSelect dropdown width

- packages/ui/src/components/va-select/VaSelect.vue
> Fix behavior of select dropdown when tab key pressed

- packages/ui/src/components/va-time-input/VaTimeInput.vue
- packages/ui/src/components/va-time-input/hooks/time-text-parser.ts
> Fix #1226 Fix VaTimeInput bug when passed text is not valid

- packages/docs/src/locales/en/en.json
- packages/docs/src/page-configs/ui-elements/select/api-options.ts
- packages/ui/src/components/va-select/VaSelect.demo.vue
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-select/VaSelectOptionList/VaSelectOptionList.vue
closes #1380 
Added the event scroll-bottom for the VaSelect component. It should be working as expected. If you scroll at bottom of the options, the new scroll-bottom event is emitted. The new feature was also added to the documentation (only for English).
> VaSelect on scroll bottom event

- packages/ui/src/components/va-tabs/VaTabs.vue
> Fix#1401 Set `display: none` to tabs slider when hideSlider=true

- packages/docs/src/locales/en/en.json
- packages/docs/src/locales/ru/ru.json
- packages/docs/src/page-configs/services/icons-config/examples/font.vue
- packages/docs/src/page-configs/services/icons-config/page-config.ts
- packages/docs/src/page-configs/ui-elements/icon/examples/Default.vue
- packages/ui/src/components/va-icon/VaIcon.vue
- packages/ui/src/services/icon-config/types.ts
close: #1420
changes:
no duplication of classes:
> Fix#1420 Correct `VaIcon` and icons config docs

- packages/docs/src/page-configs/ui-elements/select/examples/State.vue
- packages/ui/src/components/va-input/VaInput.demo.vue
- packages/ui/src/components/va-input/VaInput.vue
- packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue
- packages/ui/src/components/va-select/VaSelect.demo.vue
- packages/ui/src/components/va-select/VaSelect.vue
> Fix#1471 Fix `VaSelect` and `VaInput`(`textarea`) readonly

- packages/ui/src/components/va-button/VaButton.demo.vue
- packages/ui/src/components/va-config/VaConfig.demo.vue
- packages/ui/src/components/va-data-table/VaDataTable.demo.vue
- packages/ui/src/components/va-data-table/VaDataTable.new.demo.vue
- packages/ui/src/components/va-date-input/VaDateInput.demo.vue
- packages/ui/src/components/va-date-picker/VaDatePicker.demo.vue
- packages/ui/src/components/va-dropdown/VaDropdown.demo.vue
- packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue
- packages/ui/src/components/va-form/VaForm.demo.vue
- packages/ui/src/components/va-input/VaInput.demo.vue
- packages/ui/src/components/va-select/VaSelect.demo.vue
- packages/ui/src/components/va-tabs/VaTabs.vue
- packages/ui/src/components/va-time-input/VaTimeInput.demo.vue
- packages/ui/src/vue-book/book-main.ts
closes #1518
In this PR I removed global components from vue-book, so now we forced to import child components directly in component. This will fix unresolved components issue in tree-shaking build.
Would be nice to have some eslint rule, but this PR is only hotfix.
> Don't use global components in vue-book. Fix unresolved components.

- packages/bundlers-tests/package.json
- packages/bundlers-tests/vite.config.ts
- packages/docs/src/page-configs/ui-elements/data-table/examples/Sorting.vue
- packages/ui/jest.config.js
- packages/ui/package.json
- packages/ui/src/components/va-affix/VaAffix-utils.ts
- packages/ui/src/components/va-affix/VaAffix.vue
- packages/ui/src/components/va-button-dropdown/VaButtonDropdown.vue
- packages/ui/src/components/va-data-table/VaDataTable.demo.vue
- packages/ui/src/components/va-data-table/VaDataTable.new.demo.vue
- packages/ui/src/components/va-data-table/hooks/useColumns.ts
- packages/ui/src/components/va-icon/VaIcon.vue
- packages/ui/src/components/va-infinite-scroll/VaInfiniteScroll.vue
- packages/ui/src/components/va-input/VaInput.vue
- packages/ui/src/components/va-input/components/VaTextarea/VaTextarea.vue
- packages/ui/src/components/va-modal/tests/VaModal.spec.disabled.ts
- packages/ui/src/components/va-time-input/VaTimeInput.vue
- packages/ui/src/composables/useValidation.ts
- packages/ui/src/data/Records.ts
- packages/ui/src/mixins/ClickOutsideMixin/ClickOutsideMixin.ts
- packages/ui/src/mixins/FormComponent/FormComponentMixin.ts
- packages/ui/src/services/config-transport/withConfigTransport.ts
- packages/ui/src/services/global-config/global-config.ts
- packages/ui/src/services/icon-config/icon-helpers.ts
- packages/ui/src/services/utils.ts
- yarn.lock
THIS PR with #1501 close #1511
Use `lodash` instead of `lodash-es`. It shouldn't break tree shaking if we use `lodash/[function]` import style. 
Because `vuestic-ui` must work with SSR (e.g. with node and CJS format) we don't need to use esm-only libs.
> Fix vite SSR build

- packages/docs/src/locales/en/en.json
- packages/ui/src/components/va-input/VaInput.vue
Now va-input accepts `pattern` and `input-mode` props and use those to enhance mobile device experiences.
Fixes #1566
<details>
Pattern is probably used in form submit check. Inputmode can decide what kind virtual keyboard is show to input.
```vue
<va-input pattern="[0-9]{8}" inputmode="tel" />
```
</details>
> va-input accepts `pattern` and `inputmode` props

- packages/ui/src/components/va-date-input/VaDateInput.vue
> [#1620] Fix `VaDateInput` icon color

- packages/ui/src/composables/useSyncProp.ts
This reverts commit 10748572f8df9f8847f54e1aea8f2de7f3c955d7.
Removing useSyncProp requires extending functional of useStateful.
> Revert "deleted state in useSyncProps (#1645)"

- packages/ui/src/components/va-card/VaCard.vue
- packages/ui/src/components/va-radio/VaRadio.demo.vue
- packages/ui/src/components/va-radio/VaRadio.vue
- packages/ui/src/components/va-switch/VaSwitch.demo.vue
- packages/ui/src/components/va-switch/VaSwitch.vue
- packages/ui/src/styles/resources/_mixins.scss
close: #1657 
- `VaSwitch` has readonly state. Example added.
- Added readonly state for `VaRadio` (and example). I'd thought about implementing this via `useSelectable`, but it is not suitable in its current form, and its adaptation looks like an unnecessary complication of the common composable cause of a single case.
> [#1657] VaRadio readonly state, VaRadio & VaSwitch examples updated

- packages/docs/src/components/DocsCode.vue
- packages/docs/src/helpers/DocsHelper.ts
- packages/docs/src/page-configs/extensions/ag-grid/page-config.ts
- packages/docs/src/page-configs/getting-started/configuration-guide/code-examples/icons.ts
- packages/docs/src/page-configs/getting-started/configuration-guide/page-config.ts
- packages/docs/src/page-configs/getting-started/installation/code-examples/installation.ts
- packages/docs/src/page-configs/getting-started/installation/page-config.ts
- packages/docs/src/types/configTypes.ts
Add tabs to code examples.
fixes #1674
Pass in code object with keys as tab, values as code content.
<details>
```vue
block.code({
'npm': 'npm install @vuestic/agGrid-theme',
'yarn': 'yarn add @vuestic/agGrid-theme'
})
```
</details>
> Add tabs to code examples with object format.

- packages/docs/src/assets/fonts.scss
- packages/docs/src/components/DocsContent.vue
- packages/docs/src/components/header/Header.vue
- packages/docs/src/components/header/components/ColorDropdown.vue
- packages/docs/src/components/header/components/LanguageDropdown.vue
- packages/docs/src/components/header/components/VersionDropdown.vue
- packages/docs/src/components/landing/Admin.vue
- packages/docs/src/components/landing/Customize.vue
- packages/docs/src/components/landing/Footer.vue
- packages/docs/src/components/landing/Header.vue
- packages/docs/src/components/landing/OpenSource.vue
- packages/docs/src/components/landing/Preview.vue
- packages/docs/src/components/landing/SeamlessIntegration/SeamlessIntegration.vue
- packages/ui/src/components/va-icon/VaIcon.vue
close: #1478 
All items from 1478 were closed, but i should mention some moments:
> set primary color to 2550c0 (not 4382d9)
There is no 4382d9 at all, but i can see 2550c0. So, i guess, it was already changed.
> docs menu items should lead to introduction > Overview (not to the roadmap)
Done, but it seems strange, that overview & doc links lead to the one page. May be overview link should have '/' href? It's logically, cause of another item: "overview should be black on the landing page".
> [#1478] landing visual tweaks

- packages/docs/public/index.html
- packages/docs/src/locales/en/en.json
- packages/docs/src/page-configs/styles/typography/code-examples/font.ts
- packages/docs/src/page-configs/styles/typography/page-config.ts
Style sheets uses `Source Code Pro` but didn't import it. This pr import it in `docs/public/index.html`.
fixes #1339
> Added code font alert in typography docs

- packages/ui/src/components/va-date-input/VaDateInput.vue
- packages/ui/src/components/va-input/VaInput.vue
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-time-input/VaTimeInput.vue
- packages/ui/src/composables/useClearable.ts
- packages/ui/src/composables/useFocus.ts
- packages/ui/src/composables/useSelectable.ts
- packages/ui/src/composables/useValidation.ts
close: #1710 
As discussed during the grooming, it's a bad practice to reexport composables or import them as args through components - their logic should be incapsulated as much as possible.
> [#1710] composables refactoring

- packages/docs/src/components/DocsContent.vue
close: #1479 
Seems, that these changes are needed only for docs website, not for va-content component, so, linked styles were just overwritten.
> for some reasons we use h1, h3, h5, h6. can we use h1, h2, h3, h4 instead.
It is possible, but more styles should be overwritten. I guest, this is not a todo item, but just a suggestion for this moment.
> [#1479] vuestic docs website tweaks

- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-select/VaSelectOptionList/VaSelectOptionList.vue
Close #1758
All `VaSelect` actions and keyboard navigation were completely broken, now it is fixed.
- Keyboard navigation works
- UX improved - `VaSelect` will scroll to and focus last selected option
- All `actions` that were using `optionList` functions work now - `hintedSearch` etc.
</details>
> Fix #1758: `VaSelect` actions and navigation

- packages/ui/src/components/va-date-input/VaDateInput.vue
- packages/ui/src/components/va-date-input/hooks/input-text-parser.ts
- packages/ui/src/components/va-date-input/hooks/model-value-parser.ts
- packages/ui/src/components/va-date-input/hooks/range-model-value-guard.ts
- packages/ui/src/components/va-date-input/types/index.ts
- packages/ui/src/components/va-date-picker/utils/date-utils.ts
Close #1789
Fixed types for `VaDateInput` and its imports.
There were multiple TS errors.
</details>
> Fix #1789: types for VaDateInput and its dependencies

- packages/docs/src/page-configs/ui-elements/carousel/examples/Slots.vue
- packages/ui/src/components/va-carousel/VaCarousel.vue
The demo with slots is using wrong slots names.
```diff
- prev-next
+ next-arrow
```
> fix: carrousel demo slots wrong name

- packages/docs/src/locales/en/en.json
- packages/docs/src/page-configs/services/icons-config/examples/font.vue
- packages/docs/src/page-configs/services/icons-config/page-config.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/563
closes https://github.com/epicmaxco/vuestic-ui/issues/1613
Added regex demo:
(Upper demo styles fixed in another PR)
Updated API docs:
> Updated Icon Config docs.

- packages/docs/src/components/DocsExample.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/1118
I just made padding smaller.
> Fix show code button focus state in docs.

- packages/ui/src/components/va-button-group/VaButtonGroup.vue
- packages/ui/src/components/va-button-group/_variables.scss
- packages/ui/src/components/va-pagination/VaPagination.vue
- packages/ui/src/components/va-pagination/_variables.scss
closes https://github.com/epicmaxco/vuestic-ui/issues/1275
> Prevent pagination numeric buttons changin its width if content is long.

- packages/docs/src/locales/en/en.json
- packages/ui/src/components/va-file-upload/VaFileUpload.vue
> Fix#1773/file upload single model value

- packages/ui/src/components/va-radio/VaRadio.vue
- packages/ui/src/styles/global/_utility-global.scss
- packages/ui/src/styles/resources/_mixins.scss
close: #1838 
`VaRadio` `Tab` navigation was broken - now it's fixed. Few minor related accessibility updates. 
P.S. Safari tab navigation - `Opt` + `Tab` (https://stackoverflow.com/questions/1848390/safari-ignoring-tabindex). Can think about global service to replace this behaviour (not sure if we need to).
> [#1838] va-radio tab selection fix, accessibility updates

- packages/ui/src/components/va-date-input/VaDateInput.vue
- packages/ui/src/components/va-date-picker/VaDatePicker.vue
> Fix #1785: VaDateInput keyboard navigation, click and focus events

- packages/ui/src/composables/useStateful.ts
Closes #1846
`useStateful` now works correctly with `modelValue` - previously `modelValue` updates were ignored completely.
</details>
> Fix #1846: useStateful works with modelValue

- packages/ui/src/components/va-checkbox/VaCheckbox.vue
- packages/ui/src/components/va-chip/VaChip.vue
- packages/ui/src/components/va-color-indicator/VaColorIndicator.vue
- packages/ui/src/components/va-color-input/VaColorInput.vue
- packages/ui/src/components/va-color-palette/VaColorPalette.vue
- packages/ui/src/components/va-counter/VaCounter.vue
- packages/ui/src/components/va-data-table/VaDataTable.vue
- packages/ui/src/components/va-date-input/VaDateInput.vue
- packages/ui/src/components/va-date-picker/components/VaDatePickerHeader/VaDatePickerHeader.vue
- packages/ui/src/components/va-file-upload/VaFileUpload.vue
- packages/ui/src/components/va-file-upload/VaFileUploadGalleryItem/VaFileUploadGalleryItem.vue
- packages/ui/src/components/va-file-upload/VaFileUploadListItem/VaFileUploadListItem.vue
- packages/ui/src/components/va-input/VaInput.vue
- packages/ui/src/services/color-config/color-theme-presets.ts
- packages/ui/src/styles/resources/_mixins.scss
Related to:
#1374 
#1810 
`VaColorIndicator`, `VaColorInput`, `VaDateInput`, `VaDatePicker`, `VaFileUpload`, `VaDateTable`, `VaCounter`, `VaColorPalette`  accessibility updates & dom optimization checks. Minor updates to related components.
> Components accessibility updates & dom optimization checks

- packages/ui/src/components/va-dropdown/plugin/index.ts
- packages/ui/src/components/va-modal/plugin/index.ts
- packages/ui/src/components/va-toast/plugin/index.ts
- packages/ui/src/services/color-config/plugin/index.ts
- packages/ui/src/services/global-config/plugin/index.ts
- packages/ui/src/vuestic-plugin/utils/global-properties.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/1879
For some reason, we need to declare 'vue' instead of '@vue/runtime-dom' if we want to add global properties.
Result (read before in issue)
> Fix redeclaration of @vue/runtime-core.

- packages/docs/src/components/sidebar/Sidebar.vue
closes #1781 
Strict check that current path ends with a route name.
> [#1781] Fix: docs sidebar active route determination

- packages/ui/src/components/va-data-table/VaDataTable.demo.vue
- packages/ui/src/components/va-data-table/VaDataTable.new.demo.vue
- packages/ui/src/components/va-data-table/VaDataTable.vue
> [#1876] `VaDataTable` remove extra `click` emit

- packages/docs/src/components/DocsCode.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/1816
Before
Now
> fix#1816 escape vuestic import in docs

- packages/ui/src/components/va-accordion/VaAccordion.vue
- packages/ui/src/components/va-accordion/_variables.scss
- packages/ui/src/components/va-collapse/VaCollapse.vue
- packages/ui/src/components/va-collapse/_variables.scss
closes #1957
closes https://github.com/epicmaxco/vuestic-ui/issues/1811
There was a gap between two sidebar elements. (even in our docs sidebar)
Made accordion without gaps:
> fix#1957 Remove collapse margin. Beautify accordion.

- packages/docs/src/locales/en/en.json
- packages/docs/src/page-configs/ui-elements/modal/examples/CustomContent.vue
- packages/docs/src/page-configs/ui-elements/modal/page-config.ts
- packages/ui/src/components/va-modal/VaModal.demo.vue
- packages/ui/src/components/va-modal/VaModal.vue
- packages/ui/src/components/va-modal/_variables.scss
- packages/ui/src/styles/resources/_variables.scss
Fix #1752
- Added padding variables to manage padding
- Added `no-padding` prop
- Added `content` slot which replace all the content inside `va-modal__inner`
- Removed hardcoded paddings and this could brake some of the users code, not sure how to resolve it
```
$modal-padding-top: 1.25rem !default;
$modal-padding-right: 1.875rem !default;
$modal-padding-bottom: 1.5rem !default;
$modal-padding-left: 1.5rem !default;
```
> [#1752] Modal padding and Content improvements

- packages/docs/src/locales/en/en.json
- packages/docs/src/locales/ru/ru.json
- packages/docs/src/page-configs/ui-elements/file-upload/examples/Undo.vue
- packages/docs/src/page-configs/ui-elements/file-upload/page-config.ts
Close #1786
Added examples and translations of the undoing the removing action usage.
> File upload undo examples

- packages/ui/src/components/va-rating/VaRating.demo.vue
- packages/ui/src/components/va-rating/VaRating.vue
- packages/ui/src/components/va-rating/components/VaRatingItem/VaRatingItem.vue
- packages/ui/src/components/va-rating/hooks/useRating.ts
Closes #1952 
2 points.
1. Disabled and readonly props must take precedance over the `hover` prop. In other words, the component must not change its visual appearance when hovered in cases when it's either disabled or readonly.
Before:
https://user-images.githubusercontent.com/9782236/175301383-cf3f6c59-3481-474e-9cc6-f1752b8974de.mp4
After:
https://user-images.githubusercontent.com/9782236/175301614-d0cde0d0-49f0-4eca-8b4a-363f285c5838.mp4
2. **UPDATED - not a bug in the component, rather an improperly used demo. Reverted the fix.**
The hover-hitbox for a rating-item is somewhat corrupted. Modified it so that all the calculations happen in the context of the rating-item itself, not the wrapper. LGTM
Before:
https://user-images.githubusercontent.com/9782236/175302180-917ad9ad-bd33-44a0-bb6 …
> Fix: va-rating-issues

- packages/docs/src/locales/en/en.json
- packages/docs/src/locales/ru/ru.json
- packages/docs/src/page-configs/ui-elements/data-table/examples/CRUD.vue
- packages/docs/src/page-configs/ui-elements/data-table/examples/CustomSlots.vue
- packages/docs/src/page-configs/ui-elements/data-table/examples/Filtering.vue
- packages/docs/src/page-configs/ui-elements/data-table/examples/Other.vue
- packages/docs/src/page-configs/ui-elements/data-table/examples/Selection.vue
- packages/docs/src/page-configs/ui-elements/data-table/examples/Sorting.vue
- packages/ui/src/components/va-data-table/VaDataTable.new.demo.vue
- packages/ui/src/components/va-data-table/VaDataTable.vue
- packages/ui/src/components/va-data-table/hooks/useColumns.ts
- packages/ui/src/components/va-data-table/hooks/useFilterable.ts
- packages/ui/src/components/va-data-table/hooks/useRows.ts
- packages/ui/src/components/va-data-table/hooks/useSortable.ts
- packages/ui/src/components/va-data-table/types.ts
> [#1940] Fixed filtering and sorting of `VaDataTable` when using `items` with nested objects

- packages/ui/src/components/va-rating/components/VaRatingItem/VaRatingItem.vue
Close: #1995 
Added outline for rating items focus state.
> [#1995] Added `VaRating` item focus outline

- packages/ui/src/composables/useDomRect.ts
- packages/ui/src/composables/usePopover.ts
Close https://github.com/epicmaxco/vuestic-ui/issues/2018
va-dropdown__content-wrapper without `top` and `left` properties might position wrongly, which causes the original issue
> [#2018] usePopover - add default position

- packages/ui/src/components/va-dropdown/VaDropdown.vue
> [#2033] Fix `VaDropdown` font

- packages/ui/src/components/va-time-input/VaTimeInput.vue
Close: #1973
Allow to type space symbol when `manual-input` prop truthy.
> feat: allow write space with manual input

- packages/docs/src/components/sidebar/Sidebar.vue
- packages/docs/src/page-configs/ui-elements/sidebar/examples/Color.vue
- packages/docs/src/page-configs/ui-elements/sidebar/examples/Gradient.vue
- packages/ui/src/components/va-collapse/VaCollapse.vue
- packages/ui/src/components/va-collapse/_variables.scss
- packages/ui/src/components/va-sidebar/VaSidebar.vue
- packages/ui/src/components/va-sidebar/VaSidebarItem/VaSidebarItem.vue
- packages/ui/src/components/va-sidebar/VaSidebarItem/VaSidebarItemContent.vue
closes #2028
closes https://github.com/epicmaxco/vuestic-ui/issues/1959
Fix sidebar item colors until 1.5.0. 
Also, hide sidebar title if minimized, instead of making it opacity: 0.
Another breaking change is minimizedWidth set to 4rem from 2.5rem.
This changes looks like Okay?
> Fix#2028/fix sidebar color

- packages/ui/package.json
- yarn.lock
Close: #2071 
Free icons package update solves this problem.
> [#2071] fontawesome deprecated warning fix

- packages/ui/src/components/va-slider/VaSlider.vue
Close: #2073
It wasn't trivial at all :)
For some reason first update emit, even in case it's static, changed `modelValue`.
> [#2073] `VaSlider` range static `modelValue` fix

- packages/nuxt/src/module.ts
- packages/nuxt/src/runtime/plugin.ts
<details>
<summary>plugin.mjs</summary>
```js
import { createVuestic, createVuesticEssential } from "vuestic-ui";
import { ref } from "vue";
import { defineNuxtPlugin } from "nuxt/app";
function getGlobalProperty(app, key) {
return app.config.globalProperties[key];
}
export default defineNuxtPlugin((nuxtApp) => {
const { vueApp: app } = nuxtApp;
const { config } = JSON.parse(`<%= options.value %>`);
const withoutComponents = false;
app.use(withoutComponents ? createVuesticEssential({ config }) : createVuestic({ config }));
const head = getGlobalProperty(app, "$head");
if (head) {
const colorConfig = getGlobalProperty(app, "$vaColorConfig");
if (colorConfig) {
head.addHeadObjs(ref({
htmlAttrs: {
style: colorConfig.renderCSSVarialbes()
}
}));
}
}
});
```
</details>
Improved ts typings as …
> Use defineNuxtPlugin. Improve TS types in plugin.

- packages/docs/src/page-configs/ui-elements/date-input/examples/inputProps.vue
- packages/ui/src/components/va-checkbox/VaCheckbox.vue
- packages/ui/src/components/va-date-input/VaDateInput.demo.vue
- packages/ui/src/components/va-date-input/VaDateInput.vue
- packages/ui/src/components/va-date-input/hooks/input-text-parser.ts
- packages/ui/src/components/va-input/VaInput.vue
- packages/ui/src/components/va-input/components/VaInputWrapper/VaInputWrapper.vue
- packages/ui/src/components/va-switch/VaSwitch.vue
- packages/ui/src/components/va-time-input/VaTimeInput.vue
- packages/ui/src/composables/useSelectable.ts
- packages/ui/src/composables/useValidation.ts
> [#2057] `VaDateInput` & `VaTimeInput` moved to `VaInputWrapper`, refactoring, bugfix

- packages/ui/src/components/va-counter/VaCounter.vue
- packages/ui/src/components/va-date-input/VaDateInput.vue
- packages/ui/src/components/va-date-input/_variables.scss
- packages/ui/src/components/va-input/VaInput.vue
- packages/ui/src/components/va-input/components/VaInputWrapper/VaInputWrapper.vue
- packages/ui/src/components/va-input/components/VaInputWrapper/_variables.scss
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-select/_variables.scss
- packages/ui/src/components/va-time-input/VaTimeInput.vue
- packages/ui/src/components/va-time-input/_variables.scss
- packages/ui/src/styles/global/css-variables.scss
> [#2163] Fix `VaInputWrapper` `min-width`

- packages/docs/src/components/DocsContent.vue
- packages/docs/src/helpers/DocsHelper.ts
- packages/docs/src/page-configs/ui-elements/dropdown/page-config.ts
- packages/docs/src/page-configs/ui-elements/dropdown/specs.md
- packages/docs/src/shims-vue.d.ts
- packages/docs/src/types/configTypes.ts
- packages/docs/vue.config.js
Close #2112
Added markdown files support for the documentation pages.
You can import whole markdown file to the `PageGenerationHelper.markdown` method:
```ts
import { ApiDocsBlock } from '@/types/configTypes'
import { PageGenerationHelper } from '@/helpers/DocsHelper'
// import example markdown file:
import docs from './docs.md'
const block = new PageGenerationHelper(__dirname)
const config: ApiDocsBlock[] = [
block.markdown(docs),
]
export default config
```
Or you can provide markdown code directly:
```ts
import { ApiDocsBlock } from '@/types/configTypes'
import { PageGenerationHelper } from '@/helpers/DocsHelper'
const block = new PageGenerationHelper(__dirname)
// markdown string:
const docs = `
Example text
|Column|Column|
|---|---|
|Text|Text|
`
const config: ApiDocsBlock[] = [ …
```
> feat: add markdown support to the doc pages

- packages/ui/src/components/va-date-input/VaDateInput.vue
- packages/ui/src/components/va-icon/VaIcon.vue
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-time-input/VaTimeInput.vue
> [#2175][#2176] double disabled state fix, cursor fix

- packages/docs/src/page-configs/ui-elements/button-dropdown/examples/Colors.vue
- packages/docs/src/page-configs/ui-elements/button-dropdown/examples/Disabled.vue
- packages/docs/src/page-configs/ui-elements/button-dropdown/examples/Events.vue
- packages/docs/src/page-configs/ui-elements/button-dropdown/examples/Icons.vue
- packages/ui/src/components/va-button-dropdown/VaButtonDropdown.vue
> [#2190] Fix `VaButtonDropdown` dropdown appearance and alignment for `split` and `left-icon`

- packages/docs/src/locales/en/en.json
- packages/docs/src/locales/ru/ru.json
- packages/docs/src/page-configs/ui-elements/input/examples/Mask.vue
- packages/docs/src/page-configs/ui-elements/input/examples/Types.vue
- packages/docs/src/page-configs/ui-elements/input/page-config.ts
- packages/ui/src/styles/global/reset.scss
Close #1925
Added examples of the input's `type` attribute usage in the `va-input` component.
Added css reset for the `type="search"` input.
> feat: add input type attribute usage example

- packages/ui/src/components/va-button/hooks/useButtonAttributes.ts
- packages/ui/src/composables/useRouterLink.ts
Close: #1748 
Partially fixed issue with `to` prop in Nuxt 3 (`nuxt-link` changed to `router-link`).
> [#1748] Fixed `to` prop issue in Nuxt 3

- packages/bundlers-tests/package.json
- packages/nuxt/package.json
- packages/nuxt/src/composables/use-plugin.ts
- packages/nuxt/src/module.ts
- packages/nuxt/src/runtime/plugin.ts
- yarn.lock
Simply moved stuff that we use in nuxt module to dependencies instead of dev dependencies.
closes #2238
> fix(nuxt): move explicitly used imports to dependencies.

- packages/docs/src/page-configs/ui-elements/popover/examples/Color.vue
- packages/docs/src/page-configs/ui-elements/popover/examples/Placement.vue
- packages/docs/src/page-configs/ui-elements/popover/examples/Trigger.vue
A little popover examples fixes. Horizontally aligned examples.
> fix: align popover examples horizontally

- packages/ui/src/components/va-radio/VaRadio.vue
Added a propType to option in vaRadio.vue
> Fix: Types. VaRadio option prop type is missing [#2303]

- packages/docs/src/components/DocsNavigation.vue
- packages/docs/src/page-configs/styles/css-variables/examples/profile.vue
- packages/ui/src/styles/typography/_mixins.scss
Closes: #2304 
Fixes in the more proper way: #2282
> [#2304] fixed problems with buttons in docs for 1.5.0

- packages/ui/src/components/va-radio/VaRadio.vue
- Added PropType to options in vaRadio, now it has 4 types String, Boolean, Object and Number and default value will be null.
- Added type Number to modelValue, as passing any number dataType in options , causing a warning of type mismatch.
> fix:vaRadio option propType and added default null #2303

- packages/ui/src/components/AccessibilityGuide.md
- packages/ui/src/components/va-alert/VaAlert.vue
- packages/ui/src/components/va-chip/VaChip.vue
- packages/ui/src/components/va-collapse/VaCollapse.vue
- packages/ui/src/components/va-data-table/VaDataTable.vue
- packages/ui/src/components/va-icon/VaIcon.vue
- packages/ui/src/components/va-list/VaListItem.vue
- packages/ui/src/components/va-modal/VaModal.vue
- packages/ui/src/components/va-rating/components/VaRatingItem/VaRatingItem.vue
- packages/ui/src/components/va-toast/VaToast.vue
- packages/ui/src/styles/resources/_mixins.scss
Related to: #2349 
Focus-outline for only keyboard selection.
> [#2349] Focus outline only keyboard update

- packages/ui/src/components/va-modal/VaModal.vue
Closes: #2423 
Minor `VaModal` cancel button fix - changed preset (to plain > was also plain before `VaButton` reimplementation).
> [#2423] `VaModal` cancel button preset fix

- packages/docs/src/page-configs/ui-elements/data-table/examples/Sticky.vue
- packages/ui/src/components/va-data-table/VaDataTable.vue
- packages/ui/src/components/va-data-table/_variables.scss
- packages/ui/src/components/va-data-table/hooks/useStylable.ts
> [#2339] Fix `VaDataTable` css variables (for `sticky` and `scrolled` table)

- packages/docs/src/page-configs/ui-elements/data-table/examples/CRUD.vue
> [#2324] Fix `VaDataTable` inputs width in CRUD example

- packages/docs/src/page-configs/ui-elements/button/examples/Behaviour.vue
- packages/docs/src/page-configs/ui-elements/button/examples/WithOutline.vue
- packages/ui/src/components/va-button-group/VaButtonGroup.vue
- packages/ui/src/components/va-button-group/_variables.scss
- packages/ui/src/components/va-button/VaButton.vue
- packages/ui/src/components/va-button/hooks/useButtonBackground.ts
- packages/ui/src/components/va-button/hooks/useButtonTextColor.ts
- packages/ui/src/styles/global/reset.scss
`VaButton` background state colors now relies on CSS, not JS. Related minor fixes.
> `VaButton` background color state should rely on CSS, no on JS

- packages/docs/src/locales/en/en.json
- packages/docs/src/locales/ru/ru.json
- packages/docs/src/page-configs/ui-elements/select/examples/Slots.vue
- packages/docs/src/page-configs/ui-elements/select/examples/Tagging.vue
- packages/docs/src/page-configs/ui-elements/select/page-config.ts
- packages/ui/src/components/va-select/VaSelect.vue
Closes: #2243 
->
(was like this before but was broken) ->
> [#2243] tagging state select documentation, minor bugfixes

- packages/ui/src/components/va-date-input/VaDateInput.vue
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-time-input/VaTimeInput.vue
Closes: #2237 
`VaDropdown` props added to `VaSelect`, `VaDatepicker`, `VaTimepicker`.
> [#2237] `VaDropdown` props for `VaSelect`, `VaDatepicker`, `VaTimepicker`

- packages/ui/src/components/va-data-table/VaDataTable.vue
- packages/ui/src/components/va-data-table/hooks/useAnimationName.ts
> Fix `VaDataTable` filtering animation

- packages/ui/src/services/global-config/global-config.ts
- packages/ui/src/utils/merge-deep.ts
- packages/ui/src/utils/tests/merge-deep.spec.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/2460
Fix icons config merge method. For some reason lodash merge trying to merge objects in array and makes it wrong. This is why in https://github.com/epicmaxco/vuestic-ui/issues/2460 for `'mdi-{name}'` object was added class from `'{icon}'` object.
Looks like if lodash merge first objects with name key.
So I made my own merge.
> fix(#2460): merge icons config

- packages/docs/src/assets/main.scss
in-depth problem was that font was applied globally on typography.css include
> fix: broken icons on landing

- packages/ui/src/components/va-input/components/VaInputWrapper/VaInputWrapper.vue
`.va-input-wrapper` need  `flex:1`
and the select component  is correct  and it has `flex:1`
```vue
<div class="grid grid-cols-4 gap-2">
<va-dropdown
:auto-placement="false"
:close-on-content-click="false"
@open.once="onOpen()"
@close="onClose()"
placement="bottom"
v-model="state.showDropDown"
prevent-overflow
:offset="[0, 50]"
>
<template #anchor>
<va-input
:modelValue="shownValue"
:label="props.label"
readonly
class="cursor-pointer"
>
<template #appendInner>
<va-icon name="collections_bookmark" @click.stop="openBookMark()" />
</template>
</va-input>
</template>
</va-dropdown>
</div>
```
> fix(input): add va-input-wrapper flex:1

- packages/ui/src/components/va-alert/useAlertStyles.ts
Related to #2578
- Changed default text color for the outlined alerts.
> fix: change text color for outlined alerts

- packages/docs/src/components/header/components/ColorDropdown.vue
A little fix, that makes things better: displaying the current selected them in the colors dropdown.
<details>
<summary>Screenshots</summary>
</details>
> feat: display current selected theme in the button toggle

- packages/ui/src/services/color-config/plugin/create-color-config-plugin.ts
- packages/ui/src/services/color-config/plugin/index.ts
- packages/ui/src/vuestic-plugin/create-vuestic/create-vuestic-essential.ts
- packages/ui/src/vuestic-plugin/create-vuestic/create-vuestic.ts
Now it works:
```ts
const theme = Boolean(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light'
createApp(App)
.use(createVuestic({
config: {
colors: {
currentPresetName: theme,
}
}
}))
.mount('#app')
```
> fix: currentPresetName in createVuestic does nothing

- packages/ui/src/components/va-select/VaSelect.vue
Close #2644
- Fixed navigation with arrow keys from search input when `searchable` prop is truthy.
> fix: navigation with arrow keys

- packages/ui/src/components/va-modal/VaModal.vue
Closes: #2689 
Reimplemented logic of click-outside-close for `VaModal`. Previous was broken in some cases.
> [#2689] `VaModal` click outside logic fix

- packages/ui/src/components/va-select/VaSelect.demo.vue
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-select/components/VaSelectOption/VaSelectOption.vue
- packages/ui/src/components/va-select/components/VaSelectOption/_variables.scss
- packages/ui/src/components/va-select/components/VaSelectOptionList/VaSelectOptionList.vue
> [#2709] `VaSelect` zero value, disabled options and keyboard navigation fixes

- packages/ui/src/components/va-pagination/VaPagination.vue
Closes: #2737
Changed the way VaPagination input field height is set.
> [#2741] `VaPagination` input height fix

- packages/ui/src/composables/useClientOnly.ts
- packages/ui/src/composables/useDropdown.ts
- packages/ui/src/composables/useEvent.ts
Closes: #2741 
Tested and seems to work as needed:
But better to take a look twice because it's a pretty fundamental thing.
> [#2741] Nuxt 3 hook warning fix

- packages/ui/src/components/va-navbar/VaNavbar.vue
Before fix:
After fix:
- Added computed grid template areas and sizes.
> Navbar gird fixes

- packages/ui/src/components/va-card/VaCard.vue
closes #2827
Prev
Now
No more extra va-card__inner div.
> fix(#2827): remove va-card__inner div from VaCard

- packages/docs/src/page-configs/ui-elements/navbar/examples/Height.vue
- packages/ui/src/components/va-navbar/VaNavbar.vue
- packages/ui/src/components/va-navbar/_variables.scss
I changed navbar height to be defined by padding rather than height so it can expand instead of overflowing and fixed a couple of layout bugs.
> fix: replace navbar static height with paddings, fix: mobile layout

- packages/sandbox/scripts/bundle-analysis.ts
If `ui/dist` doesn't exist, `yarn build:analysis` command at the `sandbox` workspace fails. Let's handle this situation.
> fix: build vuestic from sandbox if it doesn't exist

- packages/ui/src/components/va-data-table/types.ts
Added generic to DataTableColumn to allow for strongly-typed keys when using the interface.
> feat: add optional strong typing to DataTableColumn

- packages/ui/src/components/va-navbar/VaNavbar.vue
> [#2920] `va-navbar` center slot on mobiles fix

- packages/ui/src/components/va-input/VaInput.demo.vue
- packages/ui/src/components/va-input/hooks/useCleave.ts
The mask property from the useCleave() hook had the missing CleaveOptions type which is a valid input type for it
> fix: add CleaveOptions type to mask prop to match real use

- packages/nuxt/src/types.ts
`smart-helpers` type for Nuxt 3 module.
> feat: smart-helpers added to nuxt module types

- packages/ui/src/components/va-badge/VaBadge.vue
- packages/ui/src/components/va-button-dropdown/VaButtonDropdown.vue
- packages/ui/src/components/va-button-group/VaButtonGroup.vue
- packages/ui/src/components/va-button-toggle/VaButtonToggle.vue
- packages/ui/src/components/va-button/VaButton.vue
- packages/ui/src/components/va-navbar/VaNavbar.vue
- packages/ui/src/components/va-scroll-container/VaScrollContainer.vue
> feat: removed deprecated in 1.6.0 props

- packages/docs/modules/page-config/blocks/api/components/api-table.vue
- packages/docs/modules/page-config/blocks/table/index.vue
> docs: make inline text reasonable size

- packages/ui/src/components/va-button/VaButton.vue
- packages/ui/src/components/va-button/_variables.scss
Before: 
After:
Needs a follow up on buttons. And decision if we want to have margins set.
> ui: tmp fix buttons

- packages/docs/modules/vuestic.ts
Hell yeah, found it!
Maybe it is a solution for https://github.com/epicmaxco/vuestic-ui/issues/3046, but it is not directly fixes it. I'll double-check it in new nuxt project.
> fix(#3046): remove vuestic from excluded optimizeDeps

- packages/nuxt/src/runtime/plugin.ts
- packages/ui/src/composables/useRouterLink.ts
- packages/ui/src/services/global-config/global-config.ts
- packages/ui/src/services/global-config/types.ts
> [#3024] `nuxt-link` is now available in vuestic

- packages/docs/components/layout/Sidebar.vue
> feat: remove extra padding

- packages/docs/components/landing/Admin.vue
- packages/docs/components/landing/Header.vue
- packages/docs/components/landing/OpenSource.vue
- packages/docs/components/landing/Preview.vue
- packages/docs/components/landing/SeamlessIntegration.vue
- packages/docs/page-config/introduction/team/components/team.vue
- packages/docs/pages/index.vue
Close #3030 
- According to the MDN docs for the img tag, removed units from `height` and `width` attributes.
- Removed public path from svg path'.
> fix: remove units for height and width attributes; fix svg

- packages/ui/src/components/va-tree-view/VaTreeView.demo.vue
- packages/ui/src/components/va-tree-view/components/VaTreeNode/VaTreeNode.vue
- packages/ui/src/components/va-tree-view/components/VaTreeNode/_variables.scss
(closes #2980 )
When expandNodeBy is "node" you can click on the node itself to expand it.
This is not visible for the end user because the mouse is still the same.
This PR changes the cursor style to `pointer` when expandNodeBy==="node" and it has children (=when it's expandable).
Used a scss variable called --va-tree-node-cursor-type (so the developer could change it)
<details>
`components/va-tree-view/components/VaTreeNode/VaTreeNode.vue`  
```vue
<div class="va-tree-node-content__body" :class="cursorClassComputed">
<slot name="content" v-bind="$props.node">{{ labelComputed }}</slot>
</div>
```
```ts
const cursorClassComputed = useBem('va-tree-node-content', () => ({
cursor: (props.node.hasChildren === true && expandNodeBy === 'node'),
}))
```
`.../VaTreeNode/_variables.scss`  
```scss …
```
> [#2980] VaTreeView expandable node cursor style

- packages/ui/src/components/va-data-table/VaDataTable.vue
> [#3121] default `VaDataTable` wrapper size set to `auto`

- packages/ui/src/components/va-select/VaSelect.vue
> [#3116] tab shift autocomplete behaviour fix

- packages/docs/components/layout/Sidebar.vue
Close #3105
- Refactored active child route detection.
> fix: detect active child route and set class

- packages/ui/src/components/va-select/VaSelect.demo.vue
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-select/components/VaSelectContent/VaSelectContent.vue
> [#3140] autocomplete readonly state fix

- packages/ui/src/components/va-date-input/VaDateInput.vue
- packages/ui/src/components/va-time-input/VaTimeInput.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/3137
> fix(#3137): expose closeOnContentClick prop from dropdown to time and date pickers

- packages/ui/src/components/va-data-table/VaDataTable.vue
- packages/ui/src/components/va-date-input/VaDateInput.vue
- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/components/va-time-input/VaTimeInput.vue
Déjà vu. 
I'm not sure how is that possible to have this issue and what PR caused regression. I also feel like I fixed it already...
closes #3188
> fix(ui): incorrect filtered child props

- packages/ui/src/components/va-modal/VaModal.vue
The overflow scroll set by v-modal will cause a white bar to appear at the bottom of the page.
<details>
```vue
// Your code
```
</details>
> fix: overflow scroll will cause a white area

- packages/ui/src/components/va-stepper/VaStepper.vue
- packages/ui/src/components/va-stepper/VaStepperStepButton.vue
- prevent default behavior for top and bottom arrows
- add focus loop according to [w3](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/) 
> When focus is on a tab element in a horizontal tab list:
Left Arrow: moves focus to the previous tab. If focus is on the first tab, moves focus to the last tab. Optionally, activates the newly focused tab.
Right Arrow: Moves focus to the next tab. If focus is on the last tab element, moves focus to the first tab. Optionally, activates the newly focused tab.
P.S. Stepper behaves as tabs component, so, I decided to use the same pattern
> fix: stepper accessibility navigation

- packages/ui/src/components/va-divider/VaDivider.vue
- packages/ui/src/components/va-divider/_variables.scss
Close #3153
…ers to specify the color of the divider. The color prop is then bound to the CSS border-color property using Vue's v-bind in CSS feature. This enables users to dynamically change the divider color using the color prop.
<details>
```vue
// Your code
```
</details>
> Add color prop to VaDivider component and bind it to CSS border color

- packages/docs/modules/page-config/blocks/shared/code/CodeView.vue
- Fixed missing highlight.js styles.
> fix: add single root instance to bind colors by v-bind at styles

- packages/docs/page-config/ui-elements/button-dropdown/examples/Split.vue
close #3314 
- Allow wrapping of split button dropdown examples from the docs on mobile view.
- Use tailwind classes instead of inline-styles.
</details>
> fix(docs): Add flex-wrap for Split example on button dropdown

- packages/ui/build/plugins/append-component-css.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/3296
Fix relative build path while building on windows machine.
From `import '..\..\../Modal.css' to `import '../../../Modal.css'`
> fix(#3296): append css wrong paths on windows

- packages/ui/src/components/va-modal/hooks/useModal.ts
- packages/ui/src/components/va-modal/types.ts
- packages/ui/src/components/va-toast/hooks/useToast.ts
- packages/ui/src/services/current-app.ts
- packages/ui/src/services/global-config/global-config.ts
- packages/ui/src/utils/component-options/types.ts
closes #3336 
This PR allows composables that using useGlobalConfig to be able to be executed ouside setup context. For example
```
const toast = useToast()
axios.interceptor((err) => {
if (err) {
toast .init('Error!')
}
})
```
> Fix#3336/allow using composables outside setup context

- packages/docs/composables/useTheme.ts
- packages/docs/page-config/styles/colors/components/theme.vue
close #3375 
<details>
</details>
> [#3375] Unexpected theme change on Colors page

- packages/docs/components/AlgoliaSearch.vue
- packages/docs/components/landing/Footer.vue
- packages/docs/components/layout/Header.vue
- packages/docs/components/layout/header/ThemeSwitch.vue
- packages/docs/layouts/default.vue
- packages/docs/translations/en.json
close #3380 
<details>
https://user-images.githubusercontent.com/55198465/235128305-7a8ecbc3-7385-4dd6-a672-7bff5a6a081b.mov
</details>
> [#3380] Add menu button in docs navbar for mobile

- packages/docs/page-config/ui-elements/tabs/examples/Color.vue
- packages/docs/page-config/ui-elements/tabs/examples/Pagination.vue
- packages/docs/page-config/ui-elements/tabs/index.ts
- packages/ui/src/components/va-tabs/VaTabs.demo.vue
- packages/ui/src/components/va-tabs/VaTabs.vue
> `Va-Tabs` flex direction

- packages/docs/pages/index.vue
> Remove landing banner

- packages/ui/src/components/va-tabs/VaTabs.demo.vue
- packages/ui/src/components/va-tabs/VaTabs.vue
close #3343 
<details>
<summary>screenshot</summary>
- test project (vue-cli project initializer)
https://user-images.githubusercontent.com/55198465/233650842-076b364d-ec9b-4ff8-8fdb-f2f6cdc092d8.mov
</details>
> [#3343] ResizeObserver error in `VaTabs`

- packages/ui/src/composables/useColors.ts
closes #3392
A setter was added to the computed property `currentPresetName` in `packages/ui/src/composables/useColors.ts`.
This setter assigns a new string value to the `currentPresetName` property of `globalConfig.value.colors`.
<details>
```ts
const currentPresetName = computed<string>({
get: () => globalConfig.value.colors!.currentPresetName,
set: (v:string) => { globalConfig.value.colors!.currentPresetName = v },
})
```
</details>
> feat#3392: make currentPresetName a writable computed

- package.json
- packages/docs/components/HeaderBanner.vue
- packages/docs/composables/useDocsScroll.ts
- packages/docs/layouts/default.vue
- packages/docs/layouts/landing.vue
- packages/docs/modules/page-config/runtime/usePageConfig.ts
- packages/docs/nuxt.config.ts
- packages/docs/package.json
- packages/docs/page-config/extensions/unocss/translation/en.json
- packages/docs/page-config/extensions/unocss/translation/ru.json
- packages/docs/page-config/getting-started/ssr-guide/index.ts
- packages/docs/pages/404.vue
- packages/docs/pages/[page-config-category]/[page].vue
- packages/nuxt/src/runtime/plugin.ts
- packages/ui/src/composables/useColors.ts
- packages/ui/src/services/color/plugin/create-color-config-plugin.ts
- packages/ui/src/services/global-config/global-config.ts
- packages/ui/src/services/global-config/plugin/index.ts
Now theme switcher work as expected in SSG, so we can switch our docs to SSG.
> fix(docs): fix theme switch on SSG

- packages/ui/src/components/va-skeleton/VaSkeleton.vue
- packages/ui/src/composables/useHover.ts
- packages/ui/src/composables/useLongPress.ts
- packages/ui/src/composables/usePressed.ts
It is super minor, but this is all I found...
> fix: remove potential memory leaks

- packages/docs/modules/page-config/blocks/api/component-parser/index.ts
- packages/docs/modules/page-config/blocks/api/index.ts
- packages/docs/modules/page-config/blocks/api/transform.ts
> fix(docs): fix api table event names render

- packages/docs/modules/page-config/blocks/file-structure/index.vue
- packages/docs/page-config/contribution/structure/index.ts
- packages/docs/page-config/navigationRoutes.ts
- packages/docs/translations/en.json
> docs: structure contribution docs

- packages/docs/modules/banner/module.ts
closes #3368
Removed throwing error due to the inability to launch the documentation locally.
> fix(docs): banner module railway .env error

- packages/docs/modules/page-config/blocks/subtitle/index.vue
- packages/docs/modules/page-config/blocks/title/index.vue
closes #3486
I changed the `title` and `sub-title` styles to look different on mobile resolution.
> fix: change title and subtitle styles to look different on mobile resolution

- packages/ui/src/components/va-sidebar/VaSidebar.demo.vue
- packages/ui/src/components/va-sidebar/VaSidebar.vue
There is new prop in Sidebar which is called `close-on-click-outside` (false by default). Demo was added.
close: [#3390](https://github.com/epicmaxco/vuestic-ui/issues/3390)
<details>
```vue
// Your code
```
</details>
> Automatically close sidebar when clicking outside of sidebar

- packages/ui/src/components/va-select/VaSelect.vue
- packages/ui/src/composables/useFocusDeep.ts
- packages/ui/src/composables/useFocusedElement.ts
closes #3488 
Now when shift tab is pressed in select with focused clear icon it correctly moves to input, not clear icon.
And also now input field is focused after dropdown is closed.
> Fix#3488/focus clear icon

- packages/docs/modules/page-config/blocks/api/common-description.ts
- packages/docs/modules/page-config/blocks/api/component-parser/index.ts
- packages/docs/modules/page-config/blocks/api/components/ApiDocs.vue
- packages/docs/modules/page-config/blocks/api/index.vue
- packages/docs/modules/page-config/blocks/api/types.ts
- yarn.lock
After translations removal all descriptions disappeared. I tried to fix it, but typing is somewhat broken with a number of loose ends.
So @m0ksem maybe you have a context to finish this one without much of a trouble?
That's mission critical for release!
Note:
Here we define meta as an object, but we get array in the prop!
> fix: props descriptions

- packages/docs/components/AlgoliaSearch.vue
Disable algolia personalization
Disable algolia personalisation to prevent showing old links in from the local storage
> feat(docs): disable algolia personalization

- packages/docs/components/layout/Sidebar.vue
- packages/docs/page-config/navigationRoutes.ts
- packages/docs/page-config/ui-elements/accordion/index.ts
- packages/docs/utils/navigation/badge.ts
closes #3528 
closes https://github.com/epicmaxco/vuestic-ui/issues/3546
> feat: automated display of badges

- packages/docs/page-config/ui-elements/alert/index.ts
- packages/ui/src/components/va-alert/VaAlert.vue
Improve accessibility on `VaAlert`, and add docs for it.
Fixes #3231
I am not very sure this pr is a breaking change, is it?
> improve accessiblity of `VaAlert` component

- packages/ui/src/components/va-radio/VaRadio.vue
close #3550 
I removed attribute styles from: label, icon, icon background, input, dot.
Instead, I added this styles to css by v-bind.
> fix: move VaRadio element attribute styles to css v-bind

- packages/ui/src/components/va-input/VaInput.vue
- packages/ui/src/components/va-time-input/VaTimeInput.vue
closes #3551
**The problem was that:** `VaIcon` was imported as a whole component in `VaInput` and `VaTimeInput`, so `VaIcon` used the default size configuration for components, where the **"small"** size is `32px`.
I changed the import to correct form and now `VaIcon` use `ConfigTransport`.
Now the "small" size of the icon is `16px`, as it should be.
> fix: change VaIcon import to get right icon size config

- packages/ui/package.json
Adds a "types" field to the `exports` block in package.json to allow TypeScript's Node16 resolution to work properly.
Without it, TypeScript throws this error:
```
Could not find a declaration file for module 'vuestic-ui'. '/workspace/node_modules/vuestic-ui/dist/es/main.js' implicitly has an 'any' type.
There are types at '/workspace/node_modules/vuestic-ui/dist/types/main.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vuestic-ui' library may need to update its package.json or typings
```
<details>
```vue
// Your code
```
</details>
> fix: node 16 module resolution error

- packages/docs/page-config/ui-elements/toast/index.ts
- packages/ui/src/components/va-toast/VaToast.vue
- packages/ui/src/utils/types/prop-type.ts
Improve accessibility of component `VaToast`
Fixes #3287.
> Improve accessibility of component `VaToast`

- packages/docs/config/vuestic-config.ts
closes #3662 
predefined `teleport: 'body'` makes each `<va-dropdown/>` to be atached to `<body></body>` regardless of whether teleport was defined or not, by removing this line, we will fix all the strange behavior with overflow.
> fix#3662/VaDropdown overflow bug

- packages/docs/page-config/ui-elements/progress-bar/index.ts
Add accessibility docs for `VaProgressBar`
Fixes #3255.
> docs: add accessibility docs for progress-bar

- packages/docs/components/landing/Footer.vue
closes #3601
I chose a very simple approach to privacy policy - just add links to headers.
There are ways to improve it (add consent banner etc), but other ui solutions don't do it. It will also be harmful for user experience.
Links lead to iubenda - a site where said policies for each tool used (analytics, cdn etc) are being regularly updated, so we won't need to follow these up on our own.
> feat: add privacy policy

- packages/docs/page-config/ui-elements/accordion/examples/Menu.vue
The text of `Menu` example of `accordion` is black in dark mode, this pr changed it to show white.
I currently don't know what part of `select` is wrong, waiting for response from issue maker to respond.
Fixes #3604.
> fix: make text white for examples of `accordion` and `select` in dark mode

- packages/docs/page-config/ui-elements/progress-bar/index.ts
- packages/docs/page-config/ui-elements/progress-circle/index.ts
Add accessibility docs for `VaProgressCircle`, which fixes #3256.
Fix typo in docs of `VaProgressBar`.
> Add accessibility docs for `VaProgressCircle`, and fix typo of docs in `VaProgressBar`

- packages/nuxt/package.json
- packages/nuxt/src/composables/use-config-file.ts
- packages/nuxt/src/module.ts
- yarn.lock
closes https://github.com/epicmaxco/vuestic-ui/issues/3746
Since https://github.com/nuxt/nuxt/pull/19530, we have a built-in way to watch files + restart Nuxt when they change. This means we don't need to register additional watchers in modules.
Spotted the issue in https://github.com/nuxt/nuxt/issues/22844. The watcher should probably have been set to be closed when nuxt closed (something like `nuxt.hook('close', () => watcher.close())`. Nevertheless, it's likely a bug we need to fix in nuxt/cli.
However, this PR works around the issue and also should improve performance in vuestic/nuxt by reducing watchers required.
> fix(nuxt): use built-in `watch` option to restart nuxt

- packages/create-vuestic/src/composables/useFiles.ts
- packages/create-vuestic/src/composables/usePackageJson.ts
- packages/create-vuestic/src/composables/useVuesticConfig/configDefault.ts
- packages/create-vuestic/src/composables/useVuesticConfig/configTreeShaking.ts
- packages/create-vuestic/src/generators/create-nuxt.ts
- packages/create-vuestic/src/generators/create-vue.ts
- packages/create-vuestic/src/index.ts
- packages/create-vuestic/src/prompts.ts
- packages/create-vuestic/src/steps/2.1.addAgGrid.ts
- packages/create-vuestic/src/steps/2.2.addTailwind.ts
- packages/create-vuestic/src/steps/2.addVuestic/insert-nuxt-module.ts
- packages/create-vuestic/src/steps/2.addVuestic/nuxt-app.ts
- packages/create-vuestic/src/steps/2.addVuestic/vue-app.ts
- packages/create-vuestic/src/steps/4.installDeps.ts
- packages/create-vuestic/src/utils/node-version.ts
- packages/create-vuestic/src/versions.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/3717
closes #3696
> feat(create-vuestic): tailwind option

- packages/ui/src/components/va-modal/VaModal.demo.vue
- packages/ui/src/components/va-modal/VaModal.vue
- packages/ui/src/components/va-modal/_variables.scss
Added a props `isShowNestedOverlay` props by default, this props is set to 'false'. When you enable it for a modal, an overlay will be displayed for that modal and will not get removed in any case.
Discussion : #1870
> fix: added props based support for nested overlay

- packages/ui/src/components/va-inner-loading/VaInnerLoading.vue
In VaInnerLoading component the icon name autorenew was changed to va-loading.
closes #3830 
<details>
```vue
- icon: { type: String, default: 'autorenew' },
+ icon: { type: String, default: 'va-loading' },
```
</details>
> fix: Change icon name in VaInnerLoading

- packages/ui/src/components/va-avatar-group/VaAvatarGroup.stories.ts
- packages/ui/src/components/va-avatar-group/VaAvatarGroup.vue
partial  #3879 
However this PR does not fix the storybook edits ( #3800 ) that described the issue
> fix(va-avatar-group): render avatar group with rest count based on max prop

- packages/ui/src/components/va-input-wrapper/VaInputWrapper.demo.vue
- packages/ui/src/components/va-input-wrapper/VaInputWrapper.vue
- packages/ui/src/components/va-textarea/VaTextarea.stories.ts
- packages/ui/src/components/va-textarea/VaTextarea.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/3901
Textarea:
Input:
> fix(textarea): resize with height

- packages/ui/src/components/va-button/VaButton.demo.vue
close #3930
After reviewing the code base and attempting to create JavaScript logic in order to allow padding for the presence of both icon and icon right inside of a Vabutton component, I realized a simpler fix. I read over the documentation and saw that the Vabutton presets prop was able to allow the button to have both icons with padding as long as the preset was set to "primary" instead of "plain". In the end, this is all I changed in the demo file. When creating future Vabuttons it could be noted that if the user wants to have 2 icons they must use the primary preset and not the plain preset.
<details>
```vue
// Your code
lines 175-177 in Vabutton.demo.vue
<va-button border-color="primary" preset="primary" icon="create" iconRight="clear">
Secondary
</va-button>
```
</details>
- [x ] …
> fix/3930 Vabutton now has padding with 2 icons as well as 1 (preset = primary)

- packages/ui/src/components/va-collapse/VaCollapse.stories.ts
- packages/ui/src/components/va-collapse/VaCollapse.vue
closes #3931 
Fix overflow behaviour of VaCollapse
The VaCollapse body wrapper had a overflow hidden which would have been causing the extra content to be clipped. Changed the overflow behaviour to auto so that users will get a scrollbar when the size exceeds more than allotted.
<details>
```vue
&__body-wrapper {
transition: var(--va-collapse-body-wrapper-transition);
overflow: scroll;   // Changed this to scroll from hidden
&--bordered {
border-bottom: 1px solid var(--va-background-border);
.va-collapse--colored-header:not(.va-collapse--expanded) & {
border-bottom: none;
}
.va-collapse--colored-body.va-collapse--expanded & {
border-bottom: none;
}
}
}
```
</details>
> Fix: Overflow behaviour of VaCollapse

- packages/ui/src/components/va-time-input/VaTimeInput.vue
- packages/ui/src/components/va-time-input/_variables.scss
- packages/ui/src/components/va-tree-view/hooks/useTreeView.ts
close #3922
Changed the onClick handler of `va-input-wrapper`
> Inconsistent behavior for VaTimeInput right icon #3922

- packages/ui/src/components/va-textarea/VaTextarea.vue
Fix #3958
Checks that the computedValue exists before trying to access the toString function
<details>
```vue
const rows = valueComputed.value ? valueComputed.value.toString().split('\n').length : 1
```
</details>
- [ x] Bug fix (non-breaking change which fixes an issue)
> Fix error with null values in VaTextarea.vue

- packages/ui/src/styles/typography/typography.scss
Remove line-height at `.va-typography-block` so as not to overrides line-height in va-h(1, 2, ... 6).
Fixing #3962.
> fix: Make line-height work in title work again

- packages/docs/modules/page-config/blocks/api/common-description.ts
- packages/docs/page-config/navigationRoutes.ts
- packages/docs/page-config/ui-elements/data-table/api-description.ts
- packages/docs/page-config/ui-elements/data-table/api-options.ts
Updated docs for DataTable to include a event description for columnSorted. Also added the `updated` badge for Stepper and DataTable. Added missing info for Select `update:modelValue` event.
> Docs update

- packages/ui/src/components/va-avatar/VaAvatar.stories.ts
- packages/ui/src/components/va-avatar/VaAvatar.vue
closes https://github.com/epicmaxco/vuestic-ui/issues/3990
```ts
export const FallbackTextNoSrc = () => ({
components: { VaAvatar },
template: '<VaAvatar fallbackText="Text" />',
})
```
> fix(#3990): use fallback if no src

- packages/ui/src/components/va-counter/VaCounter.vue
This is a PR to fix [#3999](https://github.com/epicmaxco/vuestic-ui/issues/3999)
This PR isolates `readonly` from `disabled` attribute, now the computed properties `isDecreaseActionDisabled` &  `isIncreaseActionDisabled` are only checking if disabled and min o max value is reached.
`readonly` is appended in `increaseIconProps` and `decreaseIconProps` directly from the props.
> fix: va-counter isolate readonly attribute from disabled

- packages/ui/src/components/va-breadcrumbs/VaBreadcrumbs.vue
This PR closes #4000 
Fixes the active color on non-active breadcrumbs
> Made only the active breadcrumb take active color

- packages/docs/modules/banner/runtime/banner.ts
- packages/docs/modules/google-analytics/runtime/plugin.ts
- packages/nuxt/nuxt.shim.d.ts
- packages/nuxt/src/runtime/plugin.ts
This is a DX improvement when developing - we can avoid loading the entire barrel file at `#app` by using the new granular imports merged in https://github.com/nuxt/nuxt/pull/23951.
> fix: import nuxt composables from #imports

- packages/docs/page-config/ui-elements/select/index.ts
This addresses an issue we faced where using text-by caused our select to start display at the bottom of the list instead of the top.
> Added documentation that addresses issues when using text-by.

- packages/ui/src/components/va-inner-loading/VaInnerLoading.demo.vue
- packages/ui/src/components/va-inner-loading/VaInnerLoading.vue
This PR [#4003](https://github.com/epicmaxco/vuestic-ui/issues/4003) adds custom loader components on `va-inner-loading` via slot.
Also it adds a new example in storybook for custom loader. `Default` and `custom` loaders share the same loading trigger button. 
The name of the slot is `loading` as `vaInfiniteScroll` also contains a loader slot and it is named `loading`. For consistency, I´ve chosen the same name. Personally, I think a more explicit name would be `loader` as it is a loader component what we will pass through the slot. I would use `loading` more for state cases.
> fix(#4003): add custom loader component via slot

- packages/ui/src/components/va-sidebar/VaSidebar.vue
Fixing this kind of isse:
https://github.com/epicmaxco/vuestic-ui/assets/23530004/5d65de23-a127-4b1b-9e04-1e2f6e2c7bf6
Need to check if it doesn't introduce other issues.
> fix(sidebar): jump in animation

- packages/ui/.storybook/vuestic-config/demo-icon-aliases.ts
- packages/ui/package.json
- packages/ui/src/components/va-accordion/VaAccordion.stories.ts
- packages/ui/src/components/va-affix/VaAffix.stories.ts
- packages/ui/src/components/va-alert/VaAlert.stories.ts
- packages/ui/src/components/va-app-bar/VaAppBar.stories.ts
- packages/ui/src/components/va-backtop/VaBacktop.stories.ts
- packages/ui/src/components/va-carousel/VaCarousel.stories.ts
- packages/ui/src/components/va-counter/VaCounter.stories.ts
- packages/ui/src/components/va-data-table/VaDataTable.new.demo.vue
- packages/ui/src/components/va-date-input/VaDateInput.demo.vue
- packages/ui/src/components/va-date-input/types.ts
- packages/ui/src/components/va-date-picker/VaDatePicker.demo.vue
- packages/ui/src/components/va-form/VaForm.stories.ts
- packages/ui/src/components/va-input/VaInput.demo.vue
- packages/ui/src/components/va-select/VaSelect.stories.ts
- packages/ui/src/components/va-stepper/VaStepper.demo.vue
- packages/ui/src/components/va-stepper/types.ts
- packages/ui/src/components/va-switch/VaSwitch.stories.ts
- packages/ui/src/components/va-tree-view/VaTreeView.stories.ts
- packages/ui/src/components/va-tree-view/VaTreeViewKeyboardNavigation.stories.ts
- packages/ui/src/components/va-value/VaValue.stories.ts
- packages/ui/src/components/va-viewer/VaViewer.stories.ts
- packages/ui/src/components/va-virtual-scroller/VaVirtualScroller.stories.ts
- packages/ui/src/composables/useElementBackground.stories.ts
- packages/ui/src/services/color/ColorCSSVariablesUpdater.stories.ts
- packages/ui/tsconfig.build.json
- packages/ui/tsconfig.json
Closes: #4042
Setup proper type checking in stories and eliminated preexisting TS errors
- Fixed problem that importing .vue files in stories raised TS error "Cannot find module or its corresponding type declarations." via including *.stories.ts files in tsconfig.json #4042
- Added separate tsconfig.build.json to pass to `build:types` so that stories still don't end up in generated type declarations
- Added `typecheck` script for type checking all project code including stories and hooked in precommit stage
- Fixed more TS errors that popped up on `typecheck`, namely:
- Typed all stories with interactions `play` with `StoryFn`
- Added "@testing-library/jest-dom" types to tsconfig to have jest-dom assertions methods on expect properly typed
> Stories typechecking fix (#4042)

- packages/ui/src/components/va-select/components/VaSelectContent/VaSelectContent.vue
> fix(VaSelectContent #4047): set input value on mount

- packages/ui/src/components/va-carousel/VaCarousel.vue
- packages/ui/src/components/va-form/VaForm.stories.ts
- packages/ui/src/components/va-input/VaInput.stories.ts
- packages/ui/src/components/va-input/VaInput.vue
- packages/ui/src/components/va-select/VaSelect.stories.ts
- packages/ui/src/components/va-select/hooks/useAutocomplete.ts
- packages/ui/src/components/va-stepper/VaStepper.vue
- packages/ui/src/composables/tests/useStateful.spec.ts
- packages/ui/src/composables/tests/useUserProvidedProp.spec.ts
- packages/ui/src/composables/useSelectable.ts
- packages/ui/src/composables/useStateful.ts
- packages/ui/src/composables/useUserProvidedProp.ts
> I see how I can create form data with a new form, but how would I prepopulate data? 
> 
> I cant do myForm.formData.value = {} as SomeType, because .value is readonly. Is formData only able to used to create records and not edit them? I was wondering about this approach because I'm experiencing issues with clearing a form by setting the v-model object to empty or null which immediately fires the form validation. This happens wether or not I call reset() or try and use resetValidation() to clear messages.
Fix this example: https://ui-experimental.vuestic.dev/play#eNp9Ustu2zAQ/BVCFydAZAHJzVACNE0CpGjdoi1y4oWWVzYTvsCHY8PQv2dJWpLzgC+SODszO1ztvvhmzHQToJgVtWssN5448MEQwdTqmhbe0eKGKkK4NNp6sifBwYO2knSktVqSCYqd500Z+ISqyGy0cpHYIuuOeYbM6151NpG7+J6cU1VXuSHa48GDNIJ5SM3qJ5Z6WGgxQ5bQgjiPhDYI0gjmXKwsykvSC …
> fix(stateful): use provided prop instead of default value if provided.

- packages/ui/src/components/va-data-table/VaDataTable.stories.ts
- packages/ui/src/components/va-data-table/hooks/useSortable.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/4048
> fix(data-table#4048): disable-client-side-sorting prop

- packages/ui/src/components/va-data-table/VaDataTable.stories.ts
- packages/ui/src/components/va-data-table/VaDataTable.vue
- packages/ui/src/components/va-menu-list/VaMenuList.vue
> fix(#4074): correct striped with expandable row

- packages/ui/src/components/va-input/VaInput.stories.ts
- packages/ui/src/components/va-input/VaInput.vue
> fix(#3996): set input value on input event according to model value

- packages/ui/src/components/va-collapse/VaCollapse.stories.ts
- packages/ui/src/components/va-collapse/VaCollapse.vue
> fix(#4068): use text-color prop in collapse

- packages/ui/src/composables/useAppContext.ts
- packages/ui/src/composables/useRouterLink.ts
closes #4132 
Must be available in 1.8.4
> fix(#4132): remove getCurrentInstance from computed

- packages/docs/page-config/getting-started/installation/index.ts
- packages/sandbox/package.json
- packages/ui/package.json
- yarn.lock
This pull request closes #4123  by updating the yarn.lock file to be compatible with Node.js version 20.
The project currently relies on older modules that are not compatible with the latest Node.js LTS version, 20.10.0. To resolve this, I have regenerated the yarn.lock file. By deleting the existing lock file and running yarn install, a new lock file has been generated, ensuring support for Node.js 20.
</details>
> Update yarn.lock for Node.js 20 Compatibility

- packages/ui/src/components/va-virtual-scroller/VaVirtualScroller.vue
Removing the generic default should generate a filename without URL encoded values in the package. As it the generic default is unnecessary for its use anyway. This does not solve the core naming issue (as probably the generic should not be part of the name in any scenario when packing) this should solve the specific issue mentioned here:
https://github.com/epicmaxco/vuestic-ui/issues/4156
> [VaVirtualScroller]: Remove unnecessary default type

- packages/docs/page-config/ui-elements/layout/index.ts
In section [https://ui.vuestic.dev/ui-elements/layout#mobile-friendly](url)
fixed the URL of the hyperlink _useBreakpoint_, that leads to localhost:3000
<details>
```vue
description: 'It is recommended to make `left` and `right` areas absolute on mobile devices. You can use `absolute` prop to do it in pair with [useBreakpoint](/services/breakpoints)[[target=_blank]] composable.',
```
</details>
> fix(docs): fixed hyperlink url in layout page

- packages/docs/page-config/services/colors-config/examples/change-colors.vue
- packages/docs/page-config/styles/colors/examples/ThemeSwitcher.vue
- packages/docs/page-config/ui-elements/config/examples/Colors.vue
- packages/docs/page-config/ui-elements/config/examples/Components.vue
- packages/docs/page-config/ui-elements/data-table/examples/AdvancedFiltering.vue
- packages/docs/page-config/ui-elements/form/examples/Default.vue
- packages/docs/page-config/ui-elements/form/examples/HideErrors.vue
- packages/docs/page-config/ui-elements/layout/examples/Absolute.vue
- packages/docs/page-config/ui-elements/layout/examples/Fixed.vue
- packages/docs/page-config/ui-elements/layout/examples/MobileFriendly.vue
- packages/docs/page-config/ui-elements/layout/examples/Order.vue
- packages/docs/page-config/ui-elements/value/examples/WithInputs.vue
There is some places in docs where examples in playground cant be run because of missing imports, like 'ref' or composables from 'vuestic-ui'. Looked through all the places and added necessary imports 
<details>
```vue
import { * } from 'vue'; 
import { * } from 'vuestic-ui';
```
</details>
> fix(docs):added missing imports in examples

- packages/ui/src/components/va-form/VaForm.stories.ts
- packages/ui/src/components/va-input/VaInput.stories.ts
- packages/ui/src/components/va-input/VaInput.vue
- packages/ui/src/components/va-stepper/VaStepper.vue
- packages/ui/src/composables/useForm/useFormParent.ts
- packages/ui/src/composables/useValidation.ts
The goal is to make validation in vuestic similar to Angular Forms. (see https://angular.io/guide/form-validation#cross-field-validation).
Reactive rules: if rule depends on reactive state and this state is changed rule must be recomputed.
Right now, validation is recalculated if any rule reactive state is updated, all rules are recalculated.
Validation triggers once per vue tick now, so even if a lot of validation triggered is called, validation will be calculated once.
> feat: reactive rules 

- packages/ui/src/components/va-counter/VaCounter.vue
- packages/ui/src/components/va-counter/hooks/useCounterPropsValidation.ts
- packages/ui/src/components/va-data-table/VaDataTable.vue
- packages/ui/src/components/va-progress-bar/VaProgressBar.vue
- packages/ui/src/components/va-progress-circle/VaProgressCircle.vue
- packages/ui/src/components/va-rating/VaRating.vue
- packages/ui/src/components/va-scrollbar/VaScrollbar.vue
- packages/ui/src/components/va-stepper/VaStepperControls.vue
<details>
```vue
// Your code
```
</details>
> number props accept strings

- packages/nuxt/src/module.ts
Vuestic's option "css" accepts an array of  css modules as an input. 
The default value of that option is ['smart-helpers', 'typography']. 
The problem is that nuxt won't override the default array with an array passed by user (it's a known issue). Instaed two arrays will be concatenated. 
For example, I want to use only a typography css module, so I set the css option to ['typography'].
In that case I expect the css option to be ['typography'] according to documentations.
Instead i have this:
> fix:Workaround for using arrays as default options in nuxt module closes #4213

- packages/ui/src/components/va-select/VaSelect.vue
closed #4198 
Objects should always retain their references because the default method of checking object equality relies on comparing object references when the value of 'valueBy' does not exist, thereby comparing two object references.
> fix(VaSelect): fix `objects-as-options` cannot set status correctly(#4198)

- packages/ui/src/components/va-data-table/VaDataTable.vue
The footerPrepend and footerAppend slots should be usable independently from the footer slot.
closes #4160
> fix(VaDataTable): fix slot about footer doesn't work as expected(#4160)

- packages/ui/src/components/va-color-input/VaColorInput.vue
…o bottom right
- Edge
- Chrome
https://github.com/epicmaxco/vuestic-ui/issues/3454
<details>
```vue
<style lang="scss">
.va-color-input {
display: flex;
align-items: center !important;
position: relative;
.form-group {
margin-bottom: 0;
}
&__input {
margin-bottom: 0;
min-width: 5.6rem;
&__pointer {
cursor: pointer;
}
}
&__hidden-input {
visibility: hidden;
width: 0;
height: 0;
overflow: hidden;
position: absolute;
pointer-events: none;
bottom: 0;
}
// Currently I could only determine the width of the color modal on Edge and Chrome
@supports (-ms-ime-align:auto) {
/* Edge specific */
&__hidden-input {
right: 14.7rem; // For Edge and Chrome the color picker modal size is 14.7rem
}
}
@media screen and (-webkit-min-device-pixel-ratio: 0) {
/* Chrome specific */
&__hidden-input {
right: …
```
> bug: updated the color-input pop-up positon for chrome and edge browser to bottom right

- packages/ui/src/components/va-modal/VaModal.stories.ts
<details>
https://github.com/epicmaxco/vuestic-ui/issues/3995
```vue
export const CloseButton: StoryFn = () => ({
components: { VaModal },
data () {
return {
show: false,
}
},
template: `
<button @click="show = true">
show modal
</button>
<VaModal :model-value="show" @cancel="show = false" :close-button="true">
Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.
</VaModal>
`,
})
```
</details>
> bug: Fix modal close button storybook example

- packages/ui/src/components/va-dropdown/VaDropdown.vue
- packages/ui/src/components/va-popover/VaPopover.demo.vue
- packages/ui/src/components/va-popover/VaPopover.vue
Add content-class properties to the VaPopover component to enable a method for changing the popover content on the body element.
closed #4182 
<details>
```vue
<va-popover
message="Popover Content Class with Large padding"
class="mr-6"
content-class="demo-popper-content-class"
>
<va-button>Content Class</va-button>
</va-popover>
```
</details>
> feat(VaPopper): support content-class attribute(#4182)

- packages/ui/src/components/va-sidebar/VaSidebar.demo.vue
- packages/ui/src/components/va-sidebar/VaSidebarItem/VaSidebarItem.vue
- packages/ui/src/composables/useHover.ts
- added disabled prop to side bar item
- Added a disabled prop to the sidebar item
- Added disabled style when the item is disabled
- Added demo example for disabled side bar item
<details>
```vue
<template>
<component
ref="rootElement"
class="va-sidebar__item va-sidebar-item"
tabindex="0"
:class="{
'va-sidebar-item--active': $props.active,
'va-sidebar-item--disabled': $props.disabled,
}"
:style="computedStyle"
:is="tagComputed"
v-bind="linkAttributesComputed"
v-on="keyboardFocusListeners"
>
<slot />
</component>
</template>
const props = defineProps({
// removed to keep PR short
disabled: { type: Boolean, default: false },
})
<style lang="scss">
@import "../variables";
@import "../../../styles/resources";
.va-sidebar-item {
// removed to keep PR short
&--disabled {
opacity: 0.5;
cursor: …
```
> Added Disabled Prop to Sidebar Item

- packages/ui/src/components/va-data-table/VaDataTable.vue
used background color and opacity without mixin
closes #4236 
<details>
```vue
&.striped {
.va-data-table__table-tbody {
.va-data-table__table-tr {
&:nth-of-type(2n) {
&:not(.selected) {
td {
// Position relative doesn't work on tr in Safari
position: relative;
background: var(--va-data-table-striped-tr-background-color);
opacity: var(--va-data-table-striped-tr-opacity);
}
}
}
}
}
}
```
</details>
> fix(VaDataTable): use background color and opacity without mixin

- packages/ui/src/components/va-select/components/VaSelectContent/VaSelectContent.vue
https://github.com/epicmaxco/vuestic-ui/issues/4046
<details>
```vue
<style lang="scss">
@import '../../variables';
.va-select-content {
display: flex;
flex-wrap: wrap;
flex: 1;
&__autocomplete {
flex: 1 1;
margin-left: 0.25rem;
&:first-child {
margin-left: 0;
}
}
&__placeholder {
overflow: hidden !important;
flex: 1;
line-height: normal;
color: var(--va-input-placeholder-text-color);
text-overflow: ellipsis !important;
white-space: nowrap !important;
}
&__separator {
white-space: pre;
}
&__state-icon {
margin-left: var(--va-select-state-icon-margin-left);
}
}
</style>
```
</details>
> bug: added flex grow to autocomplete input wrapper

- packages/docs/.stylelintrc.js
- packages/ui/.stylelintrc.js
- packages/ui/src/components/va-modal/VaModal.demo.vue
- packages/ui/src/composables/useTeleported.ts
The modal element is assigned data-v-data-v-[hash] attribute so that scoped classes are not applied which is a bug
> Fixed scoped class on modal

- packages/docs/page-config/services/i18n/code/runtime.ts
- packages/docs/page-config/services/i18n/code/vue-i18n-runtime.ts
- packages/docs/page-config/services/i18n/index.ts
- packages/ui/src/composables/useTranslation.ts
closes #4244
Implemented feature and updated docs
> Try to resolve $t from vue global properties (#4244)

- packages/ui/src/components/va-slider/VaSlider.vue
#4291 
<details>
```vue
// Your code
const processedStyles = computed(() => {
if (Array.isArray(val.value)) {
const val0 = ((val.value[0] - minComputed.value) / (maxComputed.value - minComputed.value)) * 100
const val1 = ((val.value[1] - minComputed.value) / (maxComputed.value - minComputed.value)) * 100
return {
[pinPositionStyle.value]: `${val0}%`,
[trackSizeStyle.value]: `${val1 - val0}%`,
backgroundColor: getColor(props.color),
visibility: props.showTrack ? 'visible' : 'hidden',
} as CSSProperties
} else {
const val0 = ((val.value - minComputed.value) / (maxComputed.value - minComputed.value)) * 100
return {
[trackSizeStyle.value]: `${val0 > 100 ? 100 : val0}%`,
backgroundColor: getColor(props.color),
visibility: props.showTrack ? 'visible' : 'hidden',
} as CSSProperties
}
})
const …
```
> fix(VaSlider): prevent slider for overflowing from track

- packages/ui/src/components/va-input-wrapper/components/VaInputLabel.vue
- packages/ui/src/components/va-switch/VaSwitch.demo.vue
- packages/ui/src/components/va-switch/VaSwitch.vue
Closes #4294 
Fixes alignment issue with `VaSwitch` if label is left aligned
Fixes `VaInputLabel` required mark size to not enlarge container size
> Fix#4294/input required mark and switch left label

- packages/ui/src/components/va-input/VaInput.vue
- packages/ui/src/components/va-input/hooks/useCleave.ts
Closes #3859
Allows to pass null as value to `VaInput` `modelValue` with no TS errors.
PR also includes small tweak of `useCleave` composable
> fix(input): add null to modelValue prop type declaration

- packages/ui/src/components/va-button/VaButton.demo.vue
- packages/ui/src/styles/resources/_mixins.scss
- #4288
<details>
```vue
@mixin va-disabled() {
cursor: default;
opacity: 0.4;
pointer-events: none;
user-select: none;
}
```
</details>
> fix(VaButton): added pointer events for disabled buttons

- packages/ui/src/components/va-card/_variables.scss
- packages/ui/src/styles/global/css-variables.scss
closes https://github.com/epicmaxco/vuestic-ui/issues/4308
1. In Va Card Component
CSS Variable used for Card Outlined Border has been updated from `va-background-element` to `va-background-border`
2.  Apply color schemes variable to define `--va-block-color`
<details>
```TS
// Sample Colors Configuration
createVuesticEssential({
config: {
colors: {
presets: {
dark: {
backgroundBorder: "ffffff",
},
},
},
},
});
```
</details>
> fix(VaCard): Ability to customize `outlined border` colour

- packages/docs/page-config/ui-elements/button/index.ts
The Button docs currently say `description-color` is used to change the text color. But that doesn't work, and the example instead uses the (seemingly correct) `text-color` prop.
> Change Button docs to say `text-color` instead of `description-color`

- packages/ui/src/composables/useTeleported.ts
- packages/ui/src/services/color/plugin/create-color-config-plugin.ts
- packages/ui/src/utils/dom.ts
> Color css variables must be rendered on app root element, not body (#4233)

- packages/ui/src/components/va-dropdown/plugin/index.ts
- packages/ui/src/components/va-modal/plugin/index.ts
- packages/ui/src/components/va-toast/plugin/index.ts
- packages/ui/src/services/breakpoint/plugin/index.ts
- packages/ui/src/services/color/plugin/index.ts
- packages/ui/src/services/colors-classes/plugin/index.ts
- packages/ui/src/services/global-config/plugin/index.ts
- packages/ui/src/services/vue-plugin/create-vuestic/create-vuestic.ts
- packages/ui/src/services/vue-plugin/types/components.ts
- packages/ui/src/services/vue-plugin/utils/global-properties.ts
In line with https://github.com/vuejs/router/pull/2295 and https://github.com/nuxt/nuxt/pull/28542, this moves to augment `vue` rather than `@vue/runtime` core.
This is now officially recommended [in the docs](https://vuejs.org/api/utility-types.html#componentcustomproperties) and it _must_ be done by all libraries or it will break types for _other_ libraries.
> fix: augment `vue` rather than `@vue/runtime-core`

- packages/ui/src/components/va-select/components/VaSelectOption/VaSelectOption.vue
Opening `<VaSelect>` with hundreds of items (tested 250) takes seconds to open when you click it.
For testing I used this code
<details>
```vue
<script setup lang="ts">
import { ref } from 'vue';
import VSelect from 'vue-select';
import 'vue-select/dist/vue-select.css';
const model = ref(null);
const model2 = ref(null);
const model3 = ref(null);
const testData = [...Array(250)].map((_, i) => `Item ${i}`);
</script>
<template>
<VaSelect
v-model="model"
label="test native"
:options="testData"
clearable
searchable
:highlight-matched-text="false"
/>
<hr class="my-4">
<VaSelect
v-model="model2"
label="test custom"
:options="testData"
clearable
searchable
:highlight-matched-text="false"
>
<template #option="slotData">
<div
role="option"
class="va-select-option" …
```
> chore: improve select option render time

- packages/ui/src/components/va-input/VaInput.vue
Add support for native `<input autocomplete=...>` attribute. [Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete).
This attribute is very necessary to handle autofilling forms (like login/register/address/...)
<details>
```vue
<VaInput
v-model="form.username"
:label="t('username')"
required
autofocus
autocomplete="username"
/>
<VaInput
v-model="form.password"
type="password"
:label="t('password')"
required
autocomplete="current-password"
/>
```
</details>
> feat(input): add native autocomplete attribute support

- packages/docs/page-config/ui-elements/toast/examples/Position.vue
- packages/docs/page-config/ui-elements/toast/index.ts
- packages/ui/.stylelintrc.js
- packages/ui/src/components/va-toast/VaToast.stories.ts
- packages/ui/src/components/va-toast/VaToast.vue
- packages/ui/src/components/va-toast/_variables.scss
- packages/ui/src/components/va-toast/hooks/useToastService.ts
- packages/ui/src/components/va-toast/toast.ts
- packages/ui/src/components/va-toast/types.ts
Add bottom-center, top-center position options to VaToast
Two new position options have been added to Vatoast: 'top-center' and 'bottom-center'.
closes https://github.com/epicmaxco/vuestic-ui/issues/4373
'top-center': Displays the toast at the top center of the screen.
'bottom-center': Displays the toast at the bottom center of the screen.
The Y-axis shift overlay and fade-out animation when the toast appears have been taken into account.
In order to handle the relationship of the animation starting point, it was necessary to add the 'center' class to the toast for these two options.
> feat(VaToast #4373): add bottom-center, top-center position options

- packages/ui/src/components/va-button-dropdown/VaButtonDropdown.vue
> fix(#4394): correct button dropdown teleport when split is used

- packages/ui/src/components/va-form-field/VaFormField.vue
Property `errorCount` is not working in `<VaFormField>`. It always shows only 1 error message.
<details>
```vue
<VaFormField
dirty
error
:error-count="2"
:error-messages="['error 1', 'error 2']"
>
example field
</VaFormField>
```
</details>
> fix(VaFormField): fix not working errorCount prop

- packages/ui/src/components/va-tree-view/components/VaTreeNode/VaTreeNode.vue
> fix(#4424): disable checkbox for disabled node

- packages/docs/layouts/default.vue
- packages/docs/pages/[page-config-category]/[page].vue
Changing between pages using sidebar visually looked awful, so I decided to add transitions.
Also, I found out and fixed an issue with additional scrolling after a click on sidebar element.
> fix(docs): add transition between docs pages, remove scrollToTop.

- packages/ui/src/components/va-date-input/VaDateInput.stories.ts
- packages/ui/src/components/va-date-input/VaDateInput.vue
- packages/ui/src/components/va-date-picker/VaDatePicker.stories.ts
- packages/ui/src/components/va-date-picker/components/VaDayPicker/va-date-picker-calendar-hook.ts
- packages/ui/src/components/va-date-picker/hooks/model-value-helper.ts
closes https://github.com/epicmaxco/vuestic-ui/issues/4454
> fix(#4454): empty range date picker start date

- packages/ui/src/components/va-date-picker/VaDatePicker.demo.vue
- packages/ui/src/components/va-date-picker/VaDatePicker.stories.ts
1. Closes #4299:
- Separate `Default` story;
- Disable screenshots on some stories;
2. Transferred `currentMonthDayView` in another story + added all types of checks;
3. Added tests for `Range` story;
4. Added `autodocs` tag;
> fix: chromatic screenshots tests status

- packages/ui/src/components/va-input/VaInput.vue
- packages/ui/src/composables/fabrics/useFocusableControl.ts
- packages/ui/src/composables/std/browser/useElementFocused.ts
Fix double focus event.
https://develop.ui.vuestic.dev/play#eNqNlm9P2zAQxr+KlTcFiTZCvOtKxUAgdRPbNDbeLJMIqZsYHNuK7cBU+t13vvxtCEnpm/Tud+fHru8hW++zUrPcUm/uLXSUMWWIpsaqZSAIYamSmSFbktEN2ZFNJlMyAXgSCJeOpNCGpDom5444mkyOi4Tvk+ssk1kDSXEjI6sBPKL8mJwvMS45nXEZQ+iETEpkcvypXXbJbTZc5YiyCNa9s1FEtW63uOI0HOmBSGflK86i57EyQLAsMFXZSihrhssQ6a6WhCKmI8sh0ycTfkQq1geILcCPW6yEoKNntU/3NVvBtwO6OKyv/EdGD9xPSQ40OXRHbbzT7iv9t5YvIxsqofelKoP7OFqL1Ptiq0YrrercwN9qHRqKAzhUbBvs4wa3oCqM6aD+VqMK7214K9eUHyhrTj/U1bQ5XFzRblzdfcjt4BCW7dIaxl4Lv7BOME33WRiaKg4cmugiOSURD7U+D7w8nCangbfcbtE2d7uFn5wW1H2ItuCeCcmnuAJUABZ4EAyM+8wzy6lr9OcoR4H5jFMRm4QsyRl5eyMPN5ZvGOfEJNSpXzPDpHj4iz3g72LjPBYalG5bxx/BRTHs7LRekVwwJwoThbyKj5xjYhy9sxWHWSrj8NTE0buKBD7uV0xDNJSmsDCYXmjK3Ix2URzcDs/gBBrOuU0HgKnbX7Z0gX6su3DbMuqK58IHkCo9oZ3DOa+S+KWdtapKWVXH21cY09056CWry95b …
> fix: correct even in useFocusableControl

- packages/ui/src/components/va-modal/VaModal.vue
- packages/ui/src/components/va-modal/modal.ts
Fix call useModal when options is object
> fix(modal): object options
